import type { Metadata } from "next";
import { SITE_NAME } from "@/lib/seo";
import ScoreClient from "./ScoreClient";
import { faqJsonLd } from "@/lib/schema-markup";

export const revalidate = 3600;

export const metadata: Metadata = {
  title: "Financial Health Score — Free 2-Minute Assessment (2026)",
  description:
    "Take our free 2-minute financial health quiz and get a personalised score out of 100. Discover your strengths, weaknesses, and next steps.",
  alternates: { canonical: "/score" },
  openGraph: {
    title: "Financial Health Score — Free 2-Minute Assessment",
    description:
      "Rate your financial health across savings, debt, super, insurance, investing, and planning. Get personalised recommendations.",
    images: [
      {
        url: "/api/og?title=Financial+Health+Score&subtitle=Free+2-Minute+Assessment&type=default",
        width: 1200,
        height: 630,
      },
    ],
  },
};

const SCORE_FAQS = [
  {
    q: "What does the Financial Health Score measure?",
    a: "The Financial Health Score is a free 2-minute self-assessment that rates your financial wellbeing out of 100 across six dimensions: (1) Savings — your emergency fund buffer and regular savings rate; (2) Debt — your debt-to-income ratio and whether you carry high-interest consumer debt; (3) Super — your projected superannuation balance relative to retirement needs; (4) Insurance — life, income protection, and total-and-permanent disability cover; (5) Investing — whether you have assets growing outside of super; and (6) Planning — whether you have a documented financial plan. Each dimension contributes equally to the total score.",
  },
  {
    q: "How accurate is the Financial Health Score?",
    a: "The score is a self-reported snapshot based on the answers you provide. It is designed to identify obvious gaps and prompt reflection, not to deliver a clinical financial assessment. The quiz uses publicly available benchmarks (ASFA retirement standard, emergency fund conventions, insurance coverage rules of thumb) to contextualise your answers. Because it relies on your estimates rather than verified financial data, treat the score as a useful starting point — not a definitive measure of your financial health.",
  },
  {
    q: "Is the Financial Health Score personal financial advice?",
    a: "No. The Financial Health Score is general information. It does not take into account your individual financial situation, objectives, tax position, or risk tolerance. The recommendations generated by the quiz are illustrative — they describe common strategies for people in similar situations, not advice tailored to your specific circumstances. If your score reveals gaps in insurance, super, or investment strategy, use the adviser finder (/advisors) to connect with a licensed professional who can assess your actual situation.",
  },
  {
    q: "Is my data saved when I take the quiz?",
    a: "If you are logged into an Invest.com.au account, your quiz answers and score are saved to your profile so you can track improvement over time. If you are not logged in, answers are held in your browser session only and are not transmitted to our servers. We do not share individual quiz results with third parties. See our Privacy Policy (/privacy) for full details.",
  },
];

const scoreFaqLd = faqJsonLd(SCORE_FAQS);

export default function ScorePage() {
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "WebApplication",
    name: `Financial Health Score — ${SITE_NAME}`,
    description:
      "Free 2-minute financial health assessment. Get a personalised score out of 100 with actionable recommendations.",
    url: "https://invest.com.au/score",
    applicationCategory: "FinanceApplication",
    operatingSystem: "Any",
    offers: { "@type": "Offer", price: "0", priceCurrency: "AUD" },
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      {scoreFaqLd && (
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(scoreFaqLd) }}
        />
      )}
      <ScoreClient />

      <div className="border-t border-slate-200 bg-white">
        <div className="container-custom max-w-3xl py-8 md:py-10">
          <h2 className="text-lg font-extrabold text-slate-900 mb-5">Frequently asked questions</h2>
          <div className="space-y-3">
            {SCORE_FAQS.map((faq) => (
              <details key={faq.q} className="group rounded-xl border border-slate-200 bg-slate-50">
                <summary className="flex cursor-pointer items-center justify-between gap-4 px-5 py-4 font-semibold text-slate-900 list-none">
                  {faq.q}
                  <span className="shrink-0 text-slate-400 group-open:rotate-180 transition-transform">▾</span>
                </summary>
                <p className="px-5 pb-5 text-sm text-slate-600 leading-relaxed">{faq.a}</p>
              </details>
            ))}
          </div>
        </div>
      </div>
    </>
  );
}
