/**
 * Code-defined seed data for the Get Matched router.
 *
 * Production reads intents, questions, and result templates from
 * `intent_taxonomy`, `get_matched_questions`, and
 * `get_matched_result_templates` (admin-editable). When the migration
 * hasn't been applied yet, or the tables are temporarily unreachable,
 * the read helpers fall back to these defaults so the public UI keeps
 * working. Plans still cannot be *persisted* without the database —
 * that's a hard requirement — but at least the questions render and
 * the result template is sensible.
 *
 * Keep these in lockstep with the SQL seed in
 * `supabase/migrations/20260724_gm01_get_matched_router.sql`. The DB
 * row is the source of truth once admin tunes it.
 */

import type {
  IntentDef,
  QuestionDef,
  ResultTemplate,
  RouteType,
} from "./types";

export const FALLBACK_INTENTS: IntentDef[] = [
  {
    id: -1,
    slug: "compare_platform",
    label: "Compare investing platforms",
    description: "Compare brokers, super funds, robo-advisors or property platforms.",
    default_route: "compare",
    default_brief_template: null,
    risk_level: "low",
    enabled: true,
    sort_order: 10,
    meta: {},
  },
  {
    id: -2,
    slug: "start_investing",
    label: "Start investing",
    description: "New to investing — figure out the right first step.",
    default_route: "compare",
    default_brief_template: null,
    risk_level: "low",
    enabled: true,
    sort_order: 20,
    meta: {},
  },
  {
    id: -3,
    slug: "smsf_property",
    label: "Invest through SMSF",
    description: "Property or shares inside a self-managed super fund.",
    default_route: "expert_team",
    default_brief_template: "smsf_property",
    risk_level: "medium",
    enabled: true,
    sort_order: 30,
    meta: {},
  },
  {
    id: -4,
    slug: "buy_property",
    label: "Buy investment property",
    description: "Residential investment property.",
    default_route: "individual",
    default_brief_template: "mortgage",
    risk_level: "low",
    enabled: true,
    sort_order: 40,
    meta: {},
  },
  {
    id: -5,
    slug: "opportunity_assessment",
    label: "Assess an opportunity",
    description: "Get help reviewing a specific deal or listing.",
    default_route: "expert_team",
    default_brief_template: "opportunity_assessment",
    risk_level: "medium",
    enabled: true,
    sort_order: 50,
    meta: {},
  },
  {
    id: -6,
    slug: "business_acquisition",
    label: "Buy a business",
    description: "Acquire an Australian business.",
    default_route: "expert_team",
    default_brief_template: "business_acquisition",
    risk_level: "medium",
    enabled: true,
    sort_order: 60,
    meta: {},
  },
  {
    id: -7,
    slug: "commercial_property",
    label: "Commercial property",
    description: "Buy, lease or invest in commercial property.",
    default_route: "expert_team",
    default_brief_template: "commercial_property",
    risk_level: "medium",
    enabled: true,
    sort_order: 70,
    meta: {},
  },
  {
    id: -8,
    slug: "foreign_investor",
    label: "Invest from overseas",
    description: "Non-resident or overseas investor into Australia.",
    default_route: "expert_team",
    default_brief_template: "foreign_investor",
    risk_level: "high",
    enabled: true,
    sort_order: 80,
    meta: {},
  },
  {
    id: -9,
    slug: "expat_investing",
    label: "Australian expat investing",
    description: "Australian living overseas investing back home.",
    default_route: "individual",
    default_brief_template: "expat",
    risk_level: "medium",
    enabled: true,
    sort_order: 90,
    meta: {},
  },
  {
    id: -10,
    slug: "financial_advice",
    label: "Get financial advice",
    description: "Licensed financial planning advice.",
    default_route: "individual",
    default_brief_template: "financial_adviser",
    risk_level: "high",
    enabled: true,
    sort_order: 100,
    meta: {},
  },
  {
    id: -11,
    slug: "tax_help",
    label: "Get tax / accounting help",
    description: "Tax planning or returns.",
    default_route: "individual",
    default_brief_template: "tax",
    risk_level: "medium",
    enabled: true,
    sort_order: 110,
    meta: {},
  },
  {
    id: -12,
    slug: "mortgage_help",
    label: "Get lending / mortgage help",
    description: "Home, investment or commercial finance.",
    default_route: "individual",
    default_brief_template: "mortgage",
    risk_level: "low",
    enabled: true,
    sort_order: 120,
    meta: {},
  },
  {
    id: -13,
    slug: "legal_help",
    label: "Get legal / conveyancing help",
    description: "Property settlement, contracts, structuring.",
    default_route: "individual",
    default_brief_template: "general",
    risk_level: "medium",
    enabled: true,
    sort_order: 130,
    meta: {},
  },
  {
    id: -14,
    slug: "second_opinion",
    label: "Get a second opinion",
    description: "Have advice or a deal independently reviewed.",
    default_route: "second_opinion",
    default_brief_template: "second_opinion",
    risk_level: "medium",
    enabled: true,
    sort_order: 140,
    meta: {},
  },
  {
    id: -15,
    slug: "listing_owner",
    label: "Post / list an opportunity",
    description: "Seller of a business, property or other deal.",
    default_route: "listing_brief",
    default_brief_template: "listing",
    risk_level: "low",
    enabled: true,
    sort_order: 150,
    meta: {},
  },
  {
    id: -16,
    slug: "listing_readiness",
    label: "Prepare a listing",
    description: "Get your opportunity ready to list.",
    default_route: "listing_brief",
    default_brief_template: "listing_readiness",
    risk_level: "low",
    enabled: true,
    sort_order: 160,
    meta: {},
  },
  {
    id: -17,
    slug: "not_sure",
    label: "Not sure yet",
    description: "Browse and figure it out as you go.",
    default_route: "guide",
    default_brief_template: null,
    risk_level: "low",
    enabled: true,
    sort_order: 999,
    meta: {},
  },
];

export const FALLBACK_QUESTIONS: QuestionDef[] = [
  {
    id: -1,
    slug: "starting_point",
    step: 1,
    kind: "select",
    prompt: "Where are you starting from?",
    subtitle: "We adapt the rest of the plan to your situation.",
    options: [
      { value: "australia", label: "Australia" },
      { value: "overseas", label: "Overseas" },
      { value: "expat", label: "Australian expat" },
      { value: "business", label: "Business / company" },
      { value: "professional", label: "Adviser / broker / professional" },
      { value: "listing_owner", label: "Listing owner / seller" },
    ],
    shown_if: {},
    maps_to: "starting_point",
    risk_weight: 0,
    mode: "both",
    enabled: true,
    sort_order: 10,
  },
  {
    id: -2,
    slug: "goal",
    step: 2,
    kind: "select",
    prompt: "What are you trying to do?",
    subtitle: "This is the most important step. Pick the closest match.",
    options: [
      { value: "compare_platform", label: "Compare investing platforms", intent_hint: "compare_platform", route_hint: "compare" },
      { value: "start_investing", label: "Start investing", intent_hint: "start_investing", route_hint: "compare" },
      { value: "buy_property", label: "Buy investment property", intent_hint: "buy_property", route_hint: "individual" },
      { value: "smsf_property", label: "Invest through my SMSF", intent_hint: "smsf_property", route_hint: "expert_team" },
      { value: "opportunity_assessment", label: "Assess an opportunity", intent_hint: "opportunity_assessment", route_hint: "expert_team" },
      { value: "business_acquisition", label: "Buy a business", intent_hint: "business_acquisition", route_hint: "expert_team" },
      { value: "commercial_property", label: "Commercial property", intent_hint: "commercial_property", route_hint: "expert_team" },
      { value: "foreign_investor", label: "Invest from overseas", intent_hint: "foreign_investor", route_hint: "expert_team" },
      { value: "financial_advice", label: "Get expert help", intent_hint: "financial_advice", route_hint: "individual" },
      { value: "listing_owner", label: "Post / list an opportunity", intent_hint: "listing_owner", route_hint: "listing_brief" },
      { value: "not_sure", label: "Not sure yet", intent_hint: "not_sure", route_hint: "guide" },
    ],
    shown_if: {},
    maps_to: "intent",
    risk_weight: 0,
    mode: "both",
    enabled: true,
    sort_order: 20,
  },
  {
    id: -3,
    slug: "smsf_situation",
    step: 3,
    kind: "select",
    prompt: "What best describes your SMSF situation?",
    subtitle: null,
    options: [
      { value: "no_smsf", label: "Thinking about setting up an SMSF" },
      { value: "considering_smsf", label: "Already considering one" },
      { value: "smsf_established", label: "I already have an SMSF" },
      { value: "smsf_property", label: "I want to buy property through SMSF" },
      { value: "not_sure", label: "Not sure" },
    ],
    shown_if: { intent: ["smsf_property"] },
    maps_to: "smsf_status",
    risk_weight: 0,
    mode: "guided",
    enabled: true,
    sort_order: 30,
  },
  {
    id: -4,
    slug: "opportunity_situation",
    step: 3,
    kind: "select",
    prompt: "What best describes the opportunity?",
    subtitle: null,
    options: [
      { value: "on_invest", label: "I found it on Invest.com.au" },
      { value: "elsewhere", label: "I found it elsewhere" },
      { value: "browsing", label: "I want to browse opportunities" },
      { value: "assessing", label: "I need help assessing a deal" },
      { value: "listing_it", label: "I want to list / sell one", route_hint: "listing_brief" },
    ],
    shown_if: { intent: ["opportunity_assessment"] },
    maps_to: "opportunity_context",
    risk_weight: 0,
    mode: "guided",
    enabled: true,
    sort_order: 30,
  },
  {
    id: -5,
    slug: "foreign_situation",
    step: 3,
    kind: "select",
    prompt: "What kind of investment from overseas?",
    subtitle: null,
    options: [
      { value: "property", label: "Australian property" },
      { value: "business", label: "Australian businesses" },
      { value: "tax_legal", label: "Need tax / legal help first" },
      { value: "finance", label: "Need finance / mortgage help" },
      { value: "not_sure", label: "Not sure where to start" },
    ],
    shown_if: { intent: ["foreign_investor"] },
    maps_to: "foreign_focus",
    risk_weight: 0,
    mode: "guided",
    enabled: true,
    sort_order: 30,
  },
  {
    id: -6,
    slug: "help_preference",
    step: 4,
    kind: "select",
    prompt: "How much help do you want?",
    subtitle: "You can change this later.",
    options: [
      { value: "info_only", label: "Just show me information", route_hint: "guide" },
      { value: "compare", label: "Show me platforms to compare", route_hint: "compare" },
      { value: "individual", label: "Show me individual experts", route_hint: "individual" },
      { value: "firm", label: "Show me firms / brokerages", route_hint: "firm" },
      { value: "expert_team", label: "Show me expert teams", route_hint: "expert_team" },
      { value: "investor_brief", label: "Create a brief for professionals", route_hint: "investor_brief" },
      { value: "not_sure", label: "Not sure — guide me" },
    ],
    shown_if: {},
    maps_to: "help_preference",
    risk_weight: 0,
    mode: "both",
    enabled: true,
    sort_order: 40,
  },
  {
    id: -7,
    slug: "budget",
    step: 5,
    kind: "select",
    prompt: "Budget or scale?",
    subtitle: "Bands only — keeps things private.",
    options: [
      { value: "under_10k", label: "Under A$10k" },
      { value: "10k_100k", label: "A$10k – A$100k" },
      { value: "100k_500k", label: "A$100k – A$500k" },
      { value: "500k_1m", label: "A$500k – A$1m" },
      { value: "1m_plus", label: "A$1m+" },
      { value: "prefer_not", label: "Prefer not to say" },
    ],
    shown_if: {},
    maps_to: "budget_band",
    risk_weight: 0,
    mode: "both",
    enabled: true,
    sort_order: 50,
  },
  {
    id: -8,
    slug: "timeline",
    step: 6,
    kind: "select",
    prompt: "Timeline?",
    subtitle: null,
    options: [
      { value: "now", label: "Now" },
      { value: "1_3_months", label: "1–3 months" },
      { value: "3_6_months", label: "3–6 months" },
      { value: "6_12_months", label: "6–12 months" },
      { value: "researching", label: "Just researching" },
    ],
    shown_if: {},
    maps_to: "timeline",
    risk_weight: 0,
    mode: "both",
    enabled: true,
    sort_order: 60,
  },
];

export const FALLBACK_TEMPLATES: Record<RouteType, ResultTemplate> = {
  compare: {
    id: -1,
    route: "compare",
    intent_slug: null,
    headline: "Compare Platforms",
    why_text:
      "Based on your answers, the right next step is to compare platforms side-by-side. You can stay completely independent — Invest.com.au provides general information only.",
    checklist: [
      { label: "See the comparison shortlist", href: "/compare" },
      { label: "Run the fee calculator", href: "/calculators/fee-impact" },
      { label: "Check what each broker actually charges" },
      { label: "Save your shortlist" },
    ],
    primary_cta: { label: "Compare platforms", href: "/compare" },
    secondary_ctas: [
      { label: "Fee calculator", href: "/calculators/fee-impact" },
      { label: "Get expert help if unsure", href: "/get-matched?goal=financial_advice" },
    ],
    cross_sells: [
      { label: "How brokerage actually adds up", href: "/article/how-brokerage-adds-up", icon: "calculator" },
      { label: "CHESS vs custodial", href: "/article/chess-vs-custodial", icon: "shield-check" },
    ],
    enabled: true,
  },
  browse: {
    id: -2,
    route: "browse",
    intent_slug: null,
    headline: "Browse Opportunities",
    why_text:
      "Open opportunities matching your shape. You stay anonymous unless you choose to enquire.",
    checklist: [
      { label: "View matching opportunities", href: "/invest" },
      { label: "Save your opportunity alerts" },
      { label: "Create an Opportunity Brief" },
    ],
    primary_cta: { label: "View opportunities", href: "/invest" },
    secondary_ctas: [
      { label: "Get help assessing", href: "/get-matched?goal=opportunity_assessment" },
    ],
    cross_sells: [
      { label: "How to read a private deal", href: "/articles", icon: "file-text" },
    ],
    enabled: true,
  },
  individual: {
    id: -3,
    route: "individual",
    intent_slug: null,
    headline: "Verified Individual Expert",
    why_text:
      "A single verified professional is likely the cleanest fit. You stay in control — they only see your details after you decide to share them.",
    checklist: [
      { label: "Browse verified individuals", href: "/advisors?provider_type=individual" },
      { label: "Compare two profiles side-by-side" },
      { label: "Create a brief for one professional" },
    ],
    primary_cta: { label: "Browse individuals", href: "/advisors?provider_type=individual" },
    secondary_ctas: [
      { label: "Or consider a firm", href: "/advisors?provider_type=firm" },
      { label: "Create an Investor Brief", href: "/briefs/new" },
    ],
    cross_sells: [
      { label: "Questions to ask any adviser", href: "/articles", icon: "message-circle" },
    ],
    enabled: true,
  },
  firm: {
    id: -4,
    route: "firm",
    intent_slug: null,
    headline: "Firm or Brokerage",
    why_text:
      "You prefer the structure of a firm. Browse verified firms — each one has at least one verified representative.",
    checklist: [
      { label: "Browse verified firms", href: "/advisors?provider_type=firm" },
      { label: "Compare firm representatives" },
      { label: "Create an Investor Brief" },
    ],
    primary_cta: { label: "Browse firms", href: "/advisors?provider_type=firm" },
    secondary_ctas: [
      { label: "View firm reviews", href: "/advisors" },
      { label: "Create an Investor Brief", href: "/briefs/new" },
    ],
    cross_sells: [
      { label: "Firm vs individual: how to pick", href: "/articles", icon: "users" },
    ],
    enabled: true,
  },
  expert_team: {
    id: -5,
    route: "expert_team",
    intent_slug: null,
    headline: "Verified Expert Team",
    why_text:
      "Your situation usually involves more than one professional. A verified expert team coordinates the work so you don't.",
    checklist: [
      { label: "Browse verified expert teams", href: "/advisors#expert-teams" },
      { label: "See who is on each team" },
      { label: "Create an Investor Brief for a team" },
    ],
    primary_cta: { label: "Browse expert teams", href: "/advisors#expert-teams" },
    secondary_ctas: [
      { label: "Create an Investor Brief", href: "/briefs/new" },
      { label: "Who do I need on my team?", href: "/articles" },
    ],
    cross_sells: [
      { label: "How verified teams work", href: "/articles", icon: "users" },
    ],
    enabled: true,
  },
  investor_brief: {
    id: -6,
    route: "investor_brief",
    intent_slug: null,
    headline: "Create an Investor Brief",
    why_text:
      "You're ready to be contacted by a verified provider. We'll route your masked brief to the right professionals.",
    checklist: [
      { label: "Confirm the goal of your brief" },
      { label: "Pick smart-match, direct or multi-response" },
      { label: "Add contact and consent" },
    ],
    primary_cta: { label: "Create brief", href: "/briefs/new" },
    secondary_ctas: [
      { label: "Browse providers first", href: "/advisors" },
    ],
    cross_sells: [
      { label: "How accept works", href: "/articles", icon: "info" },
    ],
    enabled: true,
  },
  listing_brief: {
    id: -7,
    route: "listing_brief",
    intent_slug: null,
    headline: "Prepare Your Listing",
    why_text:
      "You're on the seller side. Prepare a Listing Brief so verified professionals can help you get listing-ready and reach buyers.",
    checklist: [
      { label: "Listing readiness check" },
      { label: "Get valuation help" },
      { label: "Prepare your due-diligence pack" },
      { label: "Create your Listing Brief" },
    ],
    primary_cta: { label: "Create Listing Brief", href: "/briefs/new?template=listing_readiness" },
    secondary_ctas: [
      { label: "Post your opportunity", href: "/invest" },
      { label: "Speak to listing experts", href: "/advisors" },
    ],
    cross_sells: [
      { label: "Listing checklist", href: "/articles", icon: "file-text" },
    ],
    enabled: true,
  },
  second_opinion: {
    id: -8,
    route: "second_opinion",
    intent_slug: null,
    headline: "Second Opinion Brief",
    why_text:
      "You want an independent review of advice or a deal. Verified professionals can review it under their own licence and terms.",
    checklist: [
      { label: "Describe what needs reviewing" },
      { label: "Pick the right review type" },
      { label: "Create your Second Opinion Brief" },
    ],
    primary_cta: { label: "Create Second Opinion Brief", href: "/briefs/new?template=second_opinion" },
    secondary_ctas: [
      { label: "Find a licensed adviser", href: "/advisors?type=financial_planner" },
      { label: "Find a tax / accounting reviewer", href: "/advisors?type=tax_agent" },
    ],
    cross_sells: [
      { label: "When to get a second opinion", href: "/articles", icon: "shield" },
    ],
    enabled: true,
  },
  guide: {
    id: -9,
    route: "guide",
    intent_slug: null,
    headline: "Start with information",
    why_text:
      "You're early — here is the curated reading and tooling for where you are.",
    checklist: [
      { label: "Read the most relevant guide" },
      { label: "Run a calculator" },
      { label: "Come back when you're ready" },
    ],
    primary_cta: { label: "Browse guides", href: "/articles" },
    secondary_ctas: [
      { label: "Start the action plan over", href: "/get-matched" },
    ],
    cross_sells: [
      { label: "Most popular guides", href: "/articles", icon: "file-text" },
    ],
    enabled: true,
  },
};

/** Look up a fallback template for an intent-specific override, then the
 *  generic route default. Mirrors `getResultTemplate`'s precedence. */
export function getFallbackTemplate(
  route: RouteType,
): ResultTemplate {
  return FALLBACK_TEMPLATES[route] ?? FALLBACK_TEMPLATES.guide;
}
