import { describe, it, expect, vi, beforeEach } from "vitest";

vi.mock("@/lib/logger", () => ({
  logger: vi.fn(() => ({
    debug: vi.fn(),
    info: vi.fn(),
    warn: vi.fn(),
    error: vi.fn(),
  })),
}));

const { mockIsFlagEnabled, mockIsRateLimited, mockGetUser, mockFrom } =
  vi.hoisted(() => ({
    mockIsFlagEnabled: vi.fn<(...a: unknown[]) => Promise<boolean>>(
      async () => true,
    ),
    mockIsRateLimited: vi.fn<(...a: unknown[]) => Promise<boolean>>(
      async () => false,
    ),
    mockGetUser: vi.fn<(...a: unknown[]) => Promise<unknown>>(async () => ({
      data: { user: { id: "u1", email: "user@example.com" } },
      error: null,
    })),
    mockFrom: vi.fn(),
  }));

vi.mock("@/lib/feature-flags", () => ({
  isFlagEnabled: (...a: unknown[]) => mockIsFlagEnabled(...a),
}));
vi.mock("@/lib/rate-limit", () => ({
  isRateLimited: (...a: unknown[]) => mockIsRateLimited(...a),
}));
vi.mock("@/lib/supabase/server", () => ({
  createClient: vi.fn(async () => ({
    from: mockFrom,
    auth: { getUser: mockGetUser },
  })),
}));

function makeBuilder(result: unknown) {
  const b: Record<string, unknown> = {};
  for (const m of ["select", "update", "eq"]) b[m] = vi.fn(() => b);
  b.maybeSingle = vi.fn(async () => result);
  b.then = (cb: (v: unknown) => unknown) => Promise.resolve(cb(result));
  return b;
}

import { POST, DELETE } from "@/app/api/account/scenarios/[id]/share/route";

const VALID_UUID = "22222222-2222-2222-2222-222222222222";
const ctx = (id: string) => ({ params: Promise.resolve({ id }) });

describe("/api/account/scenarios/[id]/share", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockIsFlagEnabled.mockResolvedValue(true);
    mockIsRateLimited.mockResolvedValue(false);
    mockGetUser.mockResolvedValue({
      data: { user: { id: "u1", email: "user@example.com" } },
      error: null,
    });
  });

  it("POST 404s when the flag is off", async () => {
    mockIsFlagEnabled.mockResolvedValue(false);
    const res = await POST(new Request("http://x"), ctx(VALID_UUID));
    expect(res.status).toBe(404);
  });

  it("POST 401s when unauthenticated", async () => {
    mockGetUser.mockResolvedValue({ data: { user: null }, error: null });
    const res = await POST(new Request("http://x"), ctx(VALID_UUID));
    expect(res.status).toBe(401);
  });

  it("POST 404s on a non-uuid id", async () => {
    const res = await POST(new Request("http://x"), ctx("not-a-uuid"));
    expect(res.status).toBe(404);
  });

  it("POST generates a fresh 48-char hex token when none exists", async () => {
    let call = 0;
    mockFrom.mockImplementation(() => {
      call += 1;
      // 1st: read existing (no token); 2nd: update→select token.
      if (call === 1)
        return makeBuilder({
          data: { id: VALID_UUID, share_token: null },
          error: null,
        });
      // Capture whatever token the route generated by echoing what it set.
      const b = makeBuilder({ data: { share_token: "PLACEHOLDER" }, error: null });
      const origUpdate = b.update as (patch: Record<string, unknown>) => unknown;
      b.update = vi.fn((patch: Record<string, unknown>) => {
        b.maybeSingle = vi.fn(async () => ({
          data: { share_token: patch.share_token },
          error: null,
        }));
        return origUpdate(patch);
      });
      return b;
    });
    const res = await POST(new Request("http://x"), ctx(VALID_UUID));
    expect(res.status).toBe(200);
    const json = await res.json();
    expect(json.share_token).toMatch(/^[0-9a-f]{48}$/);
  });

  it("POST is idempotent — returns the existing token unchanged", async () => {
    const existing = "a".repeat(48);
    mockFrom.mockImplementation(() =>
      makeBuilder({
        data: { id: VALID_UUID, share_token: existing },
        error: null,
      }),
    );
    const res = await POST(new Request("http://x"), ctx(VALID_UUID));
    expect(res.status).toBe(200);
    const json = await res.json();
    expect(json.share_token).toBe(existing);
  });

  it("POST 404s when the scenario is not found / not owned", async () => {
    mockFrom.mockImplementation(() =>
      makeBuilder({ data: null, error: null }),
    );
    const res = await POST(new Request("http://x"), ctx(VALID_UUID));
    expect(res.status).toBe(404);
  });

  it("DELETE revokes the share token", async () => {
    mockFrom.mockImplementation(() =>
      makeBuilder({ data: { id: VALID_UUID }, error: null }),
    );
    const res = await DELETE(new Request("http://x"), ctx(VALID_UUID));
    expect(res.status).toBe(200);
    const json = await res.json();
    expect(json.ok).toBe(true);
  });

  it("DELETE 404s when there is nothing to revoke", async () => {
    mockFrom.mockImplementation(() =>
      makeBuilder({ data: null, error: null }),
    );
    const res = await DELETE(new Request("http://x"), ctx(VALID_UUID));
    expect(res.status).toBe(404);
  });

  it("DELETE 429s when rate limited", async () => {
    mockIsRateLimited.mockResolvedValue(true);
    const res = await DELETE(new Request("http://x"), ctx(VALID_UUID));
    expect(res.status).toBe(429);
  });
});
