import { createClient } from "@/lib/supabase/server";
import type { Broker } from "@/lib/types";
import { GENERAL_ADVICE_WARNING, ADVERTISER_DISCLOSURE_SHORT } from "@/lib/compliance";

export const metadata = { title: "Platform Comparison Report", robots: "noindex" };

export default async function ComparisonExportPage({
  searchParams,
}: {
  searchParams: Promise<{ brokers?: string }>;
}) {
  const params = await searchParams;
  const slugs = (params.brokers || "").split(",").filter(Boolean);

  if (slugs.length === 0) {
    return <div className="p-8 text-center text-slate-500">No brokers selected. Add ?brokers=slug1,slug2 to URL.</div>;
  }

  const supabase = await createClient();
  const { data } = await supabase
    .from("brokers")
    .select("*")
    .in("slug", slugs)
    .eq("status", "active");

  const brokers = (data as Broker[]) || [];
  const now = new Date().toLocaleDateString("en-AU", { day: "numeric", month: "long", year: "numeric" });

  return (
    <div className="max-w-[800px] mx-auto px-6 py-10 font-sans text-slate-900">
      {/* Header */}
      <div className="border-b-[3px] border-green-700 pb-4 mb-6">
        <div className="flex justify-between items-center">
          <div>
            <h1 className="text-2xl font-extrabold m-0">Broker Comparison Report</h1>
            <p className="text-xs text-slate-500 mt-1 mb-0">Generated {now} by invest.com.au</p>
          </div>
          <div className="text-sm font-bold text-green-700">invest.com.au</div>
        </div>
      </div>

      {/* Comparison Table */}
      <table className="w-full border-collapse text-[13px]">
        <thead>
          <tr className="bg-slate-50 border-b-2 border-slate-200">
            <th className="text-left px-3 py-2.5 font-semibold text-slate-600">Feature</th>
            {brokers.map((b) => (
              <th key={b.slug} className="text-center px-3 py-2.5 font-bold" style={{ color: b.color }}>{b.name}</th>
            ))}
          </tr>
        </thead>
        <tbody>
          {[
            { label: "ASX Fee", fn: (b: Broker) => b.asx_fee || "N/A" },
            { label: "US Fee", fn: (b: Broker) => b.us_fee || "N/A" },
            { label: "FX Rate", fn: (b: Broker) => b.fx_rate != null ? `${b.fx_rate}%` : "N/A" },
            { label: "CHESS Sponsored", fn: (b: Broker) => b.chess_sponsored ? "Yes" : "No" },
            { label: "SMSF Support", fn: (b: Broker) => b.smsf_support ? "Yes" : "No" },
            { label: "Rating", fn: (b: Broker) => b.rating ? `${b.rating}/5` : "N/A" },
            { label: "Min Deposit", fn: (b: Broker) => b.min_deposit || "N/A" },
            { label: "Inactivity Fee", fn: (b: Broker) => b.inactivity_fee || "None" },
          ].map((row, i) => (
            <tr key={row.label} className={`border-b border-slate-200 ${i % 2 === 0 ? "bg-white" : "bg-slate-50"}`}>
              <td className="px-3 py-2 font-medium">{row.label}</td>
              {brokers.map((b) => (
                <td key={b.slug} className="text-center px-3 py-2">{row.fn(b)}</td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>

      {/* Pros/Cons */}
      <div className="mt-8">
        <h2 className="text-base font-bold mb-4">Key Strengths & Weaknesses</h2>
        <div className="grid gap-4" style={{ gridTemplateColumns: `repeat(${Math.min(brokers.length, 3)}, 1fr)` }}>
          {brokers.map((b) => (
            <div
              key={b.slug}
              className="border border-slate-200 rounded-lg p-3 border-t-[3px]"
              style={{ borderTopColor: b.color }}
            >
              <h3 className="text-sm font-bold mb-2">{b.name}</h3>
              {b.pros && b.pros.length > 0 && (
                <div className="mb-2">
                  <p className="text-[10px] font-semibold text-green-600 mb-1">PROS</p>
                  {b.pros.slice(0, 3).map((p, i) => (
                    <p key={i} className="text-[11px] text-slate-700 my-0.5">+ {p}</p>
                  ))}
                </div>
              )}
              {b.cons && b.cons.length > 0 && (
                <div>
                  <p className="text-[10px] font-semibold text-red-500 mb-1">CONS</p>
                  {b.cons.slice(0, 3).map((c, i) => (
                    <p key={i} className="text-[11px] text-slate-700 my-0.5">- {c}</p>
                  ))}
                </div>
              )}
            </div>
          ))}
        </div>
      </div>

      {/* Disclaimer */}
      <div className="mt-8 p-3 bg-slate-50 rounded-lg text-[10px] text-slate-500 leading-relaxed">
        <strong>Disclaimer:</strong> {GENERAL_ADVICE_WARNING} {ADVERTISER_DISCLOSURE_SHORT}
        <br /><br />
        Report generated by invest.com.au. Data sourced from official platform fee schedules and verified by our editorial team.
        Fees are subject to change. Always verify current fees on the platform&apos;s website before opening an account.
      </div>

      {/* Auto-print script */}
      <script dangerouslySetInnerHTML={{ __html: `if(typeof window!=='undefined'){window.onload=function(){window.print()}}` }} />
    </div>
  );
}
