-- Migration: api_latency_samples — per-route p95 latency tracking.
--
-- FIN_NOTEBOOK pre-launch observability: catch slow-route regressions
-- before users do. Cheap, append-only — every API route can sample
-- itself on a small percentage of requests (default 1%) and the
-- per-day cron rolls up to a max-p95 alert.
--
-- Schema:
--   - route_path: the API route that was sampled (e.g. /api/submit-lead).
--   - duration_ms: total request time.
--   - status: HTTP status code returned.
--   - sampled_at: when the sample was taken.
--
-- Append-only; rolled up daily by /api/cron/slo-monitor and pruned at
-- 30 days by the existing observability-retention cron.
--
-- RLS: service-role-only — nothing here is user-facing.
--
-- Rollback:
--   DROP TABLE IF EXISTS public.api_latency_samples;

BEGIN;

CREATE TABLE IF NOT EXISTS public.api_latency_samples (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  route_path text NOT NULL,
  duration_ms integer NOT NULL,
  status smallint NOT NULL,
  sampled_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT api_latency_duration_positive CHECK (duration_ms >= 0 AND duration_ms <= 600000)
);

CREATE INDEX IF NOT EXISTS idx_api_latency_route_sampled
  ON public.api_latency_samples (route_path, sampled_at DESC);

CREATE INDEX IF NOT EXISTS idx_api_latency_sampled_at
  ON public.api_latency_samples (sampled_at DESC);

ALTER TABLE public.api_latency_samples ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Service role manages api_latency_samples" ON public.api_latency_samples;
CREATE POLICY "Service role manages api_latency_samples"
  ON public.api_latency_samples FOR ALL TO service_role USING (true) WITH CHECK (true);

COMMIT;
