-- ============================================================================
-- Migration: Backfill marketplace-accounts family — A-03 batch 4
-- Date:      2026-05-02 (queued under 20260607 to sort after 20260606 C-stream)
-- Audit ref: docs/audits/drift-list.md (A-06 marketplace family, shipped via
--            A-03 batch 4 iteration)
-- Queue item: docs/audits/REMEDIATION_QUEUE.md A-03
--
-- Tables covered (5):
--   1. broker_accounts       — partner-portal broker identity; 58 app refs
--   2. campaign_daily_stats  — aggregated per-broker-per-day stats; 13 refs
--   3. campaign_events       — raw click/impression/conversion log; 14 refs
--   4. campaign_templates    — broker-managed campaign scheduling rules; 4 refs
--   5. allocation_decisions  — marketplace allocation engine audit log; 4 refs
--
-- Why it matters
--   All 5 tables were in lib/database.types.ts but absent from the migration
--   tree. A clean rebuild would lose the marketplace partner-portal and the
--   allocation engine entirely. More critically, three of them hold per-broker
--   billing events (campaign_events.cost_cents), PII (broker_accounts.email,
--   phone, webhook_url) and raw click metadata (ip_hash, session_id) — all
--   without any RLS protection.
--
-- Prior policy discovery (mandatory per A-03 protocol)
--   grep -nE "(POLICY.*(broker_accounts|campaign_daily_stats|campaign_events|
--             campaign_templates|allocation_decisions)|...ENABLE)" \
--     supabase/migrations/*.sql
--   → 0 matches. No existing RLS policies on any of these 5 tables.
--
-- Schema source of truth
--   lib/database.types.ts (Database['public']['Tables'][...].Row) +
--   live DB cross-check. Notable gaps:
--   - broker_accounts.marketplace_terms_accepted: used in broker portal
--     (app/broker-portal/page.tsx:66) but absent from types.ts — pre-existing
--     type drift; not added here (out of scope, types.ts is the schema source).
--   - campaign_daily_stats/campaign_events.id: Insert has id?: never →
--     GENERATED ALWAYS AS IDENTITY (not bigserial — live DB confirmed).
--   - campaign_templates.id: Insert has id?: number →
--     GENERATED BY DEFAULT AS IDENTITY (allows explicit id assignment).
--
-- Callers (sampled):
--   broker_accounts:
--     app/api/marketplace/register/route.ts          (admin: INSERT new broker)
--     app/api/marketplace/notify/route.ts            (admin: SELECT by broker_slug)
--     app/broker-portal/page.tsx                     (browser: SELECT own account)
--     app/broker-portal/analytics/page.tsx           (browser: SELECT own account)
--     lib/marketplace/allocation.ts                  (admin: SELECT status/package)
--     app/api/cron/low-balance-alerts/route.ts       (admin: SELECT active accounts)
--   campaign_daily_stats:
--     app/broker-portal/analytics/page.tsx           (browser: SELECT own stats)
--     app/broker-portal/page.tsx                     (browser: SELECT recent stats)
--     app/api/cron/marketplace-stats/route.ts        (admin: INSERT/UPDATE daily agg)
--   campaign_events:
--     app/broker-portal/page.tsx                     (browser: SELECT recent clicks)
--     lib/marketplace/allocation.ts                  (admin: INSERT every event)
--     app/admin/marketplace/attribution/page.tsx     (admin: SELECT analytics)
--   campaign_templates:
--     app/broker-portal/campaigns/new/page.tsx       (browser: INSERT + SELECT own)
--     app/broker-portal/campaigns/[id]/edit/page.tsx (browser: INSERT + SELECT own)
--   allocation_decisions:
--     lib/marketplace/allocation.ts                  (admin: INSERT every decision)
--     app/admin/marketplace/decisions/page.tsx       (admin: SELECT analytics)
--
-- RLS policy summary
--   broker_accounts:
--     service_role: FOR ALL  (registration, crons, admin management)
--     authenticated SELECT:  WHERE auth_user_id = auth.uid()
--       Broker reads own account row (portal header, analytics). No
--       INSERT/UPDATE/DELETE — registration + status changes flow through
--       admin API routes (service-role client).
--   campaign_daily_stats:
--     service_role: FOR ALL  (stats cron writes)
--     authenticated SELECT:  WHERE broker_slug IN (SELECT broker_slug FROM
--       broker_accounts WHERE auth_user_id = auth.uid())
--       Broker analytics dashboard reads own daily stats. Write path is the
--       marketplace-stats cron via service-role client.
--   campaign_events:
--     service_role: FOR ALL  (allocation engine inserts every event)
--     authenticated SELECT:  same broker_slug subquery pattern
--       Broker portal homepage reads recent clicks and today's spend.
--       Write path is lib/marketplace/allocation.ts via admin client.
--   campaign_templates:
--     service_role: FOR ALL  (admin operations)
--     authenticated FOR ALL: same broker_slug subquery + WITH CHECK
--       Broker creates/edits campaign scheduling templates via browser client
--       (campaigns/new and campaigns/[id]/edit).
--   allocation_decisions:
--     service_role: FOR ALL  (allocation engine + admin analytics only)
--     No authenticated policy — internal engine log, no broker-portal reads.
--     Matches feature_flags / web_vitals_samples service-role-only pattern.
--
-- Subquery security note
--   The authenticated SELECT/ALL policies on campaign_daily_stats,
--   campaign_events, and campaign_templates reference broker_accounts in a
--   subquery. Postgres evaluates the subquery under the caller's session
--   role, so RLS on broker_accounts applies — authenticated users see only
--   their own account row. The subquery is therefore self-scoping: an
--   attacker who omits broker_slug filter in code cannot see other brokers'
--   data because the subquery returns only their own broker_slug.
--
-- Idempotency
--   CREATE TABLE IF NOT EXISTS on each table — no-op when it exists.
--   DROP POLICY IF EXISTS + CREATE POLICY for every policy.
--   CREATE INDEX IF NOT EXISTS — no-op when index exists.
--   ENABLE/FORCE ROW LEVEL SECURITY is idempotent on already-RLS tables.
--
-- Rollback
--   BEGIN;
--     -- broker_accounts
--     DROP POLICY IF EXISTS "service_role full access" ON public.broker_accounts;
--     DROP POLICY IF EXISTS "broker reads own account" ON public.broker_accounts;
--     DROP INDEX IF EXISTS idx_broker_accounts_auth_user_id;
--     DROP INDEX IF EXISTS idx_broker_accounts_broker_slug;
--     ALTER TABLE public.broker_accounts DISABLE ROW LEVEL SECURITY;
--     -- DROP TABLE public.broker_accounts; -- destructive, clean rebuild only
--     -- campaign_daily_stats
--     DROP POLICY IF EXISTS "service_role full access" ON public.campaign_daily_stats;
--     DROP POLICY IF EXISTS "broker reads own daily stats" ON public.campaign_daily_stats;
--     DROP INDEX IF EXISTS idx_campaign_daily_stats_broker_date;
--     ALTER TABLE public.campaign_daily_stats DISABLE ROW LEVEL SECURITY;
--     -- campaign_events
--     DROP POLICY IF EXISTS "service_role full access" ON public.campaign_events;
--     DROP POLICY IF EXISTS "broker reads own events" ON public.campaign_events;
--     DROP INDEX IF EXISTS idx_campaign_events_broker_created;
--     ALTER TABLE public.campaign_events DISABLE ROW LEVEL SECURITY;
--     -- campaign_templates
--     DROP POLICY IF EXISTS "service_role full access" ON public.campaign_templates;
--     DROP POLICY IF EXISTS "broker manages own templates" ON public.campaign_templates;
--     DROP INDEX IF EXISTS idx_campaign_templates_broker_slug;
--     ALTER TABLE public.campaign_templates DISABLE ROW LEVEL SECURITY;
--     -- allocation_decisions
--     DROP POLICY IF EXISTS "service_role full access" ON public.allocation_decisions;
--     ALTER TABLE public.allocation_decisions DISABLE ROW LEVEL SECURITY;
--   COMMIT;
-- ============================================================================

BEGIN;

-- ============================================================================
-- 1. broker_accounts
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.broker_accounts (
  id                    uuid         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  auth_user_id          uuid         NOT NULL,
  broker_slug           text         NOT NULL,
  email                 text         NOT NULL,
  full_name             text         NOT NULL,
  company_name          text,
  role                  text         NOT NULL DEFAULT 'owner',
  status                text         NOT NULL DEFAULT 'pending',
  package_id            integer,
  package_started_at    timestamptz,
  phone                 text,
  postback_api_key      text,
  webhook_url           text,
  email_preferences     jsonb,
  invited_by            text,
  last_login_at         timestamptz,
  terms_accepted_at     timestamptz,
  terms_version         text,
  updated_at            timestamptz,
  created_at            timestamptz  DEFAULT now()
);

-- Auth-user lookup (every portal auth check) + broker_slug lookup (foreign
-- references from campaigns, wallets, events all JOIN on broker_slug).
CREATE INDEX IF NOT EXISTS idx_broker_accounts_auth_user_id
  ON public.broker_accounts (auth_user_id);
CREATE INDEX IF NOT EXISTS idx_broker_accounts_broker_slug
  ON public.broker_accounts (broker_slug);

ALTER TABLE public.broker_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.broker_accounts FORCE  ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "service_role full access" ON public.broker_accounts;
CREATE POLICY "service_role full access"
  ON public.broker_accounts
  FOR ALL TO service_role
  USING (true) WITH CHECK (true);

-- Brokers read their own account row via the browser client (portal header,
-- analytics page, marketplace terms check). No INSERT/UPDATE/DELETE: broker
-- registration + account management go through admin API routes.
DROP POLICY IF EXISTS "broker reads own account" ON public.broker_accounts;
CREATE POLICY "broker reads own account"
  ON public.broker_accounts
  FOR SELECT TO authenticated
  USING (auth_user_id = auth.uid());

-- ============================================================================
-- 2. campaign_daily_stats
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.campaign_daily_stats (
  id             bigint       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  broker_slug    text         NOT NULL,
  campaign_id    integer      NOT NULL,
  stat_date      date         NOT NULL,
  clicks         integer      NOT NULL DEFAULT 0,
  conversions    integer      NOT NULL DEFAULT 0,
  impressions    integer      NOT NULL DEFAULT 0,
  spend_cents    integer      NOT NULL DEFAULT 0
);

-- Analytics dashboard orders by broker_slug + stat_date; 14-day window lookups.
CREATE INDEX IF NOT EXISTS idx_campaign_daily_stats_broker_date
  ON public.campaign_daily_stats (broker_slug, stat_date DESC);

ALTER TABLE public.campaign_daily_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campaign_daily_stats FORCE  ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "service_role full access" ON public.campaign_daily_stats;
CREATE POLICY "service_role full access"
  ON public.campaign_daily_stats
  FOR ALL TO service_role
  USING (true) WITH CHECK (true);

-- Broker analytics dashboard reads 14-day sparklines and trend data via
-- browser client. The subquery is safe: broker_accounts owner-isolation
-- policy (above) ensures auth.uid() maps to exactly one broker_slug.
DROP POLICY IF EXISTS "broker reads own daily stats" ON public.campaign_daily_stats;
CREATE POLICY "broker reads own daily stats"
  ON public.campaign_daily_stats
  FOR SELECT TO authenticated
  USING (
    broker_slug IN (
      SELECT ba.broker_slug
      FROM   public.broker_accounts ba
      WHERE  ba.auth_user_id = auth.uid()
    )
  );

-- ============================================================================
-- 3. campaign_events
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.campaign_events (
  id                       bigint       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  broker_slug              text         NOT NULL,
  campaign_id              integer      NOT NULL,
  event_type               text         NOT NULL,
  cost_cents               integer      NOT NULL DEFAULT 0,
  click_id                 text,
  conversion_value_cents   integer,
  created_at               timestamptz  DEFAULT now(),
  device_type              text,
  ip_hash                  text,
  page                     text,
  placement_id             integer,
  scenario                 text,
  session_id               text,
  user_agent               text
);

-- Broker portal reads by broker_slug + created_at (recent-7-days window).
-- Note: idx_campaign_events_campaign_id already exists from
-- 20260310_fix_performance_advisories.sql — CREATE INDEX IF NOT EXISTS is
-- idempotent and the duplicate-name attempt is a no-op.
CREATE INDEX IF NOT EXISTS idx_campaign_events_broker_created
  ON public.campaign_events (broker_slug, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_campaign_events_campaign_id
  ON public.campaign_events (campaign_id);

ALTER TABLE public.campaign_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campaign_events FORCE  ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "service_role full access" ON public.campaign_events;
CREATE POLICY "service_role full access"
  ON public.campaign_events
  FOR ALL TO service_role
  USING (true) WITH CHECK (true);

-- Broker portal homepage reads recent clicks and today's spend via browser
-- client (app/broker-portal/page.tsx). Same subquery pattern as daily_stats.
-- Write path (allocation.ts) uses admin client — no INSERT policy needed.
DROP POLICY IF EXISTS "broker reads own events" ON public.campaign_events;
CREATE POLICY "broker reads own events"
  ON public.campaign_events
  FOR SELECT TO authenticated
  USING (
    broker_slug IN (
      SELECT ba.broker_slug
      FROM   public.broker_accounts ba
      WHERE  ba.auth_user_id = auth.uid()
    )
  );

-- ============================================================================
-- 4. campaign_templates
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.campaign_templates (
  id                    integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  broker_slug           text         NOT NULL,
  name                  text         NOT NULL,
  placement_id          integer,
  inventory_type        text,
  rate_cents            integer,
  daily_budget_cents    integer,
  total_budget_cents    integer,
  active_days           integer[],
  active_hours_start    integer,
  active_hours_end      integer,
  created_at            timestamptz  DEFAULT now(),
  updated_at            timestamptz  DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_campaign_templates_broker_slug
  ON public.campaign_templates (broker_slug);

ALTER TABLE public.campaign_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campaign_templates FORCE  ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "service_role full access" ON public.campaign_templates;
CREATE POLICY "service_role full access"
  ON public.campaign_templates
  FOR ALL TO service_role
  USING (true) WITH CHECK (true);

-- Campaign new/edit pages (app/broker-portal/campaigns/*) INSERT and SELECT
-- templates via browser client. FOR ALL with WITH CHECK ensures brokers can
-- only INSERT/UPDATE rows stamped with their own broker_slug.
DROP POLICY IF EXISTS "broker manages own templates" ON public.campaign_templates;
CREATE POLICY "broker manages own templates"
  ON public.campaign_templates
  FOR ALL TO authenticated
  USING (
    broker_slug IN (
      SELECT ba.broker_slug
      FROM   public.broker_accounts ba
      WHERE  ba.auth_user_id = auth.uid()
    )
  )
  WITH CHECK (
    broker_slug IN (
      SELECT ba.broker_slug
      FROM   public.broker_accounts ba
      WHERE  ba.auth_user_id = auth.uid()
    )
  );

-- ============================================================================
-- 5. allocation_decisions
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.allocation_decisions (
  id               bigint       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  placement_slug   text         NOT NULL,
  candidates       jsonb        NOT NULL DEFAULT '[]',
  winners          jsonb        NOT NULL DEFAULT '[]',
  rejection_log    jsonb        NOT NULL DEFAULT '[]',
  candidate_count  integer      NOT NULL DEFAULT 0,
  winner_count     integer      NOT NULL DEFAULT 0,
  fallback_used    boolean      NOT NULL DEFAULT false,
  device_type      text,
  page             text,
  scenario         text,
  duration_ms      integer,
  created_at       timestamptz  NOT NULL DEFAULT now()
);

-- Note: idx_allocation_decisions_created and idx_allocation_decisions_placement
-- were already created by 20260414_wave_5_perf_indexes.sql — IF NOT EXISTS is
-- idempotent; the statements are no-ops on an existing DB.
CREATE INDEX IF NOT EXISTS idx_allocation_decisions_created
  ON public.allocation_decisions (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_allocation_decisions_placement
  ON public.allocation_decisions (placement_slug, created_at DESC);

ALTER TABLE public.allocation_decisions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.allocation_decisions FORCE  ROW LEVEL SECURITY;

-- Internal allocation engine log: lib/marketplace/allocation.ts (admin client)
-- inserts every decision; app/admin/marketplace/decisions/page.tsx (admin client)
-- reads analytics. No broker-portal or browser-client access path exists.
-- Deny-all-except-service_role matches feature_flags / web_vitals_samples pattern.
DROP POLICY IF EXISTS "service_role full access" ON public.allocation_decisions;
CREATE POLICY "service_role full access"
  ON public.allocation_decisions
  FOR ALL TO service_role
  USING (true) WITH CHECK (true);

COMMIT;
