import type { Metadata } from "next";

import { absoluteUrl, breadcrumbJsonLd, SITE_NAME } from "@/lib/seo";
import WealthStackClient from "./WealthStackClient";
import { faqJsonLd } from "@/lib/schema-markup";

// FIN_NOTEBOOK Revenue #1 (concierge wealth-stack) — the user-facing
// surface. Reads the user's prior quiz answers from sessionStorage if
// available, otherwise prompts the minimal question set inline. Calls
// /api/wealth-stack to get a goal-prioritised multi-product
// recommendation (broker + super + savings + crypto + robo), then
// renders an affiliate-clickable stack with per-component CTAs.
//
// Attribution: each component CTA carries `stackId` + `kind` query
// params so the lead/affiliate pipeline can attribute every click back
// to the same recommendation event. The downstream attribution wiring
// in the leads table is a separate PR.

export const revalidate = 0;

export const metadata: Metadata = {
  title: `Your Wealth Stack — ${SITE_NAME}`,
  description:
    "Get a personalised stack of investing products — broker, super fund, savings account, crypto exchange — matched to your goals in 60 seconds.",
  alternates: { canonical: "/wealth-stack" },
  openGraph: {
    title: `Your Wealth Stack — ${SITE_NAME}`,
    description:
      "Multi-product investing recommendation matched to your goals: broker, super, savings, crypto, robo.",
    url: absoluteUrl("/wealth-stack"),
    images: [
      {
        url: "/api/og?title=Your+Wealth+Stack&subtitle=Broker+%2B+Super+%2B+Savings+%2B+Crypto&type=quiz",
        width: 1200,
        height: 630,
      },
    ],
  },
  twitter: { card: "summary_large_image" },
};

const WEALTH_STACK_FAQS = [
  {
    q: "What is the Wealth Stack recommendation?",
    a: "Your Wealth Stack is a personalised multi-product recommendation that matches your investing goals to a curated set of Australian financial products — typically a share broker, superannuation fund, high-interest savings account, and optionally a crypto exchange or robo-adviser. The recommendation is generated by answering a short set of questions about your goals (wealth building, retirement, income, or preservation), timeline, risk tolerance, and existing accounts. Each product in the stack is selected for how well it fits your stated situation — not on the basis of commercial arrangements alone.",
  },
  {
    q: "How is the Wealth Stack personalised to me?",
    a: "The recommendation engine takes your quiz answers and applies a goal-priority algorithm: for long-term wealth building it weights low-fee brokers and high-growth super options; for retirement-focused goals it weights accumulation super funds and conservative asset mixes; for income goals it weights high-interest savings accounts and dividend-focused brokers. Products are filtered by whether they accept your account type (e.g. SMSF, individual, joint) and whether they match your investment universe (ASX only, international, crypto-enabled). The engine does not take into account your current holdings, tax position, or financial plan — see a licensed adviser for that level of personalisation.",
  },
  {
    q: "Are the products in my Wealth Stack paid placements?",
    a: "Some products in your Wealth Stack may have a commercial relationship with Invest.com.au — we may earn an affiliate fee if you open an account via a link in your stack. Affiliate relationships do not determine which products appear in your stack: a product must independently meet the criteria for your goal profile to be included. Products with affiliate relationships are ranked alongside non-affiliate products. Any affiliate relationship is disclosed on the product detail card. We publish our full fee and affiliate disclosure at /how-we-make-money.",
  },
  {
    q: "Is the Wealth Stack recommendation personal financial advice?",
    a: "No. The Wealth Stack is a general information tool. It does not take into account your complete financial situation, tax obligations, existing debts, insurance needs, estate planning, or specific investment objectives. It is designed to help you identify a sensible starting point — not replace advice from a licensed financial adviser. If you are moving significant capital, transitioning super funds, or making decisions that affect your retirement, obtain advice from an AFSL-holding adviser before acting. Use our adviser finder (/advisors) to find one.",
  },
];

const wealthStackFaqLd = faqJsonLd(WEALTH_STACK_FAQS);

export default function WealthStackPage() {
  const breadcrumbs = breadcrumbJsonLd([
    { name: "Home", url: absoluteUrl("/") },
    { name: "Your Wealth Stack" },
  ]);

  return (
    <>
      <div className="mx-auto max-w-2xl px-4 py-10 md:py-14">
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbs) }}
        />
        {wealthStackFaqLd && (
          <script
            type="application/ld+json"
            dangerouslySetInnerHTML={{ __html: JSON.stringify(wealthStackFaqLd) }}
          />
        )}
        <WealthStackClient />
      </div>

      <div className="border-t border-slate-200 bg-white">
        <div className="container-custom max-w-2xl py-8 md:py-10">
          <h2 className="text-lg font-extrabold text-slate-900 mb-4">Frequently asked questions</h2>
          <div className="space-y-2.5">
            {WEALTH_STACK_FAQS.map((faq) => (
              <details key={faq.q} className="group rounded-xl border border-slate-200 bg-slate-50">
                <summary className="flex cursor-pointer items-center justify-between gap-4 px-4 py-3 font-semibold text-sm text-slate-900 list-none">
                  {faq.q}
                  <span className="shrink-0 text-slate-400 group-open:rotate-180 transition-transform" aria-hidden="true">▾</span>
                </summary>
                <p className="px-4 pb-4 text-sm text-slate-600 leading-relaxed">{faq.a}</p>
              </details>
            ))}
          </div>
        </div>
      </div>
    </>
  );
}
