#!/usr/bin/env node
// @ts-check
/**
 * Account-kind scaffolder (Phase 0.2).
 *
 * Generates the boilerplate for a new account kind so adding kind #9+ is a
 * single command instead of an 8-file manual job, and PRINTS the exact
 * edits to apply to the 5 hand-maintained registry sites. The
 * check-entity-registry.mjs CI gate then enforces those edits landed.
 *
 * Why not auto-edit the registry sites? Editing the TS union + Set + switch
 * statements reliably needs a real AST tool (ts-morph). Rather than add a
 * dev dependency for a once-per-quarter task, this generator produces the
 * net-new files (migration, portal layout, RLS test) — the bulk of the
 * boilerplate — and emits a copy-paste checklist for the 5 one-line
 * registry edits. CI fails if any registry edit is skipped.
 *
 * Usage:
 *   node scripts/add-entity.mjs <kind_name> [--table <table>] [--portal <path>]
 *
 * Example:
 *   node scripts/add-entity.mjs wholesale_operator \
 *     --table wholesale_operators --portal /wholesale-portal
 */

import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "..");

function parseArgs(argv) {
  const args = { _: [] };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a.startsWith("--")) {
      args[a.slice(2)] = argv[++i];
    } else {
      args._.push(a);
    }
  }
  return args;
}

function timestamp() {
  // YYYYMMDDHHMMSS in UTC, matching the migration naming convention.
  const d = new Date();
  const p = (n, w = 2) => String(n).padStart(w, "0");
  return (
    `${d.getUTCFullYear()}${p(d.getUTCMonth() + 1)}${p(d.getUTCDate())}` +
    `${p(d.getUTCHours())}${p(d.getUTCMinutes())}${p(d.getUTCSeconds())}`
  );
}

function migrationSql(kind, table) {
  return `-- ============================================================================
-- Migration: <ts>_${table}.sql
-- Purpose: New '${kind}' account kind. Generated by scripts/add-entity.mjs.
--          Fill in the kind-specific columns before applying.
-- Audit ref: docs/audits/account-architecture-master-plan-2026-05-19.md
-- Risk: low — additive entity table + view branch.
-- Rollback:
--   BEGIN;
--     DROP VIEW IF EXISTS public.account_kind_membership; -- recreate prior
--     DROP TABLE IF EXISTS public.${table};
--   COMMIT;
-- ============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS public.${table} (
  id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  auth_user_id    uuid   NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  principal_id    uuid   REFERENCES public.principals(id) ON DELETE SET NULL,
  display_name    text,
  -- TODO: add kind-specific columns here
  status          text   NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('pending', 'active', 'inactive', 'suspended')),
  deleted_at      timestamptz,
  pii_redacted_at timestamptz,
  metadata        jsonb  NOT NULL DEFAULT '{}'::jsonb,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_${table}_auth_user ON public.${table} (auth_user_id);
CREATE INDEX IF NOT EXISTS idx_${table}_principal_id
  ON public.${table} (principal_id) WHERE principal_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_${table}_deleted_at
  ON public.${table} (deleted_at) WHERE deleted_at IS NOT NULL;

ALTER TABLE public.${table} ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.${table} FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "${kind} reads own profile" ON public.${table};
CREATE POLICY "${kind} reads own profile"
  ON public.${table} FOR SELECT TO authenticated
  USING (auth.uid() = auth_user_id AND deleted_at IS NULL);

DROP POLICY IF EXISTS "${kind} inserts own profile" ON public.${table};
CREATE POLICY "${kind} inserts own profile"
  ON public.${table} FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = auth_user_id);

DROP POLICY IF EXISTS "${kind} updates own profile" ON public.${table};
CREATE POLICY "${kind} updates own profile"
  ON public.${table} FOR UPDATE TO authenticated
  USING (auth.uid() = auth_user_id) WITH CHECK (auth.uid() = auth_user_id);

DROP POLICY IF EXISTS "service_role full access ${table}" ON public.${table};
CREATE POLICY "service_role full access ${table}"
  ON public.${table} FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE TRIGGER ${table}_updated_at
  BEFORE UPDATE ON public.${table}
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

-- TODO: extend account_kind_membership view with a UNION ALL branch:
--   UNION ALL
--   SELECT auth_user_id, '${kind}'::text, id::text, principal_id, status,
--     COALESCE(display_name, '${kind} account'), NULL::text AS scope_slug,
--     created_at
--   FROM public.${table} WHERE auth_user_id IS NOT NULL AND deleted_at IS NULL;

COMMIT;
`;
}

function layoutTsx(kind, portal) {
  return `/**
 * ${portal} — ${kind} workspace shell. Generated by scripts/add-entity.mjs.
 */

import { enforcePortalKind } from "@/lib/portal-gate";

export default async function Layout({ children }: { children: React.ReactNode }) {
  await enforcePortalKind("${kind}");
  return <>{children}</>;
}
`;
}

function rlsTest(kind, table) {
  return `import { describe, it, expect } from "vitest";

/**
 * RLS isolation placeholder for the '${kind}' kind (${table}).
 * Replace with a real cross-user isolation assertion against a seeded
 * staging Supabase project (user A cannot read user B's ${table} row).
 */
describe("${table} RLS isolation", () => {
  it.todo("user A cannot read user B's ${table} row");
  it("registry sanity: kind is wired", async () => {
    const { ACTIVE_ACCOUNT_KINDS } = await import("@/lib/account-types");
    expect(ACTIVE_ACCOUNT_KINDS).toContain("${kind}");
  });
});
`;
}

function registryChecklist(kind, portal) {
  return `
─────────────────────────────────────────────────────────────────────────────
MANUAL REGISTRY EDITS (CI gate scripts/check-entity-registry.mjs enforces these)
─────────────────────────────────────────────────────────────────────────────

1. lib/account-types.ts
   - Add to the AccountKind union:        | "${kind}"
   - Add to ACTIVE_ACCOUNT_KINDS array:    "${kind}",

2. lib/account-kinds.ts
   - Add to KNOWN_WORKSPACE_KINDS set:      "${kind}",
   - Add to portalForKind switch:          case "${kind}": return "${portal}";

3. lib/portal-gate.ts
   - Add to currentPortalPath switch:       case "${kind}": return "${portal}";

4. app/account/select-workspace/SelectWorkspaceClient.tsx
   - Add a KIND_META entry for "${kind}" (label, description, icon, tone)

5. components/WorkspaceSwitcher.tsx
   - Add "${kind}" to KIND_LABEL and KIND_ICON

Then run:  node scripts/check-entity-registry.mjs
`;
}

async function writeFileSafe(absPath, contents) {
  await fs.mkdir(path.dirname(absPath), { recursive: true });
  try {
    await fs.access(absPath);
    console.log(`  • SKIP (exists): ${path.relative(REPO_ROOT, absPath)}`);
    return;
  } catch {
    // doesn't exist — write it
  }
  await fs.writeFile(absPath, contents, "utf8");
  console.log(`  ✓ wrote ${path.relative(REPO_ROOT, absPath)}`);
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const kind = args._[0];
  if (!kind || !/^[a-z][a-z_]*$/.test(kind)) {
    console.error("Usage: node scripts/add-entity.mjs <kind_name> [--table <table>] [--portal <path>]");
    console.error("  <kind_name> must be lower_snake_case.");
    process.exit(1);
  }
  const table = args.table ?? `${kind}s`;
  const portal = args.portal ?? `/${kind.replace(/_/g, "-")}-portal`;
  const ts = timestamp();

  console.log(`Scaffolding account kind '${kind}' (table=${table}, portal=${portal})\n`);

  await writeFileSafe(
    path.join(REPO_ROOT, "supabase/migrations", `${ts}_${table}.sql`),
    migrationSql(kind, table).replace(/<ts>/g, ts),
  );
  await writeFileSafe(
    path.join(REPO_ROOT, "app", portal.replace(/^\//, ""), "layout.tsx"),
    layoutTsx(kind, portal),
  );
  await writeFileSafe(
    path.join(REPO_ROOT, "__tests__/rls", `${table}-isolation.test.ts`),
    rlsTest(kind, table),
  );

  console.log(registryChecklist(kind, portal));
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
