#!/usr/bin/env node
// @ts-check
/**
 * Visual snapshot + layout-shift guard (bot idea #5).
 *
 * Captures full-page screenshots of key routes at desktop + mobile widths (saved
 * as artifacts for human/regression review) and HARD-gates on horizontal
 * overflow — the most common, deterministic responsive break (a page wider than
 * the viewport = horizontal scroll on mobile). A pragmatic visual-regression
 * baseline without the flakiness/repo-bloat of committed pixel diffs.
 *
 *   npm run bots:visual
 *   BOTS_BASE_URL=https://my-preview.vercel.app npm run bots:visual
 *
 * Output: bots/reports/screenshots/<route>-<viewport>.png + bots/reports/visual-<date>.md
 * Exit: 0 no overflow · 1 a route overflows its viewport · 2 no chromium.
 * Cost: $0 — Playwright, no LLM.
 */
import { chromium } from "playwright";
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const BASE = (process.env.BOTS_BASE_URL || "https://lambent-sawine-17c3dd.netlify.app").replace(/\/$/, "");
const today = new Date().toISOString().slice(0, 10);
const shotDir = path.join(process.cwd(), "bots", "reports", "screenshots");
const reportPath = path.join(process.cwd(), "bots", "reports", `visual-${today}.md`);
const ROUTES = ["/", "/compare", "/advisors", "/best/beginners", "/super", "/quiz", "/wholesale", "/wealth-stack"];
const VIEWPORTS = [{ name: "desktop", width: 1280, height: 900, mobile: false }, { name: "mobile", width: 390, height: 844, mobile: true }];

async function main() {
  await fs.mkdir(shotDir, { recursive: true });
  let browser;
  try { browser = await chromium.launch({ args: ["--no-sandbox"] }); }
  catch (e) { console.error("[bots:visual] no chromium — `npm run bots:install`.", e instanceof Error ? e.message : ""); process.exit(2); }

  const rows = [];
  for (const route of ROUTES) {
    for (const vp of VIEWPORTS) {
      process.stdout.write(`[bots:visual] ${route} @${vp.name} … `);
      const ctx = await browser.newContext({ ignoreHTTPSErrors: true, viewport: { width: vp.width, height: vp.height }, isMobile: vp.mobile, deviceScaleFactor: vp.mobile ? 2 : 1 });
      const page = await ctx.newPage();
      let overflow = -1, status = 0;
      try {
        const resp = await page.goto(BASE + route, { waitUntil: "domcontentloaded", timeout: 30_000 });
        status = resp?.status() ?? 0;
        await page.waitForTimeout(1200);
        overflow = await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth);
        const file = path.join(shotDir, `${route.replace(/[^a-z0-9]+/gi, "_").replace(/^_|_$/g, "") || "home"}-${vp.name}.png`);
        await page.screenshot({ path: file, fullPage: true }).catch(() => {});
      } catch { /* record below */ }
      process.stdout.write(`${status} overflow:${overflow}px${overflow > 2 ? " ✗" : " ✓"}\n`);
      rows.push({ route, vp: vp.name, status, overflow });
      await ctx.close();
    }
  }
  await browser.close();

  const broken = rows.filter((r) => r.overflow > 2); // >2px = real horizontal scroll
  const lines = [
    `# Visual + layout guard — ${today}`, "",
    `Target: \`${BASE}\` · screenshots in bots/reports/screenshots/ · $0.`, "",
    broken.length === 0
      ? `## ✅ No horizontal overflow (${rows.length} route×viewport captures).`
      : `## ⚠️ ${broken.length} capture(s) with horizontal overflow.`, "",
    "| Route | Viewport | Status | Overflow (px) |", "|---|---|--:|--:|",
    ...rows.map((r) => `| \`${r.route}\` | ${r.vp} | ${r.status || "ERR"} | ${r.overflow}${r.overflow > 2 ? " ⚠️" : ""} |`),
    "", "---", "_Generated by `npm run bots:visual`._",
  ];
  await fs.writeFile(reportPath, lines.join("\n") + "\n");
  console.log(`\n[bots:visual] Report: ${path.relative(process.cwd(), reportPath)} · screenshots: ${path.relative(process.cwd(), shotDir)}/`);
  console.log(`[bots:visual] ${broken.length === 0 ? "NO OVERFLOW" : broken.length + " overflow"} (${rows.length} captures)`);
  process.exit(broken.length > 0 ? 1 : 0);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main().catch((err) => { console.error("[bots:visual] fatal:", err); process.exit(2); });
}
