#!/usr/bin/env node
// @ts-check
/**
 * Accessibility monitor (bot idea #6).
 *
 * Runs axe-core (WCAG 2.1 A/AA) against key route templates in a real browser.
 * CRITICAL violations fail the gate; SERIOUS are reported as warnings (e.g.
 * colour-contrast is serious and often needs design sign-off, so it shouldn't
 * block CI on its own). Same tag/disabled-rule set as the project's e2e a11y
 * gate. Formalises the one-off axe sweep into a recurring guard.
 *
 *   npm run bots:a11y
 *   BOTS_BASE_URL=https://my-preview.vercel.app npm run bots:a11y
 *
 * Output: bots/reports/a11y-YYYY-MM-DD.md + console summary.
 * Exit: 0 no critical · 1 a critical violation · 2 couldn't run (no chromium).
 * Cost: $0 — Playwright + axe, no LLM. Needs `npm run bots:install` once.
 */
import { chromium } from "playwright";
import AxeBuilder from "@axe-core/playwright";
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const BASE = (process.env.BOTS_BASE_URL || "https://lambent-sawine-17c3dd.netlify.app").replace(/\/$/, "");
const today = new Date().toISOString().slice(0, 10);
const reportPath = path.join(process.cwd(), "bots", "reports", `a11y-${today}.md`);
const DISABLED_RULES = ["region"]; // fires on route-transition placeholders users can't reach
const ROUTES = ["/", "/compare", "/advisors", "/best/beginners", "/super", "/crypto", "/quiz", "/wholesale"];

async function main() {
  await fs.mkdir(path.dirname(reportPath), { recursive: true });
  let browser;
  try {
    browser = await chromium.launch({ args: ["--no-sandbox"] });
  } catch (e) {
    console.error("[bots:a11y] could not launch chromium — run `npm run bots:install`.", e instanceof Error ? e.message : "");
    process.exit(2);
  }

  const rows = [];
  for (const route of ROUTES) {
    process.stdout.write(`[bots:a11y] ${route} … `);
    let critical = 0, serious = 0, ids = [];
    for (let i = 0; i < 2; i++) {
      const ctx = await browser.newContext({ ignoreHTTPSErrors: true });
      const page = await ctx.newPage();
      try {
        await page.goto(BASE + route, { waitUntil: "domcontentloaded", timeout: 30_000 });
        await page.waitForTimeout(1200);
        const res = await new AxeBuilder({ page })
          .withTags(["wcag2a", "wcag2aa", "wcag21a", "wcag21aa"])
          .disableRules(DISABLED_RULES)
          .analyze();
        critical = res.violations.filter((v) => v.impact === "critical").reduce((n, v) => n + v.nodes.length, 0);
        serious = res.violations.filter((v) => v.impact === "serious").reduce((n, v) => n + v.nodes.length, 0);
        ids = res.violations.filter((v) => v.impact === "critical" || v.impact === "serious").map((v) => `${v.id}×${v.nodes.length}`);
        await ctx.close();
        break;
      } catch { await ctx.close(); }
    }
    process.stdout.write(`crit:${critical} serious:${serious}\n`);
    rows.push({ route, critical, serious, ids });
  }
  await browser.close();

  const withCritical = rows.filter((r) => r.critical > 0);
  const lines = [
    `# Accessibility (axe WCAG 2.1 AA) — ${today}`, "",
    `Target: \`${BASE}\` · critical fails the gate, serious = warning · $0.`, "",
    withCritical.length === 0
      ? `## ✅ No critical a11y violations (${rows.length} routes).`
      : `## 🔴 ${withCritical.length} route(s) with critical a11y violations.`, "",
    "| Route | Critical | Serious | Top rules |", "|---|--:|--:|---|",
    ...rows.map((r) => `| \`${r.route}\` | ${r.critical} | ${r.serious} | ${r.ids.slice(0, 4).join(", ")} |`),
    "", "---", "_Generated by `npm run bots:a11y`._",
  ];
  await fs.writeFile(reportPath, lines.join("\n") + "\n");
  console.log(`\n[bots:a11y] Report: ${path.relative(process.cwd(), reportPath)}`);
  const totalSerious = rows.reduce((n, r) => n + r.serious, 0);
  console.log(`[bots:a11y] ${withCritical.length === 0 ? "no critical" : withCritical.length + " route(s) critical"} · ${totalSerious} serious (warn)`);
  process.exit(withCritical.length > 0 ? 1 : 0);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main().catch((err) => { console.error("[bots:a11y] fatal:", err); process.exit(2); });
}
