import { createClient } from "@supabase/supabase-js";
import { NextRequest, NextResponse } from "next/server";

export const runtime = "edge";

/**
 * Generates a structured HTML fee report that can be saved as PDF.
 * Requires email capture first (verified via email_captures table).
 * Returns HTML formatted for print/PDF — users can Cmd+P to save.
 */
export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const token = searchParams.get("token"); // email hash as simple verification

  const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  );

  // Fetch all active brokers
  const { data: brokers } = await supabase
    .from("brokers")
    .select("name, slug, platform_type, asx_fee, us_fee, fx_rate, inactivity_fee, chess_sponsored, smsf_support, rating, min_deposit")
    .eq("status", "active")
    .order("rating", { ascending: false });

  if (!brokers || brokers.length === 0) {
    return NextResponse.json({ error: "No data" }, { status: 500 });
  }

  const now = new Date();
  const dateStr = now.toLocaleDateString("en-AU", { day: "numeric", month: "long", year: "numeric" });

  const platformTypes: Record<string, string> = {
    share_broker: "Share Brokers",
    crypto_exchange: "Crypto Exchanges",
    robo_advisor: "Robo-Advisors",
    super_fund: "Super Funds",
    cfd_forex: "CFD/Forex Brokers",
    research_tool: "Research Tools",
    property_platform: "Property Platforms",
  };

  const grouped = Object.entries(platformTypes).map(([type, label]) => ({
    type, label,
    brokers: brokers.filter(b => b.platform_type === type),
  })).filter(g => g.brokers.length > 0);

  const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Australian Broker Fee Comparison ${now.getFullYear()} — Invest.com.au</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: Arial, sans-serif; color: #333; max-width: 800px; margin: 0 auto; padding: 40px 30px; }
  h1 { font-size: 24px; color: #0f172a; margin-bottom: 4px; }
  h2 { font-size: 16px; color: #0f172a; margin: 24px 0 8px; border-bottom: 2px solid #0f172a; padding-bottom: 4px; }
  .subtitle { font-size: 12px; color: #64748b; margin-bottom: 20px; }
  .date { font-size: 11px; color: #94a3b8; }
  table { width: 100%; border-collapse: collapse; margin: 8px 0 16px; font-size: 11px; }
  th { background: #0f172a; color: white; padding: 6px 8px; text-align: left; font-weight: bold; }
  td { padding: 5px 8px; border-bottom: 1px solid #e2e8f0; }
  tr:nth-child(even) { background: #f8fafc; }
  .chess { color: #059669; font-weight: bold; }
  .no-chess { color: #dc2626; }
  .footer { margin-top: 30px; padding-top: 12px; border-top: 1px solid #e2e8f0; font-size: 9px; color: #94a3b8; }
  .cta { background: #0f172a; color: white; padding: 12px 20px; border-radius: 8px; text-align: center; margin: 20px 0; }
  .cta a { color: #fbbf24; text-decoration: none; font-weight: bold; }
  @media print { .no-print { display: none; } body { padding: 20px; } }
</style></head><body>
<h1>Australian Broker Fee Comparison ${now.getFullYear()}</h1>
<p class="subtitle">Complete fee data for ${brokers.length} platforms — updated ${dateStr}</p>
<p class="date">Generated by Invest.com.au · Data verified from official broker pricing pages</p>

${grouped.map(g => `
<h2>${g.label} (${g.brokers.length})</h2>
<table>
<tr><th>Platform</th><th>Rating</th><th>${g.type === "share_broker" ? "ASX Fee" : g.type === "crypto_exchange" ? "Trading Fee" : "Fee"}</th>${g.type === "share_broker" ? "<th>US Fee</th><th>FX Rate</th><th>CHESS</th><th>SMSF</th>" : ""}<th>Inactivity</th></tr>
${g.brokers.map(b => `<tr>
<td><strong>${b.name}</strong></td>
<td>${b.rating || "N/A"}/5</td>
<td>${b.asx_fee || "N/A"}</td>
${g.type === "share_broker" ? `<td>${b.us_fee || "N/A"}</td><td>${b.fx_rate != null ? b.fx_rate + "%" : "N/A"}</td><td class="${b.chess_sponsored ? "chess" : "no-chess"}">${b.chess_sponsored ? "Yes" : "No"}</td><td>${b.smsf_support ? "Yes" : "No"}</td>` : ""}
<td>${b.inactivity_fee || "None"}</td>
</tr>`).join("")}
</table>
`).join("")}

<div class="cta no-print">
  <p>Compare these brokers interactively at <a href="https://invest.com.au/compare">invest.com.au/compare</a></p>
  <p style="font-size: 11px; margin-top: 4px; color: #94a3b8;">Use our Portfolio Calculator to see your exact annual cost → <a href="https://invest.com.au/portfolio-calculator">invest.com.au/portfolio-calculator</a></p>
</div>

<div class="footer">
  <p><strong>Disclaimer:</strong> This report contains general information only and does not constitute personal financial advice. Fee data is sourced from official broker pricing pages and may change without notice. Always verify current fees directly with the broker before making a decision. Consider reading the relevant PDS and TMD.</p>
  <p style="margin-top: 6px;">© ${now.getFullYear()} Invest.com.au — Generated ${dateStr}. Data may not be reproduced without permission.</p>
</div>
</body></html>`;

  return new NextResponse(html, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Cache-Control": "public, max-age=86400",
    },
  });
}
