-- Migration: engagement_registry — the post-match relationship loop.
--
-- Today the outcome flywheel asks ONCE (~28 days after accept) and then
-- the relationship goes dark. This registry tracks each accepted brief's
-- consumer↔provider relationship and drives scheduled check-ins at 30 /
-- 90 / 365 days (the 365-day touch is the "annual adviser review"), all
-- via a one-time token link — the same email-as-key model as the brief
-- tracker and /outcome/[token].
--
-- Cadence state machine (lib/briefs/engagements.ts):
--   checkin_stage   = number of check-ins already sent (0..3)
--   next_checkin_at = started_at + {30,90,365}d for the next stage;
--                     null once all sent or the relationship ended
--   status 'ended' / 'completed' stops scheduling; the annual review
--   stamps annual_* and, when the consumer is considering a change,
--   the UI offers a pre-filled anonymised re-brief (general info only —
--   we never tell anyone to switch).
--
-- RLS: ops-only service_role policy (token is the auth factor on the
-- consumer surface; /account/advisers matches on the signed-in email
-- server-side).
--
-- Rollback:
--   DROP TABLE IF EXISTS public.engagement_registry;

BEGIN;

CREATE TABLE IF NOT EXISTS public.engagement_registry (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brief_id integer NOT NULL UNIQUE,
  professional_id integer REFERENCES public.professionals(id) ON DELETE SET NULL,
  team_id integer,
  consumer_email text NOT NULL,
  status text NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'engaged', 'completed', 'ended')),
  started_at timestamptz NOT NULL,
  checkin_token text NOT NULL UNIQUE,
  checkin_stage integer NOT NULL DEFAULT 0 CHECK (checkin_stage >= 0 AND checkin_stage <= 3),
  next_checkin_at timestamptz,
  last_checkin_sent_at timestamptz,
  last_status_update_at timestamptz,
  -- Annual review (stage-3 touch) answers.
  annual_rating integer CHECK (annual_rating IS NULL OR (annual_rating >= 1 AND annual_rating <= 5)),
  annual_fee_band text,
  considering_change boolean,
  annual_review_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_engagement_registry_due
  ON public.engagement_registry (next_checkin_at)
  WHERE next_checkin_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_engagement_registry_email
  ON public.engagement_registry (consumer_email);
CREATE INDEX IF NOT EXISTS idx_engagement_registry_professional
  ON public.engagement_registry (professional_id);

ALTER TABLE public.engagement_registry ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Service role manages engagement_registry" ON public.engagement_registry;
CREATE POLICY "Service role manages engagement_registry"
  ON public.engagement_registry FOR ALL TO service_role USING (true) WITH CHECK (true);

COMMIT;
