-- Wave 6 schema.
--
-- Tables introduced:
--   1. form_events              — per-step form funnel beacon
--   2. search_embeddings        — pgvector embeddings for semantic search
--                                 across articles, brokers, advisors, Q&A
--   3. review_sentiment_facets  — structured sentiment per review
--                                 (service, fees, platform, speed)
--   4. job_queue                — DLQ-backed async task queue
--
-- Existing tables extended:
--   - quiz_leads                 → vertical inference
--   - articles / brokers         → last_reviewed_at pass-through
--
-- Every table is RLS-enabled and service-role-only.

-- ── pgvector extension ─────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS vector;

-- ── 1. form_events ─────────────────────────────────────────────────
-- One row per meaningful step in a multi-step form. Used to compute
-- funnel drop-off in /admin/marketplace/funnel.
--
-- The session_id matches attribution_touches.session_id so we can
-- join attribution + form funnel for source-of-truth analysis.
CREATE TABLE IF NOT EXISTS public.form_events (
  id              bigserial PRIMARY KEY,
  session_id      text NOT NULL,
  user_key        text,                 -- email or user_id once known
  form_name       text NOT NULL,        -- 'quiz' | 'advisor_enquiry' | 'advisor_signup' | 'broker_apply' | 'lead_form'
  step            text NOT NULL,        -- 'start' | 'q1' | 'q2' | ... | 'submit' | 'complete'
  step_index      integer,              -- ordinal
  event           text NOT NULL,        -- 'view' | 'interact' | 'complete' | 'abandon'
  meta            jsonb,                -- freeform per-form
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_form_events_session
  ON public.form_events (session_id, created_at);
CREATE INDEX IF NOT EXISTS idx_form_events_form_created
  ON public.form_events (form_name, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_form_events_step_event
  ON public.form_events (form_name, step, event);

ALTER TABLE public.form_events ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.form_events
  DROP CONSTRAINT IF EXISTS form_events_event_check;
ALTER TABLE public.form_events
  ADD CONSTRAINT form_events_event_check CHECK (
    event = ANY (ARRAY['view'::text, 'interact'::text, 'complete'::text, 'abandon'::text])
  );

COMMENT ON TABLE public.form_events IS
  'Per-step form funnel beacon. Join with attribution_touches on session_id for source-of-truth funnel analytics.';

-- ── 2. search_embeddings ───────────────────────────────────────────
-- One row per embedded document. document_type + document_id is
-- the natural key. embedding is a pgvector column; hnsw or ivfflat
-- index enables fast cosine-similarity search.
--
-- Embeddings are generated by a cron (`embeddings-refresh`) that
-- calls Claude / OpenAI and upserts when a source row's updated_at
-- advances past last_embedded_at.
CREATE TABLE IF NOT EXISTS public.search_embeddings (
  id              bigserial PRIMARY KEY,
  document_type   text NOT NULL,        -- 'article' | 'broker' | 'advisor' | 'qa' | 'scenario'
  document_id     text NOT NULL,        -- stringified natural id (slug or integer id)
  title           text,
  body_excerpt    text,
  embedding       vector(1536),         -- OpenAI text-embedding-3-small shape; Claude voyage-3 is also 1536
  model           text NOT NULL,        -- 'openai-text-embedding-3-small' | 'voyage-3'
  source_updated_at timestamptz,
  embedded_at     timestamptz NOT NULL DEFAULT now(),
  UNIQUE (document_type, document_id)
);

-- IVFFlat index for approximate cosine similarity. 100 lists is
-- plenty for <100k rows; grow later if needed.
CREATE INDEX IF NOT EXISTS idx_search_embeddings_cosine
  ON public.search_embeddings
  USING ivfflat (embedding vector_cosine_ops)
  WITH (lists = 100);

CREATE INDEX IF NOT EXISTS idx_search_embeddings_type
  ON public.search_embeddings (document_type);

ALTER TABLE public.search_embeddings ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.search_embeddings IS
  'pgvector embeddings for semantic search across articles/brokers/advisors/qa. Refreshed by the embeddings cron.';

-- ── 3. review_sentiment_facets ─────────────────────────────────────
-- Structured sentiment breakdown per review row. A nightly cron
-- reads new user_reviews/professional_reviews rows and asks Claude
-- for per-facet scores. Null facets mean "not addressed in the
-- review" — distinct from 0 ("explicitly bad").
CREATE TABLE IF NOT EXISTS public.review_sentiment_facets (
  id                bigserial PRIMARY KEY,
  review_type       text NOT NULL,      -- 'user_review' | 'professional_review'
  review_id         integer NOT NULL,
  customer_service  integer,            -- 0-100
  fees_value        integer,
  platform_ux       integer,
  speed_reliability  integer,
  trust_accuracy    integer,
  overall_tone      text,               -- 'positive' | 'neutral' | 'negative' | 'mixed'
  summary           text,               -- 1-2 sentence distilled takeaway
  provider          text NOT NULL,      -- 'claude' | 'openai' | 'stub'
  model             text,
  scored_at         timestamptz NOT NULL DEFAULT now(),
  UNIQUE (review_type, review_id)
);

CREATE INDEX IF NOT EXISTS idx_review_sentiment_type_id
  ON public.review_sentiment_facets (review_type, review_id);

ALTER TABLE public.review_sentiment_facets ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.review_sentiment_facets
  DROP CONSTRAINT IF EXISTS review_sentiment_tone_check;
ALTER TABLE public.review_sentiment_facets
  ADD CONSTRAINT review_sentiment_tone_check CHECK (
    overall_tone IS NULL OR overall_tone = ANY (ARRAY['positive'::text, 'neutral'::text, 'negative'::text, 'mixed'::text])
  );

-- ── 4. job_queue ───────────────────────────────────────────────────
-- DLQ-backed async task queue. Unlike crons (fire on schedule), jobs
-- represent one-off work ("send welcome email to user X in 6
-- hours"). A worker cron processes `ready` jobs, marks them
-- `running`, then `done` or `error`. Rows with error after max
-- attempts become `dead_letter` for manual triage.
CREATE TABLE IF NOT EXISTS public.job_queue (
  id              bigserial PRIMARY KEY,
  job_type        text NOT NULL,        -- 'send_email' | 'regenerate_embedding' | 'recompute_advisor_score' | ...
  payload         jsonb NOT NULL,
  status          text NOT NULL DEFAULT 'ready',
  attempts        integer NOT NULL DEFAULT 0,
  max_attempts    integer NOT NULL DEFAULT 5,
  last_error      text,
  scheduled_at    timestamptz NOT NULL DEFAULT now(),
  started_at      timestamptz,
  completed_at    timestamptz,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_job_queue_ready
  ON public.job_queue (status, scheduled_at)
  WHERE status = 'ready';
CREATE INDEX IF NOT EXISTS idx_job_queue_type_status
  ON public.job_queue (job_type, status);

ALTER TABLE public.job_queue ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.job_queue
  DROP CONSTRAINT IF EXISTS job_queue_status_check;
ALTER TABLE public.job_queue
  ADD CONSTRAINT job_queue_status_check CHECK (
    status = ANY (ARRAY['ready'::text, 'running'::text, 'done'::text, 'error'::text, 'dead_letter'::text])
  );

-- ── 5. quiz_leads.inferred_vertical ────────────────────────────────
-- The quiz routing engine writes the computed vertical here so we
-- can redirect the user correctly AND compare "stated" vs
-- "revealed" intent later.
ALTER TABLE IF EXISTS public.quiz_leads
  ADD COLUMN IF NOT EXISTS inferred_vertical text,
  ADD COLUMN IF NOT EXISTS inferred_confidence numeric;

-- ── 6. articles.last_reviewed_at ───────────────────────────────────
-- Trust + SEO freshness signal rendered on the article header.
-- Distinct from updated_at (which fires on every db save) — this
-- tracks "human editorial review completed".
ALTER TABLE IF EXISTS public.articles
  ADD COLUMN IF NOT EXISTS last_reviewed_at timestamptz,
  ADD COLUMN IF NOT EXISTS last_reviewed_by text;

-- ── 7. email_captures.session_id ───────────────────────────────────
-- Links an email capture to a browser session so the abandoned-form
-- drip can find the right email for a given session. Also gives us
-- a single-dose recovery flag.
ALTER TABLE IF EXISTS public.email_captures
  ADD COLUMN IF NOT EXISTS session_id text,
  ADD COLUMN IF NOT EXISTS recovery_sent_at timestamptz;
CREATE INDEX IF NOT EXISTS idx_email_captures_session
  ON public.email_captures (session_id)
  WHERE session_id IS NOT NULL;
