-- Migration: advisor_winback_sends — dedupe ledger for the advisor
-- win-back cron (/api/cron/advisor-winback).
--
-- FIN_NOTEBOOK 2026-06-10 ("advisor monetization only lacks cap-hit
-- upsell + churn win-back"). The cron emails advisors whose paid tier
-- lapsed back to free (professionals.advisor_tier = 'free' with
-- tier_changed_at stamped by the downgrade/cancellation flows) ONE
-- factual win-back email. This table is the send log: the cron skips
-- any advisor with a row in the last 60 days, and the row snapshots
-- the factual claims that were made (profile views / cohort enquiry
-- counts) for auditability.
--
-- Modelled on public.pro_digest_sends (the existing advisor email
-- dedupe table). Ops-only data — RLS enabled with a service_role-only
-- policy, no anon/authenticated access (matches the "Operational"
-- table class in ARCHITECTURE.md).
--
-- Rollback:
--   DROP TABLE IF EXISTS public.advisor_winback_sends;

BEGIN;

CREATE TABLE IF NOT EXISTS public.advisor_winback_sends (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  professional_id integer NOT NULL REFERENCES public.professionals(id) ON DELETE CASCADE,
  sent_at timestamptz NOT NULL DEFAULT now(),
  -- professionals.tier_change_reason at send time (e.g.
  -- 'deferred_downgrade_cycle_end'), kept for audit.
  tier_change_reason text,
  -- Snapshot of the factual claims included in the email.
  profile_views_30d integer NOT NULL DEFAULT 0,
  cohort_enquiries_30d integer NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_advisor_winback_sends_professional
  ON public.advisor_winback_sends (professional_id, sent_at DESC);

ALTER TABLE public.advisor_winback_sends ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Service role manages advisor_winback_sends" ON public.advisor_winback_sends;
CREATE POLICY "Service role manages advisor_winback_sends"
  ON public.advisor_winback_sends FOR ALL TO service_role USING (true) WITH CHECK (true);

COMMIT;
