-- Migration: brief_sla_events — the Response Guarantee ledger for the
-- brief marketplace.
--
-- When a provider accepts a brief and sends no first message within the
-- SLA window (24h), the sweep cron (/api/cron/brief-sla-sweep) refunds
-- the accept credits, releases the brief back to the open pool and
-- re-broadcasts it to other eligible providers. This table records every
-- warning and clawback so:
--   - the sweep is idempotent (one warning + one clawback max per
--     brief/provider pair),
--   - per-provider strike counts can be derived (no counter column on
--     professionals; derive with COUNT(*) over a rolling window),
--   - admin/automation dashboards can audit what the guarantee did.
--
-- Execution is gated by the `response_guarantee` feature flag (absent /
-- disabled by default → sweep is a no-op until founder enables it).
--
-- RLS: ops-only service_role policy (matches advisor_winback_sends /
-- advisor_standing_order_runs). Consumers see the effect via their brief
-- tracker + notification inbox, not by reading this table.
--
-- Rollback:
--   DROP TABLE IF EXISTS public.brief_sla_events;

BEGIN;

CREATE TABLE IF NOT EXISTS public.brief_sla_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brief_id integer NOT NULL,
  professional_id integer REFERENCES public.professionals(id) ON DELETE SET NULL,
  team_id integer,
  event_type text NOT NULL CHECK (event_type IN ('warning', 'clawback')),
  -- Credits returned to the provider on clawback (0 for warnings and for
  -- success_only-tier accepts, which were never charged at accept time).
  credits_refunded integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_brief_sla_events_brief
  ON public.brief_sla_events (brief_id, event_type);
CREATE INDEX IF NOT EXISTS idx_brief_sla_events_professional
  ON public.brief_sla_events (professional_id, event_type, created_at DESC);

ALTER TABLE public.brief_sla_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Service role manages brief_sla_events" ON public.brief_sla_events;
CREATE POLICY "Service role manages brief_sla_events"
  ON public.brief_sla_events FOR ALL TO service_role USING (true) WITH CHECK (true);

COMMIT;
