-- Migration: glossary terms to DB
-- ============================================================
-- Moves the glossary from lib/glossary.ts (static) into
-- public.glossary_terms so content can be edited without a code
-- deploy. Seeds the table with 200+ existing + new terms across
-- SMSF, Mining, Foreign Investment, Super, Tax, Property, Crypto,
-- CFD, Regulatory, and General Finance categories.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.glossary_terms (
  id          SERIAL PRIMARY KEY,
  slug        TEXT NOT NULL UNIQUE,
  term        TEXT NOT NULL,
  definition  TEXT NOT NULL,
  category    TEXT,
  sort_order  INTEGER DEFAULT 0,
  status      TEXT NOT NULL DEFAULT 'published',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_glossary_terms_category
  ON public.glossary_terms (category) WHERE status = 'published';
CREATE INDEX IF NOT EXISTS idx_glossary_terms_term_lower
  ON public.glossary_terms ((LOWER(term))) WHERE status = 'published';

ALTER TABLE public.glossary_terms ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public read published glossary" ON public.glossary_terms;
CREATE POLICY "public read published glossary" ON public.glossary_terms
  FOR SELECT USING (status = 'published');

-- Seed data — ON CONFLICT skips rows already present so re-running
-- this migration is idempotent.

INSERT INTO public.glossary_terms (slug, term, definition, category) VALUES
  ('asx', 'ASX', 'Australian Securities Exchange — Australia''s primary stock exchange where shares, ETFs, and other securities are traded.', 'General'),
  ('asx-fee', 'ASX Fee', 'The fee your broker charges each time you buy or sell Australian shares (listed on the ASX).', 'Fees'),
  ('us-fee', 'US Fee', 'The fee to buy or sell US shares — like Apple, Tesla, or US ETFs.', 'Fees'),
  ('fx-rate', 'FX Rate', 'The currency conversion markup when you buy shares in a foreign currency (e.g. USD). Lower is better.', 'Fees'),
  ('brokerage', 'Brokerage', 'The fee you pay your broker for executing a buy or sell trade.', 'Fees'),
  ('management-fee', 'Management Fee', 'An ongoing annual fee charged by a fund, ETF, or robo-advisor for managing your money. Usually shown as a percentage (e.g. 0.50% p.a.).', 'Fees'),
  ('spread', 'Spread', 'The difference between the buy and sell price of an asset. A tighter spread means lower trading cost.', 'Fees'),
  ('chess', 'CHESS', 'A system where shares are registered directly in your name on the ASX register — not held by your broker. Safer if the broker goes bust.', 'Share Trading'),
  ('custodial', 'Custodial', 'A model where your broker holds shares on your behalf (in their name). You still own them, but they aren''t registered directly to you on the ASX.', 'Share Trading'),
  ('etf', 'ETF', 'Exchange-Traded Fund — a basket of investments (shares, bonds, etc.) that trades on the ASX like a single share. A simple way to diversify.', 'General'),
  ('index-fund', 'Index Fund', 'A fund that tracks a market index (like the ASX 200 or S&P 500) by holding the same stocks in the same proportions.', 'General'),
  ('dividend', 'Dividend', 'A payment made by a company to its shareholders, usually from profits. Paid quarterly or semi-annually in Australia.', 'General'),
  ('drp', 'DRP', 'Dividend Reinvestment Plan — instead of receiving cash dividends, you automatically receive more shares in the company.', 'General'),
  ('market-order', 'Market Order', 'An order to buy or sell immediately at the best available price. Fast, but you don''t control the exact price.', 'Share Trading'),
  ('limit-order', 'Limit Order', 'An order to buy or sell only at a specific price (or better). You control the price, but the trade may not happen if the price isn''t reached.', 'Share Trading'),
  ('cgt', 'CGT', 'Capital Gains Tax — tax you pay on the profit when you sell shares for more than you paid.', 'Tax'),
  ('franking-credits', 'Franking Credits', 'Tax credits attached to dividends from Australian companies that have already paid company tax — they can reduce your tax bill.', 'Tax'),
  ('tax-loss-harvesting', 'Tax-Loss Harvesting', 'Selling investments at a loss to offset capital gains and reduce your tax bill. The loss can be carried forward to future years.', 'Tax'),
  ('negative-gearing', 'Negative Gearing', 'When the costs of an investment property (interest, maintenance) exceed the rental income. The loss can be deducted from your taxable income.', 'Tax'),
  ('asic', 'ASIC', 'Australian Securities & Investments Commission — Australia''s financial regulator that oversees brokers, fund managers, and financial advisers.', 'Regulatory'),
  ('asic-regulated', 'ASIC-regulated', 'ASIC (Australian Securities & Investments Commission) is Australia''s financial regulator. All brokers on this site hold an Australian Financial Services Licence.', 'Regulatory'),
  ('afsl', 'AFSL', 'Australian Financial Services Licence — a licence issued by ASIC that allows a company to provide financial services in Australia.', 'Regulatory'),
  ('afca', 'AFCA', 'Australian Financial Complaints Authority — a free, independent dispute resolution service. If your broker doesn''t resolve a complaint, AFCA can help.', 'Regulatory'),
  ('austrac', 'AUSTRAC', 'Australian Transaction Reports and Analysis Centre — regulates crypto exchanges and monitors financial transactions for anti-money laundering compliance.', 'Regulatory'),
  ('pds', 'PDS', 'Product Disclosure Statement — a legal document from the broker that explains a financial product''s features, fees, and risks.', 'Regulatory'),
  ('tmd', 'TMD', 'Target Market Determination — a document that describes who a financial product is designed for.', 'Regulatory'),
  ('smsf', 'SMSF', 'Self-Managed Super Fund — a way to manage your own retirement savings and invest directly in shares, ETFs, and more.', 'Super'),
  ('superannuation', 'Superannuation', 'Australia''s compulsory retirement savings system. Your employer contributes a percentage of your salary (currently 11.5%) into a super fund.', 'Super'),
  ('concessional-contributions', 'Concessional Contributions', 'Super contributions taxed at 15% (instead of your marginal rate). Includes employer contributions and salary sacrifice. Capped at $30,000/year.', 'Super'),
  ('salary-sacrifice', 'Salary Sacrifice', 'Redirecting part of your pre-tax salary into super. You pay 15% contributions tax instead of your marginal rate, saving tax.', 'Super'),
  ('blockchain', 'Blockchain', 'A decentralised digital ledger that records all transactions across a network. The technology behind Bitcoin, Ethereum, and other cryptocurrencies.', 'Crypto'),
  ('wallet', 'Wallet', 'Software or hardware that stores your cryptocurrency private keys. Needed to send, receive, and manage crypto outside of an exchange.', 'Crypto'),
  ('staking', 'Staking', 'Locking up crypto to support a blockchain network and earn rewards — similar to earning interest. Available on proof-of-stake coins like Ethereum.', 'Crypto'),
  ('defi', 'DeFi', 'Decentralised Finance — financial services (lending, borrowing, trading) built on blockchain without traditional banks or intermediaries.', 'Crypto'),
  ('altcoin', 'Altcoin', 'Any cryptocurrency that isn''t Bitcoin. Includes Ethereum, Solana, Cardano, and thousands of others. Generally higher risk and more volatile.', 'Crypto'),
  ('cold-storage', 'Cold Storage', 'Keeping your cryptocurrency offline (on a hardware wallet like Ledger) where hackers can''t reach it. The safest way to store large crypto holdings.', 'Crypto'),
  ('diversification', 'Diversification', 'Spreading your investments across different assets, sectors, or countries to reduce risk. ''Don''t put all your eggs in one basket.''', 'General'),
  ('compound-interest', 'Compound Interest', 'Earning returns on your returns. e.g. $10,000 at 8% p.a. grows to $21,589 in 10 years because each year''s gains also earn returns.', 'General'),
  ('pe-ratio', 'P/E Ratio', 'Price-to-Earnings ratio — a company''s share price divided by its earnings per share. A quick way to gauge if a share is cheap or expensive relative to its profits.', 'General'),
  ('mysuper', 'MySuper', 'A simple, low-cost default super option that every fund must offer. If you don''t choose a specific investment option, your money goes into MySuper.', 'Super'),
  ('apra', 'APRA', 'Australian Prudential Regulation Authority — the regulator that supervises super funds, banks, and insurance companies to ensure they''re financially sound.', 'Regulatory'),
  ('preservation-age', 'Preservation Age', 'The age you can access your super — between 55 and 60 depending on when you were born. Born after 1 July 1964? Your preservation age is 60.', 'Super'),
  ('cfd', 'CFD', 'Contract for Difference — a leveraged product that lets you speculate on price movements without owning the asset. High risk — most retail accounts lose money.', 'CFD & Forex'),
  ('leverage', 'Leverage', 'Borrowing money from your broker to trade a larger position. Magnifies both profits and losses. e.g. 30:1 leverage means $1 controls $30.', 'CFD & Forex'),
  ('margin', 'Margin', 'The deposit required to open a leveraged position. If your losses exceed your margin, you may face a margin call and forced liquidation.', 'CFD & Forex'),
  ('pip', 'Pip', 'The smallest price increment in forex trading. For most currency pairs, 1 pip = 0.0001 (e.g. AUD/USD moving from 0.6500 to 0.6501).', 'CFD & Forex'),
  ('stop-loss', 'Stop-Loss', 'An order that automatically closes your position if the price moves against you by a set amount. Limits potential losses.', 'CFD & Forex'),
  ('overnight-financing', 'Overnight Financing', 'A fee charged for holding a leveraged CFD position overnight. Also called a swap rate. Costs add up if you hold positions for days or weeks.', 'CFD & Forex'),
  ('short-selling', 'Short Selling', 'Selling an asset you don''t own (borrowing it first) to profit from a price drop. You buy it back later at a lower price. Very risky if the price rises instead.', 'CFD & Forex'),
  ('robo-advisor', 'Robo-Advisor', 'An automated investing service that builds and manages a diversified portfolio for you based on your goals and risk tolerance. Low fees, hands-off.', 'Robo-Advisors')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.glossary_terms (slug, term, definition, category) VALUES
  ('risk-tolerance', 'Risk Tolerance', 'How much investment volatility (ups and downs) you''re comfortable with. Robo-advisors use this to choose your portfolio mix.', 'Robo-Advisors'),
  ('rebalancing', 'Rebalancing', 'Adjusting your portfolio back to its target mix (e.g. 60% shares, 40% bonds) when market movements cause it to drift. Robo-advisors do this automatically.', 'Robo-Advisors'),
  ('micro-investing', 'Micro-Investing', 'Investing tiny amounts (often spare change from round-ups) into a diversified portfolio. Apps like Raiz and Spaceship make this automatic.', 'Robo-Advisors'),
  ('socially-responsible-investing', 'Socially Responsible Investing', 'Investing in companies that meet environmental, social, and governance (ESG) criteria — avoiding fossil fuels, weapons, or tobacco. Most robo-advisors offer an SRI portfolio option.', 'Robo-Advisors'),
  ('fundamental-analysis', 'Fundamental Analysis', 'Evaluating a company''s financial health (revenue, earnings, debt) to determine if its share price is fair value. Used by tools like Simply Wall St and Stock Doctor.', 'Share Trading'),
  ('technical-analysis', 'Technical Analysis', 'Using charts, price patterns, and indicators (RSI, MACD, moving averages) to predict future price movements. Used heavily in platforms like TradingView.', 'Share Trading'),
  ('stock-screener', 'Stock Screener', 'A tool that filters shares based on criteria you set (e.g. P/E ratio under 15, dividend yield over 4%). Helps find investment opportunities quickly.', 'Share Trading'),
  ('reit', 'REIT', 'Real Estate Investment Trust — a company that owns and operates income-producing property. Trades on the ASX like a share, letting you invest in property without buying a house.', 'Property'),
  ('fractional-property', 'Fractional Property', 'Investing in a portion of a property (e.g. $100 worth) through platforms like BrickX. Lower entry cost than buying a whole property.', 'Property'),
  ('rental-yield', 'Rental Yield', 'Annual rental income as a percentage of the property''s value. e.g. $25,000 rent on a $500,000 property = 5% yield.', 'Property'),
  ('hin', 'HIN', 'Holder Identification Number — a unique number assigned to you when your shares are CHESS-sponsored. It starts with an ''X'' and lets you transfer shares between brokers without selling.', 'Share Trading'),
  ('fractional-shares', 'Fractional Shares', 'Buying a portion of a share instead of a whole one. e.g. $50 worth of a $500 share. Offered by some platforms to lower the entry barrier.', 'Share Trading'),
  ('inactivity-fee', 'Inactivity Fee', 'A fee some platforms charge if you don''t trade for a certain period (e.g. 6 or 12 months). Many modern platforms have removed this fee.', 'Fees'),
  ('paper-trading', 'Paper Trading', 'Practising trades with fake money in a simulated market. A risk-free way to learn before investing real money. Also called a demo account.', 'Share Trading'),
  ('srs', 'SRS', 'Sponsored Reporting Service — CHESS-sponsored holders receive statements directly from the ASX registry (Computershare or Link Market Services) confirming their holdings.', 'Share Trading'),
  ('lvr', 'LVR', 'Loan-to-Value Ratio — the percentage of a property''s value that you''re borrowing. e.g. borrowing $400,000 on a $500,000 property = 80% LVR. Above 80% usually requires Lenders Mortgage Insurance.', 'Property'),
  ('lmi', 'LMI', 'Lenders Mortgage Insurance — a one-off insurance premium you pay when borrowing more than 80% of a property''s value. Protects the lender (not you) if you default. Can cost $5,000–$30,000+.', 'Property'),
  ('offset-account', 'Offset Account', 'A savings account linked to your mortgage. Money in the offset reduces the loan balance that interest is calculated on. e.g. $50,000 in offset on a $500,000 loan = interest charged on $450,000.', 'Property'),
  ('capital-growth', 'Capital Growth', 'The increase in an asset''s value over time. e.g. a property bought for $600,000 that''s now worth $750,000 has had $150,000 (25%) capital growth.', 'Property'),
  ('equity', 'Equity', 'The portion of a property you actually own — the property''s value minus what you owe on the mortgage. Can be used as security to borrow for further investments.', 'Property'),
  ('settlement', 'Settlement', 'The legal process of transferring property ownership from seller to buyer. In Australia, settlement typically takes 30–90 days after contracts are exchanged.', 'Property'),
  ('bond', 'Bond', 'A loan you make to a government or company in exchange for regular interest payments and your money back at maturity. Generally lower risk than shares but lower returns.', 'General'),
  ('term-deposit', 'Term Deposit', 'A bank deposit where you lock your money away for a fixed period (1 month to 5 years) at a guaranteed interest rate. Safe but inflexible — early withdrawal incurs penalties.', 'General'),
  ('yield', 'Yield', 'The income return on an investment, expressed as a percentage. e.g. a share paying $2 in annual dividends with a $40 price has a 5% dividend yield.', 'General'),
  ('coupon-rate', 'Coupon Rate', 'The annual interest rate paid by a bond, expressed as a percentage of its face value. e.g. a $1,000 bond with a 4% coupon pays $40/year in interest.', 'General'),
  ('income-protection', 'Income Protection', 'Insurance that replaces up to 75% of your income if you can''t work due to illness or injury. Premiums are generally tax-deductible in Australia.', 'Insurance'),
  ('tpd-insurance', 'TPD Insurance', 'Total and Permanent Disability insurance — pays a lump sum if you become permanently unable to work. Often held inside super to reduce out-of-pocket cost.', 'Insurance'),
  ('life-insurance', 'Life Insurance', 'Pays a lump sum to your beneficiaries if you die. Can be held inside or outside super. The amount should cover debts, living expenses for dependants, and future goals.', 'Insurance'),
  ('trust', 'Trust', 'A legal structure where a trustee holds assets on behalf of beneficiaries. Family (discretionary) trusts allow flexible distribution of investment income to reduce overall tax.', 'Tax'),
  ('marginal-tax-rate', 'Marginal Tax Rate', 'The tax rate you pay on each additional dollar of income. In Australia, rates range from 0% (under $18,200) to 45% (over $190,000) plus the 2% Medicare levy.', 'Tax'),
  ('payg', 'PAYG', 'Pay As You Go — Australia''s system for collecting income tax throughout the year (via employer withholding) rather than in one lump sum at tax time.', 'Tax'),
  ('cost-base', 'Cost Base', 'The original cost of an investment plus associated costs (brokerage, stamp duty). Used to calculate capital gains or losses when you sell.', 'Tax'),
  ('blue-chip', 'Blue Chip', 'Large, well-established companies with a long history of reliable performance. In Australia, blue chips include BHP, CBA, CSL, and Woolworths. Lower risk but also lower growth potential than small caps.', 'Share Trading'),
  ('small-cap', 'Small Cap', 'A company with a relatively small market capitalisation (typically under $2 billion in Australia). Higher growth potential but also higher risk and volatility than large caps.', 'Share Trading'),
  ('market-capitalisation', 'Market Capitalisation', 'The total value of a company''s shares — calculated by multiplying the share price by the number of shares on issue. Used to classify companies as large cap, mid cap, or small cap.', 'Share Trading'),
  ('ipo', 'IPO', 'Initial Public Offering — when a private company lists on the stock exchange for the first time, offering shares to the public. Can be high-reward but also high-risk.', 'Share Trading'),
  ('vesting', 'Vesting', 'The process by which you gain full ownership of employer-granted shares or options over time. Common in startup and tech company compensation packages.', 'Share Trading'),
  ('asx-200', 'ASX 200', 'An index of the 200 largest companies listed on the ASX by market capitalisation. The main benchmark for the Australian share market''s performance.', 'General'),
  ('bear-market', 'Bear Market', 'A sustained decline in the market — typically defined as a 20%+ drop from recent highs. The opposite of a bull market. Bear markets are normal and historically temporary.', 'General'),
  ('bull-market', 'Bull Market', 'A sustained period of rising share prices. Generally defined as a 20%+ rise from recent lows. Bull markets tend to last longer than bear markets.', 'General'),
  ('volatility', 'Volatility', 'How much an investment''s price fluctuates over time. High volatility means bigger price swings (up and down). Crypto and small caps are high volatility; bonds and term deposits are low volatility.', 'General'),
  ('liquidity', 'Liquidity', 'How quickly and easily an asset can be converted to cash without significantly affecting its price. ASX blue chips and major ETFs are highly liquid; property and unlisted investments are illiquid.', 'General'),
  ('dollar-cost-averaging', 'Dollar-Cost Averaging', 'Investing a fixed amount at regular intervals regardless of price, automatically buying more units when prices are low and fewer when high. Removes emotion from timing decisions.', 'General'),
  ('asset-allocation', 'Asset Allocation', 'How you divide your portfolio across different asset classes — shares, bonds, property, cash. Your allocation should reflect your goals and risk tolerance.', 'General'),
  ('passive-investing', 'Passive Investing', 'An investment approach that tracks a market index rather than trying to beat it. Typically done through ETFs. Lower fees and historically outperforms most active managers over the long term.', 'General'),
  ('active-investing', 'Active Investing', 'Picking individual shares or timing the market to try to outperform a benchmark. Higher fees and most active fund managers underperform their index over 10+ years.', 'General'),
  ('portfolio-rebalancing', 'Portfolio Rebalancing', 'Adjusting your portfolio back to your target allocation after market movements shift the weights. E.g. if shares rise to 75% of your portfolio but your target is 70%, you sell some shares to rebalance.', 'General'),
  ('managed-fund', 'Managed Fund', 'A pooled investment where a professional fund manager makes investment decisions on behalf of investors. Unlike ETFs, most managed funds are not listed on the ASX and are bought/sold at end-of-day prices.', 'General'),
  ('infrastructure-fund', 'Infrastructure Fund', 'A fund that invests in physical infrastructure assets like toll roads, airports, ports, and utilities. Typically offers stable, inflation-linked income streams. Examples: APA Group, Transurban, IFT.', 'General'),
  ('listed-investment-company', 'Listed Investment Company', 'An ASX-listed company that holds a portfolio of investments. Like an ETF but structured as a company. Trades at a premium or discount to its net asset value (NAV). Examples: AFI, MLT, ARG.', 'Share Trading')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.glossary_terms (slug, term, definition, category) VALUES
  ('net-asset-value', 'Net Asset Value', 'The per-unit value of a fund''s assets minus liabilities. For ETFs, the share price trades close to NAV. For LICs, the share price can trade at a premium or discount to NAV.', 'Share Trading'),
  ('earnings-per-share', 'Earnings Per Share', 'A company''s net profit divided by the number of shares on issue. Higher EPS generally means the company is more profitable. Used to calculate the P/E ratio.', 'Share Trading'),
  ('price-to-book-ratio', 'Price-to-Book Ratio', 'A company''s share price divided by its book value per share (assets minus liabilities). A ratio below 1 may indicate the shares are undervalued relative to assets.', 'Share Trading'),
  ('return-on-equity', 'Return on Equity', 'How much profit a company generates for each dollar of shareholder equity. A higher ROE generally means management is using capital efficiently. Look for sustained ROE above 15%.', 'Share Trading'),
  ('economic-moat', 'Economic Moat', 'A sustainable competitive advantage that protects a company''s profits from competitors. Coined by Warren Buffett. Examples: brand strength (CBA), switching costs (Xero), cost advantages (Woolworths).', 'Share Trading'),
  ('value-investing', 'Value Investing', 'Buying shares that appear underpriced relative to their intrinsic value — often measured by P/E, P/B, or dividend yield. Made famous by Warren Buffett and Benjamin Graham.', 'Share Trading'),
  ('growth-investing', 'Growth Investing', 'Focusing on companies expected to grow earnings faster than average, often reinvesting profits rather than paying dividends. Examples: tech stocks, small-cap innovators. Higher risk, higher potential return.', 'Share Trading'),
  ('ex-dividend-date', 'Ex-Dividend Date', 'The date from which new buyers are no longer entitled to receive the upcoming dividend. If you buy shares on or after the ex-dividend date, you won''t receive that payment. The share price typically falls by roughly the dividend amount on this date.', 'Share Trading'),
  ('rights-issue', 'Rights Issue', 'When a company offers existing shareholders the right to buy additional new shares at a discounted price, usually to raise capital. Shareholders can exercise the right (buy the shares) or sell the rights on the ASX.', 'Share Trading'),
  ('share-buyback', 'Share Buyback', 'When a company repurchases its own shares from the market, reducing the total shares on issue. Often signals management believes the shares are undervalued. Increases earnings per share for remaining shareholders.', 'Share Trading'),
  ('accumulation-phase', 'Accumulation Phase', 'The period during your working life when you are building your super balance through contributions and investment returns. Earnings in accumulation phase are taxed at 15%.', 'Super'),
  ('pension-phase', 'Pension Phase', 'When you convert your super into an income stream (account-based pension) in retirement. Investment earnings and income payments are tax-free (up to the transfer balance cap of $1.9 million in 2026).', 'Super'),
  ('transition-to-retirement', 'Transition to Retirement', 'A strategy for Australians aged 60-67 who are still working but want to access some of their super as an income stream. Allows salary sacrificing more into super while drawing down a pension, potentially improving tax efficiency.', 'Super'),
  ('non-concessional-contributions', 'Non-Concessional Contributions', 'After-tax super contributions (i.e. not tax-deductible). The annual cap is $120,000 in 2026. You can make up to $360,000 in one year using the bring-forward rule if you''re under 75 and your total super balance allows.', 'Super'),
  ('bring-forward-rule', 'Bring-Forward Rule', 'Allows you to contribute up to three years of non-concessional contributions in a single year ($360,000 in 2026), if your total super balance is below $1.66 million. Useful for large lump-sum contributions.', 'Super'),
  ('binding-death-benefit-nomination', 'Binding Death Benefit Nomination', 'A legal instruction to your super fund specifying who receives your super balance when you die. A valid binding nomination overrides the trustee''s discretion. Must usually be renewed every 3 years unless ''non-lapsing''.', 'Super'),
  ('options', 'Options', 'Contracts giving the right (but not obligation) to buy (call option) or sell (put option) an asset at a set price before a set date. Used for hedging or speculation. Complex instruments suitable only for experienced investors.', 'CFD & Forex'),
  ('futures', 'Futures', 'Contracts obligating you to buy or sell an asset at a predetermined price on a future date. Used by institutional investors to hedge or speculate on commodities, indices, and currencies. High leverage and risk.', 'CFD & Forex'),
  ('margin-call', 'Margin Call', 'A demand from your broker to deposit more funds when your account falls below the minimum margin requirement. Failure to meet a margin call results in your positions being automatically closed at a loss.', 'CFD & Forex'),
  ('gearing', 'Gearing', 'Borrowing money to invest. Positive gearing means rental income exceeds costs (profit). Negative gearing means costs exceed income (a tax-deductible loss). Neutral gearing means income equals costs.', 'Property'),
  ('stamp-duty', 'Stamp Duty', 'A state government tax on property purchases, calculated as a percentage of the purchase price. One of the largest upfront costs of buying property. Rates vary by state; first home buyers often receive concessions.', 'Property'),
  ('capital-works-deduction', 'Capital Works Deduction', 'A tax deduction for the cost of constructing or renovating income-producing property, claimed at 2.5% per year over 40 years. Different from depreciation, which covers removable items like appliances and carpets.', 'Tax'),
  ('smsf-accountant', 'SMSF Accountant', 'A specialist accountant who handles the tax, accounting, and compliance work for self-managed super funds. SMSFs must lodge annual returns, prepare financial statements, and meet strict ATO rules — most trustees outsource this to an SMSF accountant.', 'SMSF'),
  ('smsf-auditor', 'SMSF Auditor', 'An independent auditor registered with ASIC who must audit every SMSF annually before its tax return is lodged. The auditor checks compliance with the SIS Act, investment rules, and financial reporting standards. Required by law each year.', 'SMSF'),
  ('in-house-asset', 'In-House Asset', 'An investment, loan, or lease between an SMSF and a related party (e.g. a fund member''s business). In-house assets cannot exceed 5% of the SMSF''s total asset value. Breaching this cap is a major compliance issue.', 'SMSF'),
  ('sole-purpose-test', 'Sole Purpose Test', 'The SIS Act rule that every SMSF must be maintained only for the purpose of providing retirement benefits. Using SMSF assets for personal use (e.g. living in an SMSF-owned property) breaches this test and risks the fund''s tax concessions.', 'SMSF'),
  ('non-concessional-contribution', 'Non-Concessional Contribution', 'A contribution to super made from after-tax money. These are not taxed on entry but are capped (currently $120,000/year). Useful for high-earners consolidating savings into super.', 'Super'),
  ('concessional-contribution', 'Concessional Contribution', 'A pre-tax contribution to super, including employer SG and salary sacrifice. Taxed at 15% on entry (or 30% for high-income earners). Capped at $30,000/year for most people.', 'Super'),
  ('transfer-balance-cap', 'Transfer Balance Cap', 'The lifetime cap on how much super can be transferred into the tax-free retirement pension phase. Currently $1.9m. Amounts above this must stay in accumulation (taxed at 15%).', 'Super'),
  ('division-293-tax', 'Division 293 Tax', 'An extra 15% tax on concessional super contributions for individuals with income (including super) above $250,000. Effectively makes super tax 30% for high earners on the relevant portion.', 'Super'),
  ('jorc-code', 'JORC Code', 'The Joint Ore Reserves Committee code — Australia''s standard for reporting exploration results, mineral resources, and ore reserves on ASX-listed mining companies. JORC-compliant announcements are legally binding and auditable.', 'Mining'),
  ('prrt', 'PRRT', 'The Petroleum Resource Rent Tax — a 40% tax on the net profits of petroleum projects in Australia. Targets oil and gas producers and is levied after the company recovers its exploration and capital costs.', 'Mining'),
  ('royalty', 'Royalty', 'A payment made to a state government or private landholder based on the volume or value of resources extracted. Different states charge different royalty rates for different commodities. Separate from company tax.', 'Mining'),
  ('feasibility-study', 'Feasibility Study', 'A detailed engineering and economic study evaluating whether a mining project is technically and financially viable. Usually progresses scoping → pre-feasibility → definitive feasibility before a company commits to construction.', 'Mining'),
  ('offtake-agreement', 'Offtake Agreement', 'A pre-production contract in which a buyer agrees to purchase a specified volume of a miner''s future output. Critical for financing — lenders often require offtake agreements before releasing capital.', 'Mining'),
  ('critical-minerals', 'Critical Minerals', 'Minerals deemed strategically essential (e.g. lithium, nickel, rare earths) that Australia exports to allies for EV batteries, defence, and clean energy. The Australian government publishes a Critical Minerals List guiding investment incentives.', 'Mining'),
  ('tenement', 'Tenement', 'An exploration or mining lease granted by a state government giving a company the exclusive right to explore or mine a defined area for a specified period. Tenement registers are public and listed miners must disclose their holdings.', 'Mining'),
  ('native-title', 'Native Title', 'Traditional Aboriginal and Torres Strait Islander rights over land and waters, recognised under Australian law. Mining companies must negotiate Indigenous Land Use Agreements (ILUAs) before developing projects on native-title land.', 'Mining'),
  ('firb', 'FIRB', 'The Foreign Investment Review Board — the government body that reviews and recommends whether proposed foreign investments align with Australia''s national interest. Approvals are issued by the Treasurer.', 'Foreign Investment'),
  ('siv', 'SIV', 'The Significant Investor Visa (subclass 188C) — an investor visa requiring $5m of complying investments in Australia. Offers a residency pathway without needing English-language tests or age limits.', 'Foreign Investment'),
  ('complying-investment-framework', 'Complying Investment Framework', 'The set of rules defining which Australian investments qualify for the Significant Investor Visa. Currently requires a minimum $1m in venture capital, $1.5m in emerging companies, and the remainder in balanced products.', 'Foreign Investment'),
  ('non-resident-withholding-tax', 'Non-Resident Withholding Tax', 'The flat rate of tax deducted at source on Australian-sourced income paid to foreign residents. Rates differ by income type and treaty: typically 30% on unfranked dividends, 10% on interest, 30% on royalties before DTA relief.', 'Tax'),
  ('double-tax-agreement', 'Double Tax Agreement', 'A treaty between two countries that allocates taxing rights so the same income isn''t taxed twice. Australia has DTAs with ~45 countries, reducing withholding rates on dividends, interest, and royalties.', 'Tax'),
  ('vacancy-fee', 'Vacancy Fee', 'An annual federal fee charged to foreign owners of Australian residential property that is vacant for more than 183 days in a year. Enforced by the ATO; rates vary by purchase price.', 'Foreign Investment'),
  ('stamp-duty-surcharge-foreign', 'Stamp Duty Surcharge', 'An extra stamp duty imposed by state governments on foreign buyers of Australian residential property. Rates range from 7% (NSW) to 8% (VIC, QLD) on top of standard duty.', 'Foreign Investment'),
  ('temporary-resident', 'Temporary Resident', 'A person holding a temporary Australian visa. Temporary residents can buy one established home to live in (subject to FIRB approval) but must sell when their visa ends.', 'Foreign Investment'),
  ('tax-residency', 'Tax Residency', 'Whether you''re an Australian tax resident for a given financial year. Residents are taxed on worldwide income at progressive rates; non-residents only on Australian-sourced income but at higher withholding rates and without the tax-free threshold.', 'Tax'),
  ('managed-investment-trust', 'MIT', 'Managed Investment Trust — an Australian collective investment vehicle that can pass income through to investors with concessional withholding tax (15%) on distributions to foreign residents. Common for unlisted property and infrastructure funds.', 'Tax'),
  ('land-tax', 'Land Tax', 'A state government tax on investment property based on the unimproved value of land. Your principal residence is usually exempt. Rates are progressive and reset annually on 31 December (NSW) or 30 June (other states).', 'Property'),
  ('strata-title', 'Strata Title', 'Ownership of a unit in a multi-unit development where you individually own your unit and jointly own common areas with other owners. Governed by a body corporate / owners corporation.', 'Property')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.glossary_terms (slug, term, definition, category) VALUES
  ('torrens-title', 'Torrens Title', 'The Australian system for registering property ownership. Whoever is on the Torrens register is the legal owner. Provides government-backed title guarantees.', 'Property'),
  ('vendor', 'Vendor', 'The seller in a property transaction. Vendors usually engage a conveyancer or solicitor to prepare the contract of sale and handle settlement.', 'Property'),
  ('conveyancer', 'Conveyancer', 'A licensed professional who handles the legal transfer of property ownership. Cheaper than a solicitor for simple transactions; solicitors are preferred for complex titles or disputes.', 'Property'),
  ('cooling-off-period', 'Cooling-Off Period', 'The short window (usually 5 business days in NSW/QLD) after signing a contract of sale during which the buyer can withdraw and forfeit only a small deposit. Auction sales have no cooling off.', 'Property'),
  ('off-the-plan', 'Off-the-Plan', 'Buying a property before it''s built, often with a 10% deposit and settlement when construction finishes. Can defer stamp duty in some states but carries construction and market-timing risk.', 'Property'),
  ('lic', 'LIC', 'Listed Investment Company — an ASX-listed company that holds a portfolio of other companies. Differs from an ETF in that it''s a closed-end fund so its share price can trade at a premium or discount to NAV.', 'Share Trading'),
  ('nav', 'NAV', 'Net Asset Value — the per-unit value of a fund''s holdings after subtracting liabilities. For ETFs, the market price usually tracks NAV closely; for LICs it can diverge materially.', 'General'),
  ('closed-end-fund', 'Closed-End Fund', 'A fund with a fixed number of units that trade on an exchange, rather than being issued and redeemed on demand. Price is set by the market and can trade above or below NAV.', 'General'),
  ('management-expense-ratio', 'MER', 'Management Expense Ratio — the total annual cost of running a managed fund, expressed as a percentage of assets. Passive ETFs often charge 0.05–0.40%; actively managed funds 0.70–2%+.', 'Fees'),
  ('performance-fee', 'Performance Fee', 'An additional fee (often 10-20%) a fund charges on returns above a benchmark or hurdle rate. Common in hedge funds and some Australian LICs. Can materially reduce investor returns in strong years.', 'Fees'),
  ('high-water-mark', 'High-Water Mark', 'A rule ensuring performance fees are only paid on new highs in a fund''s NAV. Protects investors from paying twice for the same performance after a drawdown.', 'Fees'),
  ('hurdle-rate', 'Hurdle Rate', 'The minimum return a fund must deliver before performance fees kick in — often set at the risk-free rate or a benchmark like the ASX 200 return.', 'Fees'),
  ('managed-account', 'Managed Account', 'An investment portfolio where an external manager makes trading decisions on your behalf but the assets are held in your own name on a platform. Different from a managed fund where you own units in a pool.', 'General'),
  ('sma', 'Separately Managed Account', 'SMA — a managed account where an external manager runs a standardised model portfolio on your behalf. Cheaper than fully bespoke management; more transparent than a managed fund.', 'General'),
  ('wholesale-investor', 'Wholesale Investor', 'Under the Corporations Act, a wholesale investor is someone with $2.5m+ net assets, $250k+ annual income, or investing $500k+ in a single product. Wholesale investors can access products that aren''t available to retail investors.', 'Regulatory'),
  ('sophisticated-investor', 'Sophisticated Investor', 'A wholesale investor certified by an accountant as having sufficient financial knowledge. Often used as the entry test for early-stage private placements and wholesale funds.', 'Regulatory'),
  ('buyers-agent', 'Buyer''s Agent', 'A licensed property professional who sources and negotiates purchases on behalf of the buyer. Paid by the buyer, not the seller. Useful for interstate purchases or time-poor investors.', 'Property'),
  ('mortgage-broker', 'Mortgage Broker', 'A licensed intermediary who matches borrowers with lenders across the market, rather than representing a single bank. Paid via commission from the lender, not the borrower.', 'Property'),
  ('financial-planner', 'Financial Planner', 'An AFSL-authorised representative who gives personal financial advice. In Australia, planners must hold FAR-compliant qualifications, meet CPD requirements, and disclose fees and conflicts.', 'Regulatory'),
  ('statement-of-advice', 'Statement of Advice', 'SOA — the formal written advice document a planner must provide before implementing recommendations. Must disclose fees, conflicts, benefits, and the research basis. Key legal record of personal advice.', 'Regulatory'),
  ('best-interests-duty', 'Best Interests Duty', 'The legal obligation on Australian financial advisers to act in the client''s best interests — not the adviser''s, not the employer''s. Breaches trigger ASIC action and civil penalties.', 'Regulatory'),
  ('authorised-representative', 'Authorised Representative', 'A person or company authorised to provide financial services under another entity''s AFSL. Advisers employed by planning practices are usually authorised representatives of the practice''s licensee.', 'Regulatory'),
  ('far', 'FAR', 'Financial Adviser Register — the public ASIC register listing every adviser, their licensee, and their qualifications. Always check an adviser is on FAR before engaging them.', 'Regulatory'),
  ('mara', 'MARA', 'Migration Agents Registration Authority — the government body that registers migration agents in Australia. Only MARA-registered agents may give immigration advice for a fee.', 'Regulatory'),
  ('medicare-levy', 'Medicare Levy', 'A 2% tax on taxable income that funds Australia''s public health system. Low-income earners are exempt or pay a reduced rate. High-income earners without private hospital cover also pay the Medicare Levy Surcharge.', 'Tax'),
  ('fbt', 'FBT', 'Fringe Benefits Tax — paid by employers on non-cash benefits provided to employees (e.g. company cars, gym memberships). FBT year runs 1 April to 31 March.', 'Tax'),
  ('gst', 'GST', 'Goods and Services Tax — a 10% tax on most goods and services sold in Australia. Most investment activities (shares, super) are GST-free or input-taxed.', 'Tax'),
  ('tax-offset', 'Tax Offset', 'A direct reduction in the tax you pay, applied after your tax is calculated. Differs from a deduction, which reduces your taxable income. The franking credit offset is the most valuable for investors.', 'Tax'),
  ('listo', 'Low Income Super Tax Offset', 'LISTO — a government refund of up to $500 of the 15% contributions tax for low-income earners ($37k or below). Paid automatically into super each year.', 'Super'),
  ('super-co-contribution', 'Super Co-Contribution', 'A government contribution of up to $500 to your super for low-to-middle-income earners who make personal after-tax contributions. Phases out at $60,400/year income (2026).', 'Super'),
  ('spouse-super-contribution', 'Spouse Super Contribution', 'A contribution you make to your spouse''s super fund. If your spouse earns under $40k you may claim a tax offset of up to $540. Useful for balancing super between partners.', 'Super'),
  ('cold-wallet', 'Cold Wallet', 'A cryptocurrency wallet that stores private keys offline (e.g. hardware wallet, paper wallet). Immune to remote hacking but requires physical security. Standard for large crypto holdings.', 'Crypto'),
  ('hot-wallet', 'Hot Wallet', 'A cryptocurrency wallet connected to the internet (e.g. exchange wallet, mobile app). Convenient for trading but vulnerable to exchange hacks and phishing.', 'Crypto'),
  ('self-custody', 'Self-Custody', 'Holding your own cryptocurrency private keys, rather than trusting an exchange or custodian. Maximum security and control but no recovery option if keys are lost.', 'Crypto'),
  ('asic-leverage-cap', 'ASIC Leverage Cap', 'ASIC''s retail CFD rules imposing maximum leverage of 30:1 on forex majors, 20:1 on indices, 2:1 on crypto, and 5:1 on other CFDs. Professional clients can request higher limits.', 'CFD & Forex'),
  ('corporations-act', 'Corporations Act', 'The primary Australian law governing companies, financial products, and financial services. Administered by ASIC and covers everything from director duties to disclosure to licensing.', 'Regulatory'),
  ('ongoing-fee-arrangement', 'Ongoing Fee Arrangement', 'An annual fee for ongoing financial advice that must be agreed in writing by the client each year (FDS and annual renewal). Required disclosure framework for subscription-style adviser relationships.', 'Regulatory'),
  ('ddo', 'Design and Distribution Obligations', 'DDO — rules requiring product issuers to define a target market for each financial product and distribute it only to clients in that market. Implemented in 2021 to strengthen consumer protection.', 'Regulatory'),
  ('market-depth', 'Market Depth', 'A real-time view of pending buy and sell orders at each price level. Helps traders judge liquidity and short-term supply/demand. Some brokers charge extra for full market depth data.', 'Share Trading'),
  ('corporate-action', 'Corporate Action', 'An event initiated by a listed company that affects shareholders — e.g. dividend, buyback, share split, rights issue, takeover. Investors must usually respond by a deadline.', 'Share Trading'),
  ('superstream', 'SuperStream', 'The ATO standard for electronic payment and data exchange of super contributions. All employers and funds must use SuperStream — it''s what enables same-day super transfers.', 'Super'),
  ('superannuation-guarantee', 'SG', 'Superannuation Guarantee — the minimum percentage of ordinary time earnings employers must pay into employees'' super. Currently 11.5% and rising to 12% in July 2025.', 'Super'),
  ('franking-percentage', 'Franking Percentage', 'The percentage of a dividend that carries franking credits. 100% franked means full corporate tax has been paid; 50% franked means only half. Unfranked dividends carry no imputation benefit.', 'Tax'),
  ('imputation-credit', 'Imputation Credit', 'Another name for a franking credit — the corporate tax already paid on a dividend, credited back to shareholders to prevent double taxation.', 'Tax'),
  ('ex-ante-return', 'Ex-Ante Return', 'An expected future return, calculated before the fact using assumptions about growth and yield. Contrasted with ex-post returns (actual, historical).', 'General'),
  ('alpha', 'Alpha', 'The excess return of an investment relative to a benchmark, adjusted for risk. Positive alpha means the manager beat the index; negative means they underperformed.', 'General'),
  ('beta', 'Beta', 'A measure of how much an asset''s price moves relative to the overall market. Beta of 1 moves in line; 1.5 is 50% more volatile; 0.5 is half as volatile.', 'General'),
  ('sharpe-ratio', 'Sharpe Ratio', 'A measure of risk-adjusted return: excess return above the risk-free rate divided by volatility. Higher is better — shows return per unit of risk taken.', 'General'),
  ('standard-deviation', 'Standard Deviation', 'A statistical measure of how much a return varies from its average over time. Used as the most common proxy for risk or volatility in finance.', 'General'),
  ('tracking-error', 'Tracking Error', 'How closely a passive fund follows its benchmark. Small tracking error is desirable for index funds — it means you''re getting the index return minus fees.', 'General')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.glossary_terms (slug, term, definition, category) VALUES
  ('drawdown', 'Drawdown', 'The peak-to-trough fall in portfolio value during a losing period, expressed as a percentage. Max drawdown is a key risk metric for evaluating managers and strategies.', 'General'),
  ('duration', 'Duration', 'A measure of a bond''s price sensitivity to interest-rate changes. A duration of 5 means a 1% rate rise causes roughly a 5% bond-price fall. Higher duration = higher rate risk.', 'General'),
  ('credit-spread', 'Credit Spread', 'The extra yield a corporate bond offers over a government bond of the same maturity. Compensates investors for credit risk — wider spreads mean markets see more default risk.', 'General')
ON CONFLICT (slug) DO NOTHING;
