-- Migration: demand_pools — Group Briefs (pooled demand auctions, idea #17).
--
-- Clusters consenting consumers with the same need (brief template × state ×
-- calendar month) into a demand POOL. Advisers respond once with a single
-- structured GROUP OFFER (availability + a package rate band); each pool
-- member then individually accepts or declines on their own brief tracker.
--
-- Strictly LEAD ROUTING, not a financial market (see
-- docs/strategy/REGULATORY-AVOID-LIST.md → "Australian Market Licence"):
--   * Nothing is traded or matched between consumers; no financial products
--     change hands. A pool is a bundle of leads.
--   * Group "rates" are the ADVISER'S OWN quoted package pricing — not a
--     consumer→adviser money intermediation. The platform never clips a fee;
--     a member accept debits the adviser via flat B2B credits (the existing
--     advisor_credit_ledger accept path, at a volume discount).
--   * Each member decides individually — no group purchase, no aggregation.
--
-- Three tables:
--   demand_pools   — one row per (template_key, state, period); the cluster.
--   pool_members   — a brief that opted in and was assigned to a pool.
--   pool_offers    — one structured group offer per adviser per pool.
--
-- Dormant behind the `demand_pools` feature flag (fail-closed): with the flag
-- off the opt-in checkbox never renders, the adviser inbox shows no pool cards,
-- pool surfaces 404, and the clustering step is a no-op — so these tables may
-- sit empty indefinitely without affecting any live path.
--
-- Pools expire at end-of-period; the status flip from 'forming'/'offered' to
-- 'expired' is handled LAZILY on read (lib/briefs/demand-pools.ts → isPool
-- ExpiredForRead / markPoolExpiredIfDue), so no new cron is introduced.
--
-- RLS: service_role-only — these are anonymous, email-keyed surfaces with the
-- same posture as engagement_registry (the brief tracker reads via admin and
-- gates all PII by emailMatches; the adviser inbox reads via an authed advisor
-- session through the service-role client). No anon/authenticated policy.
--
-- Rollback:
--   DROP TABLE IF EXISTS public.pool_offers;
--   DROP TABLE IF EXISTS public.pool_members;
--   DROP TABLE IF EXISTS public.demand_pools;

BEGIN;

-- ── demand_pools ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.demand_pools (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_key text NOT NULL,
  state text NOT NULL,
  -- Calendar-month bucket, e.g. '2026-06'.
  period text NOT NULL,
  status text NOT NULL DEFAULT 'forming'
    CHECK (status IN ('forming', 'offered', 'closed', 'expired')),
  min_size integer NOT NULL DEFAULT 3,
  max_size integer NOT NULL DEFAULT 12,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (template_key, state, period)
);

CREATE INDEX IF NOT EXISTS idx_demand_pools_lookup
  ON public.demand_pools (template_key, state, period);
CREATE INDEX IF NOT EXISTS idx_demand_pools_status
  ON public.demand_pools (status);

ALTER TABLE public.demand_pools ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Service role manages demand_pools" ON public.demand_pools;
CREATE POLICY "Service role manages demand_pools"
  ON public.demand_pools FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ── pool_members ──────────────────────────────────────────────────────────
-- One brief per pool membership. brief_id is globally UNIQUE: a brief belongs
-- to at most one pool, ever. consumer_email is the email-as-key auth factor
-- mirrored from the brief (the tracker gates PII by it).
CREATE TABLE IF NOT EXISTS public.pool_members (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pool_id bigint NOT NULL REFERENCES public.demand_pools(id) ON DELETE CASCADE,
  brief_id integer NOT NULL UNIQUE,
  consumer_email text NOT NULL,
  status text NOT NULL DEFAULT 'joined'
    CHECK (status IN ('joined', 'left', 'accepted')),
  joined_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_pool_members_pool ON public.pool_members (pool_id);
CREATE INDEX IF NOT EXISTS idx_pool_members_email ON public.pool_members (consumer_email);

ALTER TABLE public.pool_members ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Service role manages pool_members" ON public.pool_members;
CREATE POLICY "Service role manages pool_members"
  ON public.pool_members FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ── pool_offers ───────────────────────────────────────────────────────────
-- One structured group offer per adviser per pool. body is the adviser's own
-- words (<=500 chars); package_rate_band is the adviser's own quoted package
-- pricing band — never platform-set, never a consumer→adviser money path.
CREATE TABLE IF NOT EXISTS public.pool_offers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pool_id bigint NOT NULL REFERENCES public.demand_pools(id) ON DELETE CASCADE,
  professional_id integer NOT NULL,
  body text NOT NULL CHECK (char_length(body) <= 500),
  package_rate_band text,
  status text NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'withdrawn', 'expired')),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (pool_id, professional_id)
);

CREATE INDEX IF NOT EXISTS idx_pool_offers_pool ON public.pool_offers (pool_id);
CREATE INDEX IF NOT EXISTS idx_pool_offers_professional
  ON public.pool_offers (professional_id);

ALTER TABLE public.pool_offers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Service role manages pool_offers" ON public.pool_offers;
CREATE POLICY "Service role manages pool_offers"
  ON public.pool_offers FOR ALL TO service_role USING (true) WITH CHECK (true);

COMMIT;
