-- Expand best_for_scenarios from 3 to 30.
--
-- Each scenario powers a /best-for/<slug> programmatic SEO page.
-- The scoring_weights are applied against broker columns to produce
-- a deterministic ranking. Negative weights mean "lower is better"
-- (e.g. asx_fee_value: -0.40 ranks cheaper brokers higher).
--
-- Target user descriptions are kept under 2 sentences to avoid
-- the page looking padded. Intros are 2-3 sentences and focus on
-- why this scenario matters — not generic fluff.

INSERT INTO public.best_for_scenarios
  (slug, h1, intro, meta_description, scoring_weights, required_attrs, target_user, display_order)
VALUES
  ('day-trading-asx',
   'Best brokers for ASX day trading (2026)',
   'Day traders need rock-bottom ASX brokerage because commission costs compound over hundreds of trades per month. The rankings below weight ASX brokerage most heavily, with bonuses for real-time data, margin availability and platform speed.',
   'Independent ranking of the cheapest Australian brokers for ASX day trading. Brokerage fees, real-time data, margin and platform speed compared.',
   '{"asx_fee_value": -0.55, "rating": 0.20, "chess_sponsored": 0.15, "us_fee_value": -0.10}',
   '{}',
   'Active traders placing 20+ ASX trades per month who need the lowest possible brokerage.',
   40),

  ('us-shares-low-fx',
   'Best brokers for US shares with low FX fees',
   'FX conversion fees are the hidden cost of buying US shares from Australia. A 0.70% FX spread on a $10,000 transfer costs $70 before you even buy a share. The rankings below weight FX rates and US brokerage above everything else.',
   'Compare Australian brokers for US shares by FX conversion cost. Independent ranking by FX spread, US brokerage and platform features.',
   '{"us_fee_value": -0.30, "fx_rate": -0.45, "asx_fee_value": -0.10, "chess_sponsored": 0.15}',
   '{}',
   'Australian investors buying US shares who want the lowest total cost including FX conversion.',
   50),

  ('zero-brokerage',
   'Best $0 brokerage platforms in Australia',
   'Several Australian platforms now offer $0 brokerage on ASX or US trades — but the tradeoffs vary. Some recoup costs through wider FX spreads, some through payment for order flow, and some through premium subscription tiers. We rank them by total cost, not just headline brokerage.',
   'Independent ranking of $0 brokerage platforms in Australia. We compare the real total cost including FX, subscription fees and platform limitations.',
   '{"asx_fee_value": -0.50, "us_fee_value": -0.25, "fx_rate": -0.15, "rating": 0.10}',
   '{}',
   'Cost-conscious investors looking for genuinely zero or near-zero brokerage in Australia.',
   60),

  ('chess-sponsored-only',
   'Best CHESS-sponsored brokers in Australia',
   'CHESS sponsorship means your shares are held in your name on the ASX subregister — not pooled in a custodian omnibus account. If your broker goes under, CHESS-sponsored holdings are yours. The rankings below only include brokers that offer CHESS sponsorship and weight it as the top factor.',
   'Independent comparison of CHESS-sponsored brokers in Australia. Only brokers that hold your shares in your name on the ASX subregister.',
   '{"chess_sponsored": 0.45, "asx_fee_value": -0.30, "rating": 0.15, "us_fee_value": -0.10}',
   ARRAY['chess_sponsored']::text[],
   'Investors who require CHESS-sponsored holdings for custody protection.',
   70),

  ('crypto-trading',
   'Best platforms for crypto trading in Australia',
   'Crypto platforms in Australia range from dedicated exchanges to traditional brokers that added crypto. The rankings below weight crypto availability, AUD deposit options and regulatory standing (AUSTRAC registration) over general share-trading features.',
   'Compare the best crypto trading platforms in Australia. Independent ranking by fees, coin selection, AUD deposits and regulatory status.',
   '{"asx_fee_value": -0.10, "us_fee_value": -0.10, "rating": 0.40, "fx_rate": -0.20}',
   '{}',
   'Australian crypto investors who want a regulated platform with AUD deposits.',
   80),

  ('retirement-income',
   'Best brokers for retirement income portfolios',
   'Retirees drawing income from their portfolio need low-cost execution on dividend stocks, CHESS sponsorship for security, and minimal inactivity fees. The rankings below weight dividend-friendly features and low ongoing costs.',
   'Independent ranking of the best brokers for Australian retirees managing income portfolios. CHESS sponsorship, low brokerage, no inactivity fees.',
   '{"chess_sponsored": 0.30, "asx_fee_value": -0.30, "inactivity_fee": -0.25, "rating": 0.15}',
   ARRAY['chess_sponsored']::text[],
   'Retirees or near-retirees managing a dividend income portfolio.',
   90),

  ('micro-investing',
   'Best micro-investing apps in Australia',
   'Micro-investing platforms let you start with $5–$50 and build gradually. The rankings below weight low minimum deposits and low flat brokerage most heavily — percentage-based brokerage is a tax on small balances.',
   'Compare the best micro-investing apps for Australians. Start investing from $5 with low fees and no minimum balance requirements.',
   '{"min_deposit": -0.40, "asx_fee_value": -0.35, "rating": 0.15, "us_fee_value": -0.10}',
   '{}',
   'Beginners with small amounts who want to start investing with $5–$50.',
   100),

  ('options-trading',
   'Best brokers for options trading in Australia',
   'Options trading in Australia is limited to a handful of platforms. The rankings below weight options availability, ASX options pricing and international options access.',
   'Independent ranking of Australian brokers offering options trading. ASX options, US options, pricing and platform features compared.',
   '{"asx_fee_value": -0.25, "us_fee_value": -0.25, "rating": 0.30, "chess_sponsored": 0.20}',
   '{}',
   'Active traders who want to trade ASX or US options from an Australian account.',
   110),

  ('cfd-trading',
   'Best CFD brokers in Australia (ASIC-regulated)',
   'CFD trading in Australia is regulated by ASIC with leverage caps and negative balance protection. The rankings below weight regulatory status, spreads and platform quality over headline sign-up offers.',
   'Independent ranking of ASIC-regulated CFD brokers in Australia. Spreads, leverage, platform quality and regulatory standing compared.',
   '{"rating": 0.40, "asx_fee_value": -0.20, "us_fee_value": -0.20, "fx_rate": -0.20}',
   '{}',
   'Traders looking for ASIC-regulated CFD platforms with tight spreads.',
   120),

  ('long-term-buy-hold',
   'Best brokers for long-term buy-and-hold investors',
   'Buy-and-hold investors trade infrequently but hold for years. Inactivity fees, custody structure and dividend handling matter more than per-trade brokerage. The rankings below weight CHESS sponsorship, zero inactivity fees and platform reliability over trading costs.',
   'Independent ranking of the best brokers for Australian buy-and-hold investors. CHESS custody, no inactivity fees, dividend handling compared.',
   '{"chess_sponsored": 0.35, "inactivity_fee": -0.30, "asx_fee_value": -0.15, "rating": 0.20}',
   '{}',
   'Investors who buy a handful of stocks or ETFs and hold for 5+ years.',
   130),

  ('high-net-worth',
   'Best brokers for high-net-worth investors ($500k+)',
   'Portfolios above $500k have different priorities: platform stability under large orders, CHESS sponsorship for custody protection, competitive FX on large international transfers, and responsive account management. The rankings below weight these institutional-grade features.',
   'Independent comparison of the best brokers for Australian high-net-worth investors with $500k+ portfolios. Custody, FX rates, execution quality compared.',
   '{"chess_sponsored": 0.30, "fx_rate": -0.25, "asx_fee_value": -0.20, "rating": 0.25}',
   ARRAY['chess_sponsored']::text[],
   'Investors with $500k+ who need CHESS custody and institutional-grade execution.',
   140),

  ('asx-etf-dca',
   'Best brokers for regular ASX ETF investing (DCA)',
   'Dollar-cost averaging into ASX ETFs means you buy small, regular parcels — usually $200–$1,000 per month. Flat brokerage costs per trade eat into returns at these sizes. The rankings below weight low flat ASX brokerage and automatic investment features.',
   'Compare the cheapest brokers for regular ASX ETF purchases. Dollar-cost averaging with low flat brokerage and auto-invest features.',
   '{"asx_fee_value": -0.55, "chess_sponsored": 0.20, "rating": 0.15, "min_deposit": -0.10}',
   '{}',
   'Investors making regular monthly ETF purchases of $200–$1,000.',
   150),

  ('first-time-investor',
   'Best brokers for first-time investors in Australia',
   'Your first broker sets the tone for your entire investing experience. The rankings below weight educational resources, low minimums, simple pricing and platform usability over advanced features that beginners do not need.',
   'Independent ranking of the best brokers for first-time Australian investors. Simple pricing, low minimums, educational tools compared.',
   '{"min_deposit": -0.30, "asx_fee_value": -0.30, "rating": 0.30, "chess_sponsored": 0.10}',
   '{}',
   'Complete beginners opening their first brokerage account.',
   160),

  ('mobile-first',
   'Best mobile trading apps in Australia',
   'Mobile-first investors want to buy, sell and monitor their portfolio from their phone. The rankings below weight mobile app quality, push notification support and one-tap trading features.',
   'Compare the best mobile trading apps for Australian investors. App quality, real-time alerts, biometric login and trade execution from your phone.',
   '{"rating": 0.45, "asx_fee_value": -0.25, "us_fee_value": -0.15, "chess_sponsored": 0.15}',
   '{}',
   'Investors who do 90%+ of their trading on a mobile phone.',
   170),

  ('asx-penny-stocks',
   'Best brokers for ASX penny stocks (sub-$1 shares)',
   'Penny stock traders need flat brokerage (not percentage-based), because a 0.10% commission is meaningless on a $500 trade but a $9.50 flat fee is material. The rankings below weight low flat ASX brokerage and real-time ASX market data.',
   'Independent ranking of the cheapest brokers for ASX penny stocks. Flat brokerage, real-time data and small-cap research compared.',
   '{"asx_fee_value": -0.55, "chess_sponsored": 0.20, "rating": 0.15, "inactivity_fee": -0.10}',
   '{}',
   'Speculative traders buying sub-$1 ASX shares with small position sizes.',
   180),

  ('global-diversification',
   'Best brokers for global diversification from Australia',
   'Diversifying beyond the ASX means accessing US, UK, European and Asian markets. The rankings below weight multi-market access, competitive FX rates and low international brokerage.',
   'Compare brokers for Australian investors who want global market access. US, UK, European and Asian shares from one account.',
   '{"us_fee_value": -0.30, "fx_rate": -0.35, "asx_fee_value": -0.15, "chess_sponsored": 0.20}',
   '{}',
   'Australian investors who want to diversify across multiple global markets.',
   190),

  ('dividend-reinvestment',
   'Best brokers with dividend reinvestment (DRP) support',
   'Dividend reinvestment plans automatically convert your cash dividends into additional shares — compounding returns without paying brokerage. Not all Australian brokers support DRP. The rankings below only consider brokers that offer it.',
   'Compare Australian brokers that support dividend reinvestment plans (DRP). Automatic reinvestment, CHESS sponsorship and brokerage compared.',
   '{"chess_sponsored": 0.30, "asx_fee_value": -0.30, "inactivity_fee": -0.20, "rating": 0.20}',
   '{}',
   'Long-term investors who want automatic dividend reinvestment.',
   200),

  ('share-trading-under-25',
   'Best brokers for investors under 25',
   'Young investors typically start with small amounts, trade via mobile, and do not need advanced features like margin or options. The rankings below weight low minimums, low fees and mobile app quality.',
   'Best share trading platforms for Australians under 25. Low minimums, low fees, great mobile apps — independently ranked.',
   '{"min_deposit": -0.35, "asx_fee_value": -0.30, "rating": 0.25, "us_fee_value": -0.10}',
   '{}',
   'Investors under 25 starting with small amounts and trading mainly via mobile.',
   210),

  ('managed-portfolios',
   'Best managed portfolio platforms in Australia',
   'Managed portfolios (robo-advisors) let you invest without picking individual stocks — you choose a risk level and the platform allocates for you. The rankings below weight management fee, asset allocation quality and minimum investment.',
   'Compare the best robo-advisor and managed portfolio platforms in Australia. Management fees, performance, asset allocation independently ranked.',
   '{"rating": 0.40, "min_deposit": -0.25, "asx_fee_value": -0.15, "fx_rate": -0.20}',
   '{}',
   'Hands-off investors who want professional portfolio management without a financial advisor.',
   220),

  ('smsf-international',
   'Best brokers for SMSF international investing',
   'SMSF trustees who want global diversification need CHESS sponsorship for domestic holdings AND competitive FX rates for international trades. The rankings below weight both — domestic custody safety and international cost efficiency.',
   'Independent ranking of the best brokers for SMSF international investing. CHESS sponsorship plus competitive FX rates and US brokerage.',
   '{"chess_sponsored": 0.30, "smsf_support": 0.25, "us_fee_value": -0.20, "fx_rate": -0.25}',
   ARRAY['smsf_support', 'chess_sponsored']::text[],
   'SMSF trustees who want to invest internationally while maintaining CHESS custody domestically.',
   230),

  ('no-inactivity-fee',
   'Best brokers with no inactivity fees',
   'Several Australian brokers charge $10–$25 per quarter if you do not trade. For buy-and-hold investors, these fees erode returns for doing nothing. The rankings below only consider brokers with zero inactivity fees.',
   'Compare Australian brokers with no inactivity fees. Independent ranking for buy-and-hold investors who do not want to pay for not trading.',
   '{"inactivity_fee": -0.50, "asx_fee_value": -0.20, "chess_sponsored": 0.20, "rating": 0.10}',
   '{}',
   'Buy-and-hold investors who refuse to pay inactivity fees.',
   240),

  ('low-minimum-deposit',
   'Best brokers with low or no minimum deposit',
   'Some Australian brokers require $500–$2,000 to open an account. Others let you start with $0. The rankings below weight minimum deposit requirements most heavily for investors who want to start small.',
   'Compare Australian brokers with the lowest minimum deposit requirements. Start investing from $0 with independent rankings.',
   '{"min_deposit": -0.50, "asx_fee_value": -0.25, "rating": 0.15, "us_fee_value": -0.10}',
   '{}',
   'New investors who want to open an account with little or no upfront capital.',
   250),

  ('forex-trading',
   'Best forex brokers in Australia (ASIC-regulated)',
   'Forex trading in Australia falls under ASIC regulation with leverage caps and negative balance protection. The rankings below weight regulatory standing, AUD pairs spread, and platform quality.',
   'Independent ranking of ASIC-regulated forex brokers in Australia. Spreads, leverage caps, platform quality and regulatory standing compared.',
   '{"rating": 0.40, "fx_rate": -0.30, "us_fee_value": -0.15, "asx_fee_value": -0.15}',
   '{}',
   'Forex traders looking for ASIC-regulated brokers with competitive AUD pair spreads.',
   260),

  ('australian-expat',
   'Best brokers for Australian expats living overseas',
   'Australian expats face a unique problem: many domestic brokers restrict or close accounts when you move abroad. The rankings below weight international access, FX efficiency and willingness to serve non-resident Australians.',
   'Compare brokers that serve Australian expats living overseas. Account portability, FX rates and international access independently ranked.',
   '{"fx_rate": -0.35, "us_fee_value": -0.25, "asx_fee_value": -0.20, "chess_sponsored": 0.20}',
   '{}',
   'Australian citizens or residents who have moved overseas and want to keep their ASX portfolio.',
   270),

  ('ethical-investing',
   'Best ethical and ESG investing platforms in Australia',
   'Ethical investing platforms screen out companies involved in fossil fuels, weapons, gambling or tobacco. The rankings below weight ESG screening capabilities, ethical fund availability and transparent methodology.',
   'Compare ethical and ESG investing platforms in Australia. Independent ranking by screening methodology, fund availability and costs.',
   '{"rating": 0.40, "asx_fee_value": -0.25, "chess_sponsored": 0.20, "min_deposit": -0.15}',
   '{}',
   'Values-driven investors who want to exclude harmful industries from their portfolio.',
   280),

  ('property-shares',
   'Best platforms for investing in property via shares (REITs)',
   'REITs let you invest in Australian commercial property without buying a building. The rankings below weight REIT availability, CHESS sponsorship for custody and low ASX brokerage.',
   'Compare the best platforms for investing in Australian REITs and property shares. CHESS custody, brokerage and REIT availability independently ranked.',
   '{"chess_sponsored": 0.30, "asx_fee_value": -0.35, "rating": 0.20, "inactivity_fee": -0.15}',
   '{}',
   'Investors who want property exposure through ASX-listed REITs rather than direct property.',
   290),

  ('bond-investing',
   'Best platforms for bond investing in Australia',
   'Bond platforms in Australia range from ASX-listed bond ETFs to direct corporate bond marketplaces. The rankings below weight fixed-income access, low brokerage and platform reliability.',
   'Compare the best bond investing platforms in Australia. Bond ETFs, corporate bonds and government bonds independently ranked.',
   '{"asx_fee_value": -0.30, "chess_sponsored": 0.25, "rating": 0.25, "inactivity_fee": -0.20}',
   '{}',
   'Income-focused investors looking for fixed-income exposure through bonds or bond ETFs.',
   300)

ON CONFLICT (slug) DO UPDATE SET
  h1 = EXCLUDED.h1,
  intro = EXCLUDED.intro,
  meta_description = EXCLUDED.meta_description,
  scoring_weights = EXCLUDED.scoring_weights,
  required_attrs = EXCLUDED.required_attrs,
  target_user = EXCLUDED.target_user,
  display_order = EXCLUDED.display_order,
  updated_at = now();
