-- Migration: advisor standing orders — auto-accept rules for the brief
-- marketplace (Standing Orders & Instant Match).
--
-- An adviser defines a rule ("auto-accept SMSF briefs in NSW up to 10
-- credits, max 3/week"); the engine (lib/briefs/standing-orders.ts)
-- claims matching briefs the moment they become acceptable, via the
-- existing acceptBrief() money path (advisor_credit_ledger debit +
-- optimistic lock on advisor_auctions).
--
-- advisor_standing_order_runs is the per-attempt activity log: it powers
-- the portal activity feed, the per-order weekly cap and the per-adviser
-- daily safety cap. One row per attempted auto-accept (accepted or
-- skipped, with reason).
--
-- Execution is gated by the `standing_orders` feature flag (absent /
-- disabled by default → engine is a no-op until founder enables it).
--
-- RLS: ops-style service_role-only policies (matches advisor_winback_sends
-- and the other advisor-portal tables). The portal reads/writes via
-- /api/advisor-auth/standing-orders, which authenticates with
-- requireAdvisorSession() and uses the service-role client — there is no
-- auth.uid() linkage on professionals for legacy advisor sessions, so
-- row-owner policies are not expressible here.
--
-- Rollback:
--   DROP TABLE IF EXISTS public.advisor_standing_order_runs;
--   DROP TABLE IF EXISTS public.advisor_standing_orders;

BEGIN;

CREATE TABLE IF NOT EXISTS public.advisor_standing_orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  professional_id integer NOT NULL REFERENCES public.professionals(id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'paused')),
  -- Auto-resume: a paused rule with paused_until in the past is treated
  -- as active again by the engine (vacation mode).
  paused_until timestamptz,
  -- Filters. Empty array = match any.
  brief_templates text[] NOT NULL DEFAULT '{}',
  states text[] NOT NULL DEFAULT '{}',
  budget_bands text[] NOT NULL DEFAULT '{}',
  -- Skip briefs whose accept cost exceeds this many credits.
  max_credits_per_accept integer NOT NULL DEFAULT 10
    CHECK (max_credits_per_accept >= 1 AND max_credits_per_accept <= 100),
  -- Per-rule cap on auto-accepts in any rolling 7-day window.
  weekly_accept_cap integer NOT NULL DEFAULT 3
    CHECK (weekly_accept_cap >= 1 AND weekly_accept_cap <= 25),
  -- Fairness cursor: candidates are tried least-recently-triggered first.
  last_triggered_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_advisor_standing_orders_active
  ON public.advisor_standing_orders (status, paused_until);
CREATE INDEX IF NOT EXISTS idx_advisor_standing_orders_professional
  ON public.advisor_standing_orders (professional_id);

CREATE TABLE IF NOT EXISTS public.advisor_standing_order_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  standing_order_id bigint REFERENCES public.advisor_standing_orders(id) ON DELETE SET NULL,
  professional_id integer NOT NULL REFERENCES public.professionals(id) ON DELETE CASCADE,
  brief_id integer NOT NULL,
  accepted boolean NOT NULL DEFAULT false,
  -- 'accepted' | 'insufficient_credits' | 'weekly_cap' | 'daily_safety_cap'
  -- | 'already_accepted' | 'error' (free text kept loose for forward-compat)
  reason text NOT NULL,
  credits_spent integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_standing_order_runs_order
  ON public.advisor_standing_order_runs (standing_order_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_standing_order_runs_professional
  ON public.advisor_standing_order_runs (professional_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_standing_order_runs_brief
  ON public.advisor_standing_order_runs (brief_id);

ALTER TABLE public.advisor_standing_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.advisor_standing_order_runs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Service role manages advisor_standing_orders" ON public.advisor_standing_orders;
CREATE POLICY "Service role manages advisor_standing_orders"
  ON public.advisor_standing_orders FOR ALL TO service_role USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Service role manages advisor_standing_order_runs" ON public.advisor_standing_order_runs;
CREATE POLICY "Service role manages advisor_standing_order_runs"
  ON public.advisor_standing_order_runs FOR ALL TO service_role USING (true) WITH CHECK (true);

COMMIT;
