-- Migration: brief_views — the Brief Trust Centre's activity ledger
-- ("who's seen my brief").
--
-- Two honest signals, one row per (brief, adviser, kind):
--   - 'reached': the brief appeared in the adviser's inbox payload
--     (/api/briefs/inbox) — recorded batch insert-or-ignore.
--   - 'viewed':  the adviser opened the brief's full masked details
--     (/api/briefs/[slug]/preview) — first open also triggers the
--     consumer's "an adviser viewed your brief" in-app notification.
--
-- The consumer tracker (/briefs/[slug]) shows aggregate counts only —
-- adviser identities are never exposed pre-acceptance, so the table is
-- ops-only under RLS like the other marketplace ledgers.
--
-- Rollback:
--   DROP TABLE IF EXISTS public.brief_views;

BEGIN;

CREATE TABLE IF NOT EXISTS public.brief_views (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brief_id integer NOT NULL,
  professional_id integer NOT NULL REFERENCES public.professionals(id) ON DELETE CASCADE,
  kind text NOT NULL CHECK (kind IN ('reached', 'viewed')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_brief_views_pair
  ON public.brief_views (brief_id, professional_id, kind);
CREATE INDEX IF NOT EXISTS idx_brief_views_brief
  ON public.brief_views (brief_id, kind);

ALTER TABLE public.brief_views ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Service role manages brief_views" ON public.brief_views;
CREATE POLICY "Service role manages brief_views"
  ON public.brief_views FOR ALL TO service_role USING (true) WITH CHECK (true);

COMMIT;
