-- Migration: lead_tasks + lead_sequences — Adviser Follow-Up Autopilot
-- (idea #14, docs/strategy/RETENTION_MARKETPLACE_MEGA_SESSIONS.md).
--
-- Gives advisers a lightweight CRM on top of their existing portal leads:
--   1. lead_tasks            — per-lead to-dos with a due date (done/overdue).
--   2. lead_sequences        — named follow-up cadences (active|paused).
--   3. lead_sequence_steps   — up to 3 steps per sequence (day offset, subject,
--                              body with allowlisted merge fields).
--   4. lead_sequence_enrolments — a lead enrolled in a sequence; the send
--                              engine (/api/cron/lead-sequence-engine) advances
--                              current_step as each day-offset comes due.
--
-- LEAD KEYING — portal leads live in `public.professional_leads`, keyed by an
--   `integer` primary key `id`, owned by `professional_id integer` (FK to
--   professionals.id). There is NO uuid/text lead reference, so this feature
--   keys tasks and enrolments by that integer. To stay decoupled from the
--   parent row's lifecycle (and because enrolments/tasks are advisor-private
--   bookkeeping, not a hard sub-record of the lead) we store the lead id as a
--   plain `integer lead_ref` and ALSO carry `professional_id` on every row, so
--   the API layer can always scope by (professional_id, lead_ref) — exactly the
--   ownership scoping `professional_leads` updates use today
--   (app/api/advisor-portal/pipeline). lead_ref is intentionally NOT a FK: a
--   purged/anonymised lead leaves an inert enrolment that the engine simply
--   can't resolve a recipient for (it skips), rather than cascading deletes
--   through CRM bookkeeping.
--
-- DORMANCY — every surface is gated behind the `lead_sequences` feature flag
--   (fail-closed: absent/disabled ⇒ no UI, send engine no-ops). These tables
--   are inert until the flag is enabled; nothing here changes existing
--   behaviour.
--
-- RLS — service-role-only, mirroring the established posture for advisor-owned
--   tables whose sessions carry NO Supabase JWT (advisor_sessions,
--   advisor_standing_order_runs, brief_sla_events, respondent_scorecards). All
--   reads/writes go through the service-role admin client from server routes
--   that re-verify the caller's professional_id via requireAdvisorSession()
--   and scope every query by professional_id. An owner RLS policy would be
--   security theatre here — there is no auth.uid() to bind to on a legacy
--   advisor_session cookie — so the API-layer ownership check is the real gate,
--   identical to how professional_leads itself is written.
--
-- Rollback:
--   DROP TABLE IF EXISTS public.lead_sequence_enrolments;
--   DROP TABLE IF EXISTS public.lead_sequence_steps;
--   DROP TABLE IF EXISTS public.lead_sequences;
--   DROP TABLE IF EXISTS public.lead_tasks;
-- All statements are idempotent; re-running is a no-op.

BEGIN;

-- ── 1. Per-lead tasks ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.lead_tasks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  professional_id integer NOT NULL REFERENCES public.professionals(id) ON DELETE CASCADE,
  -- professional_leads.id of the lead this task hangs off. Plain integer, not a
  -- FK (see header). Scoped together with professional_id in every query.
  lead_ref integer NOT NULL,
  title text NOT NULL CHECK (char_length(title) >= 1 AND char_length(title) <= 200),
  due_at timestamptz,
  done_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_lead_tasks_owner_lead
  ON public.lead_tasks (professional_id, lead_ref);
-- Drives the daily "due today / overdue" digest: open tasks (done_at IS NULL)
-- with a due date, ordered by when they're due.
CREATE INDEX IF NOT EXISTS idx_lead_tasks_due
  ON public.lead_tasks (due_at)
  WHERE done_at IS NULL AND due_at IS NOT NULL;

ALTER TABLE public.lead_tasks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Service role manages lead_tasks" ON public.lead_tasks;
CREATE POLICY "Service role manages lead_tasks"
  ON public.lead_tasks FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ── 2. Follow-up sequences ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.lead_sequences (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  professional_id integer NOT NULL REFERENCES public.professionals(id) ON DELETE CASCADE,
  name text NOT NULL CHECK (char_length(name) >= 1 AND char_length(name) <= 120),
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'paused')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_lead_sequences_owner
  ON public.lead_sequences (professional_id, status);

ALTER TABLE public.lead_sequences ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Service role manages lead_sequences" ON public.lead_sequences;
CREATE POLICY "Service role manages lead_sequences"
  ON public.lead_sequences FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ── 3. Sequence steps (≤3 enforced at the API layer) ─────────────────────
CREATE TABLE IF NOT EXISTS public.lead_sequence_steps (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sequence_id bigint NOT NULL REFERENCES public.lead_sequences(id) ON DELETE CASCADE,
  -- Days after enrolment this step fires. 0 = immediately on enrol.
  day_offset integer NOT NULL CHECK (day_offset >= 0 AND day_offset <= 30),
  subject text NOT NULL CHECK (char_length(subject) >= 1 AND char_length(subject) <= 150),
  -- Plain-text body (light formatting only); merge fields resolved against a
  -- safe allowlist at send time. No raw HTML from advisers.
  body text NOT NULL CHECK (char_length(body) >= 1 AND char_length(body) <= 2000),
  -- Ordering within the sequence (0-based). Mirrors day_offset ordering but
  -- kept explicit so two steps can never collide on sort.
  position integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_lead_sequence_steps_sequence
  ON public.lead_sequence_steps (sequence_id, position);

ALTER TABLE public.lead_sequence_steps ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Service role manages lead_sequence_steps" ON public.lead_sequence_steps;
CREATE POLICY "Service role manages lead_sequence_steps"
  ON public.lead_sequence_steps FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ── 4. Enrolments (a lead progressing through a sequence) ─────────────────
CREATE TABLE IF NOT EXISTS public.lead_sequence_enrolments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sequence_id bigint NOT NULL REFERENCES public.lead_sequences(id) ON DELETE CASCADE,
  professional_id integer NOT NULL REFERENCES public.professionals(id) ON DELETE CASCADE,
  -- professional_leads.id of the enrolled lead (plain integer, see header).
  lead_ref integer NOT NULL,
  enrolled_at timestamptz NOT NULL DEFAULT now(),
  -- How many steps have been sent. 0 = nothing sent yet; the engine sends step
  -- at index current_step when its day_offset is due, then increments.
  current_step integer NOT NULL DEFAULT 0,
  completed_at timestamptz,
  stopped_at timestamptz,
  -- Stamped after every send: enforces the ≤1-send-per-lead-per-day hard cap
  -- and makes the engine idempotent across re-runs within a day.
  last_sent_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  -- One live enrolment per (sequence, lead). Re-enrolling the same lead in the
  -- same sequence is a no-op upsert rather than a duplicate cadence.
  UNIQUE (sequence_id, lead_ref)
);

-- The engine's hot path: active enrolments (not completed, not stopped) for a
-- given professional, ordered for due-step evaluation.
CREATE INDEX IF NOT EXISTS idx_lead_sequence_enrolments_active
  ON public.lead_sequence_enrolments (professional_id, last_sent_at)
  WHERE completed_at IS NULL AND stopped_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_lead_sequence_enrolments_sequence
  ON public.lead_sequence_enrolments (sequence_id);

ALTER TABLE public.lead_sequence_enrolments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Service role manages lead_sequence_enrolments" ON public.lead_sequence_enrolments;
CREATE POLICY "Service role manages lead_sequence_enrolments"
  ON public.lead_sequence_enrolments FOR ALL TO service_role USING (true) WITH CHECK (true);

COMMIT;
