-- Migration: Firm Lead-Ops — routing policies + assignment audit trail +
-- per-seat billing scaffolding (mega-session idea #13).
--
-- Adds firm-level lead-distribution operations on top of the existing
-- advisor_firms / invitations machinery (which today only supports a manual
-- assignment dropdown). Three additive surfaces:
--
--   1. advisor_firms.routing_policy (jsonb) — how incoming leads for a firm
--      member are distributed across the firm. Shape:
--        {
--          "mode": "manual" | "round_robin" | "load_balanced" | "specialty",
--          "specialty_map"?: { "<advisor_type|need_slug>": <professional_id>, ... }
--        }
--      Default '{}' is treated by lib/firm-routing.ts as mode:"manual"
--      (today's behaviour — no auto-assignment), so existing firms are
--      untouched until an admin opts in AND the `firm_routing` flag is on.
--
--   2. advisor_firms.stripe_subscription_id (text) + advisor_firms.billed_seats
--      (int) — the per-seat SaaS subscription (flat B2B fee, lean lane).
--      Written ONLY by the Stripe webhook seat-sync branch, and ONLY when the
--      `firm_seat_billing` flag + Stripe env config exist. Dormant otherwise.
--
--   3. lead_assignments — the assignment audit trail. One row per
--      auto-assignment OR manual reassignment, capturing who a lead went to,
--      by which mechanism, and (for reassignments) who it was taken from.
--      Powers the manager console's audit list. lead_ref is a text reference
--      (the professional_leads.id as text) so the table is decoupled from the
--      leads table's int PK and can also reference brief-derived leads later.
--
-- RLS: lead_assignments is service_role-only, matching the surrounding
-- firm-table posture (advisor_firms write policies, firm_seat_requests,
-- advisor_standing_orders). The portal reads/writes via
-- /api/advisor-portal/firm-routing + /firm-leads, which authenticate with
-- requireAdvisorSession() + is_firm_admin and use the service-role client —
-- legacy advisor sessions have no auth.uid() linkage to professionals, so
-- row-owner policies are not expressible here.
--
-- Idempotent: ADD COLUMN IF NOT EXISTS + CREATE TABLE/INDEX/POLICY IF NOT
-- EXISTS (policies via DROP POLICY IF EXISTS then CREATE). Safe to re-run.
--
-- Rollback:
--   DROP TABLE IF EXISTS public.lead_assignments;
--   ALTER TABLE public.advisor_firms DROP COLUMN IF EXISTS routing_policy;
--   ALTER TABLE public.advisor_firms DROP COLUMN IF EXISTS stripe_subscription_id;
--   ALTER TABLE public.advisor_firms DROP COLUMN IF EXISTS billed_seats;

BEGIN;

-- ── advisor_firms: routing policy + per-seat billing columns ──────────────
ALTER TABLE public.advisor_firms
  ADD COLUMN IF NOT EXISTS routing_policy jsonb NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE public.advisor_firms
  ADD COLUMN IF NOT EXISTS stripe_subscription_id text;

ALTER TABLE public.advisor_firms
  ADD COLUMN IF NOT EXISTS billed_seats integer;

-- ── lead_assignments: assignment audit trail ─────────────────────────────
CREATE TABLE IF NOT EXISTS public.lead_assignments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  firm_id integer NOT NULL REFERENCES public.advisor_firms(id) ON DELETE CASCADE,
  -- The lead this assignment is for. Text ref (professional_leads.id as text)
  -- to stay decoupled from the leads table PK type.
  lead_ref text NOT NULL,
  -- The firm member the lead was assigned to.
  professional_id integer NOT NULL REFERENCES public.professionals(id) ON DELETE CASCADE,
  -- How the assignment was made. 'manual' = admin dropdown / reassign;
  -- the other three = automatic distribution by lib/firm-routing.ts.
  assigned_by text NOT NULL
    CHECK (assigned_by IN ('manual', 'round_robin', 'load_balanced', 'specialty')),
  assigned_at timestamptz NOT NULL DEFAULT now(),
  -- For a reassignment, the professional_id the lead was taken away from.
  -- NULL for a first (auto) assignment.
  reassigned_from integer
);

CREATE INDEX IF NOT EXISTS idx_lead_assignments_firm
  ON public.lead_assignments (firm_id, assigned_at DESC);
CREATE INDEX IF NOT EXISTS idx_lead_assignments_professional
  ON public.lead_assignments (professional_id, assigned_at DESC);
-- Fairness cursor for round-robin: "who was assigned least recently in this
-- firm" reads (firm_id, professional_id, assigned_at).
CREATE INDEX IF NOT EXISTS idx_lead_assignments_firm_pro_recency
  ON public.lead_assignments (firm_id, professional_id, assigned_at DESC);
CREATE INDEX IF NOT EXISTS idx_lead_assignments_lead_ref
  ON public.lead_assignments (firm_id, lead_ref);

ALTER TABLE public.lead_assignments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Service role manages lead_assignments" ON public.lead_assignments;
CREATE POLICY "Service role manages lead_assignments"
  ON public.lead_assignments FOR ALL TO service_role USING (true) WITH CHECK (true);

COMMIT;
