-- ============================================================
-- Seed 12 hydrogen editorial articles.
-- Idempotent: ON CONFLICT (slug) DO NOTHING.
-- ============================================================

INSERT INTO public.articles (
  title, slug, excerpt, category, content_type,
  sections, tags, read_time, evergreen, published_at,
  related_verticals, related_advisor_types, status,
  author_name, author_title
) VALUES

(
  'Fortescue (FMG): How the Iron Ore Major''s Hydrogen Story Changed',
  'fortescue-fmg-hydrogen-thesis-update',
  'FFI promised to become a green hydrogen supermajor. Then reality intervened. What Fortescue''s retreat means for ASX hydrogen investors.',
  'hydrogen', 'analysis',
  $json$[
    {"heading":"The original ambition","body":"In 2021 Fortescue Metals Group (ASX: FMG), through its Fortescue Future Industries (FFI) subsidiary, committed to producing 15 million tonnes of green hydrogen annually by 2030 and spending US$6.2B on the transition. That positioned FMG as the single largest listed hydrogen play on the ASX and a credible challenger to fossil majors in the energy transition.\n\nThe announcement reshaped how investors thought about the company. FMG traded with a ''hydrogen premium'' for parts of 2022 as market participants priced in optionality on transition cashflows."},
    {"heading":"The 2024 reset","body":"In 2024 Fortescue materially scaled back the hydrogen ambition. The 15Mt-per-year target was quietly dropped. Layoffs reduced FFI headcount by roughly 700 positions. Reasons cited: cost inflation on green hydrogen projects, electrolyser supply-chain constraints, lower-than-expected off-take pricing, and competing capital needs within the iron ore business.\n\nCapital allocation pivoted back toward iron ore decarbonisation (Christmas Creek green iron) and away from standalone hydrogen export."},
    {"heading":"What remains","body":"FMG retains meaningful green hydrogen exposure: the Gibson Island ammonia conversion project with Incitec Pivot remains live; the Holmaneset project in Norway; select US and European investigations. But the company is no longer positioning itself as a pure-play transition leader.\n\nFor investors, the practical read is: FMG''s hydrogen today is optionality on top of an iron ore dividend engine, not a separate investment case."},
    {"heading":"What this means for the sector","body":"If a company with FMG''s balance sheet (A$55B market cap, strong dividend generation) struggled to make green hydrogen economics work, it says something about the broader sector. Green hydrogen costs need to fall further, off-take pricing needs to rise, or policy support needs to increase — likely all three.\n\nThe 2024 cost-reality check is healthy for ASX hydrogen investors. It clarifies which ASX pure-plays have genuine paths to FID (typically those aligned with Hydrogen Headstart Production Credit or major off-takers) and which are priced on narrative alone."},
    {"heading":"Investor positioning","body":"FMG remains a reasonable top-of-portfolio holding for Australian dividend investors. At the current size the hydrogen exposure is a fraction of 1% of earnings — you are fundamentally buying an iron ore business with unusually active capital allocation.\n\nFor dedicated hydrogen exposure, smaller ASX pure-plays (Hazer, Province, Frontier) are higher-beta alternatives. None has FMG''s balance sheet or cash-flow visibility. An energy-focused financial planner can help blend the right mix given your risk tolerance."},
    {"heading":"What to watch","body":"Three signals for FMG''s hydrogen thesis: (1) Gibson Island ammonia project FID decision expected late-2020s, (2) any re-escalation of FFI capex, (3) government Hydrogen Headstart Production Credit awards for projects involving FMG.\n\nFor the broader sector: watch green hydrogen LCOE studies and off-take contract signings. Until LCOE falls below US$4/kg reliably and long-term off-take contracts clear US$5/kg, most Australian green hydrogen projects remain policy-dependent."}
  ]$json$::jsonb,
  $json$["Fortescue","FMG","hydrogen","green hydrogen","FFI","ASX"]$json$::jsonb,
  7, true, NOW(),
  ARRAY['hydrogen','oil-gas'], ARRAY['energy_financial_planner','resources_fund_manager']::text[],
  'published','Market Research Team','Invest.com.au'
),

(
  'Hazer Group (HZR): Methane Pyrolysis — the Unloved Hydrogen Pathway',
  'hazer-group-hzr-methane-pyrolysis',
  'While everyone argued about electrolysers, Hazer built a commercial demonstration plant for methane-pyrolysis hydrogen. It works. It''s also speculative.',
  'hydrogen', 'guide',
  $json$[
    {"heading":"What methane pyrolysis actually is","body":"Most hydrogen investment conversation focuses on electrolysis — splitting water with electricity. Hazer Group (ASX: HZR) has taken a different route: thermal decomposition of methane into hydrogen gas and solid graphitic carbon.\n\nReaction: CH4 → H2 + C(solid). The output is hydrogen plus a solid carbon by-product — no CO2 emissions, no water, no gigawatts of electricity required. It''s hydrogen production with a fundamentally different input and output profile from electrolysis."},
    {"heading":"Why it matters","body":"Two specific features make methane pyrolysis investable. First, the energy input requirement is roughly half that of electrolysis per kg of hydrogen produced. Second, the carbon by-product has market value — graphitic carbon used in battery anodes, carbon black for tyres and polymers, and potentially electrode carbons for aluminium smelting.\n\nIf Hazer''s unit economics hold at commercial scale, the effective hydrogen cost is significantly subsidised by by-product revenue. This is the pitch."},
    {"heading":"The commercial demonstration","body":"Hazer''s Commercial Demonstration Plant (CDP) in Kwinana, WA, is operational. It produces small quantities of hydrogen and solid graphitic carbon at demonstration scale. Data from the CDP is essential for future commercial-scale FID decisions.\n\nOperating experience at the CDP is the single most important milestone. Positive performance metrics — yield, purity, graphitic carbon quality — support the case for scale-up. Disappointing results would materially impair the investment thesis."},
    {"heading":"Commercial pipeline","body":"Hazer has signed MoUs and licensing agreements with potential commercial partners — including a US arm Hazer North America — to deploy the technology at scale. No commercial-scale FID has been announced as of mid-2026.\n\nCommercial-scale projects require off-take for both hydrogen and graphitic carbon. Marketing carbon black or battery anode-grade carbon is a specialist business; Hazer needs partners with carbon-market access."},
    {"heading":"Risks","body":"Scale-up risk is the dominant variable. Lab-scale and demonstration-scale technologies frequently encounter new challenges at commercial scale — catalyst performance, heat management, product purity consistency. Hazer''s CDP is valuable because it de-risks some of this, but not all.\n\nCarbon by-product market risk is a second factor. If battery-grade anode carbon prices collapse (for example from Chinese supply), Hazer''s unit economics degrade materially.\n\nFunding risk is real. Hazer is a small-cap with limited cashflow; commercial scale-up will require equity or debt that current shareholders will partially absorb through dilution."},
    {"heading":"Investor fit","body":"Hazer fits speculative-end allocations in hydrogen portfolios. Small position sizing (under 1% of portfolio) for exposure to technology optionality that''s distinct from the mainstream electrolysis thesis.\n\nIt does NOT fit: core hydrogen exposure (too early for that), income portfolios (no dividends), or ESG-constrained mandates that exclude natural-gas-derived hydrogen (methane is the feedstock). A resources fund manager can size Hazer against your overall hydrogen allocation."}
  ]$json$::jsonb,
  $json$["Hazer","HZR","methane pyrolysis","hydrogen","carbon black","ASX"]$json$::jsonb,
  7, true, NOW(),
  ARRAY['hydrogen'], ARRAY['resources_fund_manager']::text[],
  'published','Market Research Team','Invest.com.au'
),

(
  'Green vs Blue vs Turquoise Hydrogen: The Colour Taxonomy Investors Need',
  'hydrogen-colour-taxonomy-green-blue-turquoise',
  'Eight colours, three that matter for investors. How to read an ASX hydrogen prospectus without being misled by marketing.',
  'hydrogen', 'guide',
  $json$[
    {"heading":"The full colour set","body":"Hydrogen marketing uses a colour taxonomy that describes how the hydrogen is produced. Green, blue, turquoise, grey, brown, black, pink, yellow — the list goes on. For investor purposes three colours dominate investment decisions: green, blue, and turquoise. The rest are largely labels for hydrogen that is already produced industrially today."},
    {"heading":"Green hydrogen","body":"Green hydrogen is produced by electrolysis of water using renewable electricity. 2H2O + electricity → 2H2 + O2. The attraction is zero direct CO2 emissions provided the electricity source is genuinely renewable.\n\nGreen hydrogen is the policy-favoured pathway — the Hydrogen Headstart Production Credit targets green hydrogen specifically. Most ASX-listed pure-play developers (Province, Frontier, Hazer Energy projects) are green-focused.\n\nThe economics depend fundamentally on electricity cost. Green hydrogen at US$4-5/kg requires renewable electricity at US$20-30/MWh consistently — achievable in Australia''s best renewable zones (Pilbara, Broken Hill, Mid-West WA) but not universally."},
    {"heading":"Blue hydrogen","body":"Blue hydrogen is produced from natural gas via steam methane reforming (SMR) or autothermal reforming (ATR), with the CO2 captured and stored permanently. Production is cheaper than green hydrogen today — US$2-3/kg in many locations — but requires credible carbon-capture-and-storage (CCS) at commercial scale.\n\nASX blue hydrogen exposure is indirect. Santos''s Moomba CCS hub and Woodside''s planned capture facilities could support blue hydrogen production. Pure Hydrogen (ASX: PH2) has blue hydrogen in its portfolio mix.\n\nCritics argue blue hydrogen''s emissions profile depends heavily on upstream methane leakage rates and CCS permanence. For investors, blue hydrogen is economically stronger than green today but policy-vulnerable."},
    {"heading":"Turquoise hydrogen","body":"Turquoise hydrogen is produced from natural gas via methane pyrolysis — the thermal decomposition pathway Hazer Group uses. CH4 → H2 + C(solid). No CO2 emissions, solid carbon by-product.\n\nTurquoise hydrogen is the most ''interesting'' investable category: lower capex than electrolysis, by-product revenue, natural gas feedstock already widely available. Hazer is the ASX pure-play exposure. Pure Hydrogen has some turquoise-pathway exposure.\n\nTurquoise is less mature commercially than either green or blue. Scale-up risk is material."},
    {"heading":"The colours that don''t really matter for investors","body":"Grey hydrogen (SMR without CCS, today''s industrial default), brown/black (coal-derived), yellow (mixed grid electricity), pink (nuclear-powered electrolysis) — these are mostly semantic categories describing hydrogen that already exists or is aspirational.\n\nGrey hydrogen is ~95% of global production today and trades in industrial commodity markets. It is not typically a retail-investable exposure. Pink hydrogen is theoretical in Australia given the domestic nuclear ban."},
    {"heading":"What to read in a prospectus","body":"When evaluating an ASX hydrogen pure-play, three questions matter: (1) What colour is the hydrogen — green, blue, or turquoise? (2) What is the LCOE/LCOH target at commercial scale, and under what assumptions? (3) What is the off-take path — contracted, in negotiation, or aspirational?\n\nMarketing materials emphasise the colour and the end-state LCOH. The off-take question is where investment case quality separates. A project with signed multi-decade off-take at pricing that covers CAPEX + OPEX + return is fundamentally different from a project that assumes the off-take market will exist at an attractive price point."}
  ]$json$::jsonb,
  $json$["hydrogen","green hydrogen","blue hydrogen","turquoise hydrogen","LCOH","ASX"]$json$::jsonb,
  7, true, NOW(),
  ARRAY['hydrogen'], ARRAY['resources_fund_manager','energy_financial_planner']::text[],
  'published','Market Research Team','Invest.com.au'
),

(
  'The Hydrogen Headstart Production Credit: $2B Policy Underwriting',
  'hydrogen-headstart-production-credit-explained',
  'Hydrogen Headstart is the Australian policy instrument that turns green hydrogen from uninvestable to investable. Here''s how it works.',
  'hydrogen', 'guide',
  $json$[
    {"heading":"Why the policy exists","body":"Green hydrogen at current electrolyser cost and renewable electricity prices typically produces at US$4-6/kg LCOH in favourable Australian locations. Most off-take markets (ammonia export, steel reduction, transport) can sustainably pay US$2-3/kg at scale.\n\nThe gap between production cost and willingness-to-pay is what makes green hydrogen unprofitable today. The Hydrogen Headstart Production Credit exists to close that gap, specifically for projects in the strategic ''first-mover'' category that enable Australia to build scale, supply chain, and off-take relationships."},
    {"heading":"How the scheme works","body":"Hydrogen Headstart allocates A$2 billion in competitive production-credit funding. Successful projects receive a fixed dollar-per-kilogram payment for 10 years of production, calibrated to top-up off-take pricing to an economic return.\n\nThe credit is paid per kg of actual hydrogen produced — not per kg of capacity, and not up-front. This is important: it rewards real production, not announcements. Projects that fail to reach FID or commissioning don''t receive support.\n\nThe scheme was competitively allocated through 2024-25 with shortlisted projects identified. Further tranches are possible as policy priorities evolve."},
    {"heading":"Complementary state programs","body":"Commonwealth Hydrogen Headstart is paired with state-level programs. Queensland Hydrogen Industry Strategy, WA Renewable Hydrogen Strategy, SA Hydrogen Jobs Plan, and Tasmania''s renewable hydrogen commitments all provide state-level support — site allocation, tax concessions, grid-connection prioritisation.\n\nProjects typically stack Commonwealth and state support. A single green hydrogen project might receive Hydrogen Headstart production credit, state-level tax holidays, and accelerated grid connection — all reducing the effective production cost to off-takers."},
    {"heading":"Who benefits on the ASX","body":"ASX-listed pure-plays pitching into Hydrogen Headstart include Province Resources (HyEnergy project), Frontier Energy (Waroona project), and various unlisted project consortia backed in part by ASX-listed parents. Fortescue''s Gibson Island project participated in earlier rounds.\n\nFor retail investors, the practical test is: is a given ASX hydrogen developer''s project eligible for Hydrogen Headstart support? Eligibility materially re-rates project economics; non-eligibility does not."},
    {"heading":"Policy risk","body":"Production credits are conditional on the scheme continuing. A future federal government could reduce, redirect, or cancel the scheme. The 2025-26 budget cycle reaffirmed commitment but long-term durability is assumption, not certainty.\n\nHistorical comparables suggest production credits survive government changes more reliably than grants — they reward private capital taking real risk. But hydrogen is a policy-intensive sector and investors should budget policy-risk alongside project-execution risk."},
    {"heading":"How to factor it into investment decisions","body":"For an ASX hydrogen developer, three questions: (1) Is the project shortlisted or has it been awarded Hydrogen Headstart? (2) What is the awarded or anticipated dollar-per-kg credit? (3) What is the off-take pricing that the credit tops up to?\n\nA credit-supported project with committed off-take at an economic price is materially de-risked. A project pitching at Hydrogen Headstart but not yet selected is speculating on award probability. A project with neither is pre-investment-case.\n\nSpecialist resources fund managers and energy financial planners track the scheme closely — for meaningful allocations, their insight is worth engaging."}
  ]$json$::jsonb,
  $json$["Hydrogen Headstart","production credit","green hydrogen","policy","Australia"]$json$::jsonb,
  7, true, NOW(),
  ARRAY['hydrogen'], ARRAY['resources_fund_manager','energy_financial_planner']::text[],
  'published','Market Research Team','Invest.com.au'
),

(
  'Ammonia Export: Why Japan and Korea Matter for Australian Hydrogen',
  'ammonia-export-japan-korea-hydrogen',
  'Nobody is shipping liquid hydrogen across the Pacific. Everyone is shipping ammonia. Here''s why that matters for ASX investment decisions.',
  'hydrogen', 'analysis',
  $json$[
    {"heading":"The shipping problem","body":"Hydrogen gas has extraordinarily low energy density — around 0.089 kg/m³ at standard conditions. Liquefying it requires cooling to -253°C and consumes 30%+ of the hydrogen''s energy content just in the liquefaction process. This makes pure-hydrogen shipping economically marginal over long distances.\n\nEvery Australian hydrogen export project — without exception — plans to convert hydrogen to an energy-dense carrier before shipping. The dominant carrier is ammonia (NH3). Some projects propose methylcyclohexane (MCH) or synthetic natural gas routes, but ammonia is the default."},
    {"heading":"Why ammonia","body":"Ammonia has three practical advantages as a hydrogen carrier. First, shipping infrastructure already exists — ammonia has been shipped internationally for decades as an agricultural feedstock (urea, fertiliser). Port terminals, vessels, and handling standards are established.\n\nSecond, ammonia is storable as liquid at modest refrigeration temperatures (-33°C) without extreme cryogenics. Third, ammonia can be directly combusted in modified coal-fired power stations or co-fired in gas turbines — no need to reconvert to hydrogen for many end-uses.\n\nThe downside is that converting hydrogen to ammonia via the Haber-Bosch process consumes roughly 10% of the hydrogen''s energy content and requires its own capital equipment."},
    {"heading":"Japan and Korea as anchor off-takers","body":"Both Japan and Korea have firm decarbonisation commitments and limited domestic renewables for cost-effective green hydrogen production. Both have signed strategic supply agreements with Australian project consortia — including Jera, Kepco, Marubeni, and Mitsubishi.\n\nThe anchor off-take pricing is emerging around US$7-10/kg hydrogen-equivalent for initial shipments through 2028-2030, reflecting first-mover cost structures. Over time, scale economies and electrolyser cost reductions are expected to bring pricing into the US$4-6/kg range — the level that makes green hydrogen sustainable without long-term policy subsidy."},
    {"heading":"What this means for ASX project selection","body":"ASX-listed hydrogen developers with Japanese or Korean off-take MoUs or binding contracts have a more credible path to FID than those without. Fortescue''s pre-scale-back Gibson Island included an Incitec Pivot ammonia off-take — practically equivalent to Japanese ammonia demand. Woodside''s H2Perth targets hydrogen for local use and potential ammonia export. Origin''s Hunter Valley partnership with Orica has similar logic.\n\nSmaller pure-plays typically have letters-of-intent rather than binding off-takes, which is appropriate for pre-FID projects but should be read as intent rather than commitment."},
    {"heading":"The ammonia co-firing thesis","body":"Japanese utilities, including Jera, have committed to co-firing ammonia in existing coal-fired power stations. Initially 20% ammonia by energy content; ambitions to reach 50% by 2030. This creates structural, high-volume demand for ammonia imports.\n\nFor Australian green hydrogen producers this is the critical demand anchor. Without firm Japanese and Korean off-take, large-scale Australian green hydrogen has no clear first market."},
    {"heading":"Investor takeaway","body":"When evaluating an ASX hydrogen developer, read the off-take section of the prospectus carefully. ''MoU with major Japanese utility'' is weaker than ''binding off-take with Jera''. Dollar-per-kg pricing bands should be disclosed; if the prospectus talks about ''commercial terms to be agreed'' it''s early.\n\nSpecialist foreign-investment lawyers and energy-focused financial planners track these off-take relationships closely. For concentrated hydrogen-sector allocations, professional advice pays for itself."}
  ]$json$::jsonb,
  $json$["hydrogen","ammonia","Japan","Korea","export","co-firing","Jera"]$json$::jsonb,
  7, true, NOW(),
  ARRAY['hydrogen'], ARRAY['foreign_investment_lawyer','resources_fund_manager']::text[],
  'published','Market Research Team','Invest.com.au'
),

(
  'ASX Hydrogen ETF (HGEN): What It Holds and Doesn''t Hold',
  'hgen-hydrogen-etf-asx-explained',
  'One-ticket global hydrogen exposure. Plug Power, Bloom Energy, Linde — what''s inside and what''s missing.',
  'hydrogen', 'guide',
  $json$[
    {"heading":"What HGEN is","body":"Global X Hydrogen ETF (ASX: HGEN) is the primary ASX-listed wrapper for diversified hydrogen exposure. It tracks the Solactive Global Hydrogen v2 Index — approximately 25-30 holdings globally across electrolyser manufacturers, fuel cell producers, industrial gas majors (Linde, Air Liquide), and hydrogen project developers.\n\nMER is approximately 0.69% — consistent with Global X''s other niche thematic ETFs. Currency exposure is USD-dominated and unhedged; AUD depreciation against USD amplifies returns (and the reverse)."},
    {"heading":"Top holdings","body":"Typical top holdings include Plug Power (US electrolyser + fuel cell), Bloom Energy (US solid oxide fuel cells), Linde (global industrial gases — dominant current hydrogen producer), Air Products (similar), Cummins (engines and fuel cells via the Accelera division), Nel ASA (Norwegian electrolyser maker), ITM Power (UK electrolyser), Ceres Power (UK fuel cell).\n\nAustralian names (FMG, Origin, Hazer) appear at small weights because the index uses market-cap-adjusted methodology. Hydrogen-exposed majors are more heavily weighted than pure-plays in absolute terms."},
    {"heading":"What''s not in HGEN","body":"HGEN is an equity-only vehicle — it does not hold physical hydrogen or hydrogen forward contracts. There is no investable ''hydrogen price'' the way there is for oil or uranium. This is a structural feature of the market.\n\nHGEN is also not a pure-play Australian hydrogen ETF. Australian exposure is <10% of typical holdings. If you want concentrated Australian hydrogen exposure, individual stock selection (Hazer, Province, Frontier) supplements HGEN''s global tilt."},
    {"heading":"How it has performed","body":"HGEN and global hydrogen equity indices broadly have experienced extreme volatility since 2020. The 2020-21 hydrogen hype cycle drove many component stocks to 10-20x valuations relative to revenue; subsequent de-rating has been severe. Through 2024-25 the sector has been consolidating at lower multiples.\n\nThis is typical of early-stage thematic investment. Retail investors should not size HGEN on the assumption the 2020-21 returns are repeatable. A more realistic expectation is mid-single-digit returns over multi-year horizons with significant volatility."},
    {"heading":"Fit in a portfolio","body":"HGEN fits investors wanting thematic exposure to the global energy transition without picking individual pure-plays. A 1-3% allocation within a broader equity portfolio captures the sector without over-exposing to volatility.\n\nFor dedicated hydrogen believers, pairing HGEN with 1-2 ASX pure-plays (Hazer for methane pyrolysis optionality, Province or Frontier for Australian green hydrogen) creates diversified sector exposure."},
    {"heading":"SMSF considerations","body":"HGEN is conventional ASX-listed and suitable for SMSF holdings without special treatment. Record-keeping is straightforward. Distributions (typically annual, low yield given most holdings are reinvesting-phase companies) are handled through standard brokerage reporting.\n\nThematic ETF allocations inside SMSFs should still satisfy the investment strategy and sole-purpose test. For SMSFs concentrated in hydrogen exposure beyond 5% of assets, a specialist SMSF accountant should review alignment with the fund''s documented strategy."}
  ]$json$::jsonb,
  $json$["HGEN","hydrogen ETF","Global X","ASX","thematic"]$json$::jsonb,
  6, true, NOW(),
  ARRAY['hydrogen'], ARRAY['energy_financial_planner','smsf_accountant']::text[],
  'published','Market Research Team','Invest.com.au'
),

(
  'PEM vs Alkaline vs Solid Oxide Electrolysers: The Technology Race',
  'pem-alkaline-solid-oxide-electrolyser-race',
  'Every ASX green hydrogen developer chooses an electrolyser technology. The choice changes project economics, timeline, and risk.',
  'hydrogen', 'guide',
  $json$[
    {"heading":"Three main electrolyser types","body":"Green hydrogen production requires an electrolyser — the equipment that splits water into hydrogen and oxygen using electricity. Three commercial categories dominate: proton exchange membrane (PEM), alkaline (AEL), and solid oxide (SOEC).\n\nEach has different capital cost, operating characteristics, and maturity. Understanding the trade-offs helps read project prospectuses critically."},
    {"heading":"Alkaline electrolysers","body":"Alkaline is the oldest commercially-proven technology — 100+ years of industrial history. Uses a liquid alkaline electrolyte (typically potassium hydroxide). Capital cost is the lowest of the three technologies today: approximately US$600-900/kW at scale.\n\nTrade-off: alkaline electrolysers respond slowly to variable renewable input. They prefer steady electricity supply and can''t cycle on-off efficiently. This matters because most green hydrogen projects couple with solar or wind — intermittent sources. Steady baseload-style electricity supply is more expensive than variable supply."},
    {"heading":"PEM electrolysers","body":"Proton exchange membrane (PEM) electrolysers use a solid polymer membrane. Capital cost is higher than alkaline: approximately US$1,000-1,500/kW at scale. Response to variable input is rapid — PEM can cycle on-off and follow renewable generation profiles well.\n\nPEM is the preferred technology for projects coupling directly with solar or wind without battery or grid buffering. Trade-off is cost and some concerns about precious-metal (iridium) dependence for catalysts."},
    {"heading":"Solid oxide electrolysers","body":"Solid oxide electrolyser cell (SOEC) technology operates at very high temperatures (700-900°C). Benefits: highest efficiency of the three technologies (80%+), and can co-electrolyse water and CO2 to produce syngas directly.\n\nSOEC is the least commercially mature — scaled demonstration plants exist but commercial-scale deployment is rare. Lifetime and degradation are less well-characterised than PEM or alkaline. Capital cost is high and uncertain. Most ASX developers do not use SOEC currently."},
    {"heading":"How this shapes project economics","body":"A project pitching alkaline electrolysers with guaranteed firmed electricity supply (from a grid connection or co-located battery) has the lowest capex. A project pitching PEM with variable renewable input has higher capex but potentially lower electricity cost. Both are credible business models — the choice is about matching technology to the electricity supply profile.\n\nA project pitching SOEC at commercial scale today is making a more speculative technology bet. Not wrong, but the prospectus should explain why SOEC specifically."},
    {"heading":"What to watch in an ASX hydrogen prospectus","body":"Electrolyser selection is usually disclosed. The key questions: (1) What technology? (2) Where is it manufactured? (3) Is there a supply contract or just a preferred vendor? (4) What electricity supply model — fixed price, spot, co-located renewables?\n\nSupply chain matters particularly. Western electrolyser capacity is constrained; Chinese electrolyser capacity is larger but creates geopolitical and warranty complications. A project with a signed electrolyser supply agreement from a Tier 1 supplier is more FID-ready than one relying on aspirational procurement."}
  ]$json$::jsonb,
  $json$["electrolyser","PEM","alkaline","SOEC","green hydrogen","technology"]$json$::jsonb,
  7, true, NOW(),
  ARRAY['hydrogen'], ARRAY['resources_fund_manager']::text[],
  'published','Market Research Team','Invest.com.au'
),

(
  'Why So Many Hydrogen Project FIDs Haven''t Happened (Yet)',
  'hydrogen-project-fid-delays-australia',
  'Announcements have outpaced investment decisions by roughly 10-to-1. Here''s why — and what has to change for FIDs to accelerate.',
  'hydrogen', 'analysis',
  $json$[
    {"heading":"The announcement-to-FID gap","body":"Through 2020-23 Australia saw dozens of green hydrogen project announcements — multi-gigawatt ambitions from FMG, Woodside, Origin, BP, Shell, and a deep bench of pure-play developers. By mid-2026 the number of projects that have reached Final Investment Decision (FID) remains in single digits.\n\nThe gap is striking. It has caused some investors to write off the sector entirely. That''s probably the wrong conclusion — but understanding why FIDs have lagged is essential to sizing exposure appropriately."},
    {"heading":"Cost uncertainty","body":"Green hydrogen LCOH depends on three variable cost components: electrolyser capex, renewable electricity price, and operating factors (water, maintenance, land). Each of these was projected aggressively downward in 2020-21 forecasts.\n\nElectrolyser capex has come down but not at the pace projected. Renewable electricity LCOE has been stickier — particularly once you include firming costs. Operating factors have been largely as expected.\n\nThe net effect: projected LCOH numbers that looked compelling in 2021 now appear optimistic. Developers facing FID have had to revise cost bases upward or renegotiate off-take — or both."},
    {"heading":"Off-take uncertainty","body":"First-mover Japanese and Korean utility ammonia off-takers have signed MoUs but many have delayed binding contracts pending firmed project economics. Steel and heavy-transport end-users have similarly been cautious — understandable given the stakes.\n\nThis creates a chicken-and-egg problem. Projects want firmed off-take to FID. Off-takers want firmed project pricing to commit. The Hydrogen Headstart Production Credit is designed partly to break this deadlock by offering a policy-backed production subsidy that reduces off-take pricing risk."},
    {"heading":"Financing","body":"Green hydrogen project capex typically runs US$5-10B for commercial-scale projects (500MW-1GW). Financing requires debt, equity, and often export-credit agency support. Debt markets require firmed off-take and firmed construction cost. Equity markets require visibility to dividend or capital return.\n\nLenders and equity investors have become more demanding through 2023-25. Projects that might have cleared on ambition-plus-MoU in 2021 now need off-take + capex commitment + operating experience before financing closes. This is healthy but slows FIDs."},
    {"heading":"What has to change","body":"Three things would accelerate ASX hydrogen FIDs: (1) sustained Hydrogen Headstart Production Credit awards at scale (already underway), (2) one or two successful first-mover FIDs that prove out the financing and off-take model, and (3) further electrolyser cost reduction, particularly in Western supply chains.\n\nThe sector is probably 12-36 months away from the first meaningful ASX pure-play FID. From there the pace should accelerate meaningfully."},
    {"heading":"Implications for investors","body":"Sizing matters. ASX hydrogen is a sector where narrative dominance leads to overvaluation in positive news cycles and underweighting in negative cycles. Patient sizing — 1-3% of a broader portfolio — captures upside if FIDs materialise without risking outsized damage if they don''t.\n\nPair exposure works well: a global hydrogen ETF (HGEN) plus 1-2 ASX pure-plays with specific technology or policy positioning. A specialist energy financial planner can help calibrate this against your risk tolerance and time horizon."}
  ]$json$::jsonb,
  $json$["hydrogen","FID","project delays","green hydrogen","Australia"]$json$::jsonb,
  7, true, NOW(),
  ARRAY['hydrogen'], ARRAY['energy_financial_planner','resources_fund_manager']::text[],
  'published','Market Research Team','Invest.com.au'
),

(
  'FIRB and Hydrogen: Critical-Infrastructure Overlap for Foreign Investors',
  'firb-hydrogen-foreign-investment-rules',
  'Hydrogen is not yet a named sensitive sector under FIRB — but many hydrogen project components are. Here''s the practical position.',
  'hydrogen', 'guide',
  $json$[
    {"heading":"Hydrogen''s FIRB classification","body":"Hydrogen itself is not separately classified as a sensitive sector under the Foreign Acquisitions and Takeovers Act 1975. Direct foreign investment in a hydrogen production project faces the standard economic test under FIRB — a national-interest analysis covering tax, employment, capital expenditure, and competition considerations.\n\nHowever, many components of an integrated hydrogen project attract additional scrutiny under overlapping regimes."},
    {"heading":"The critical-infrastructure overlap","body":"Under the 2025 amendments to the Security of Critical Infrastructure Act, ammonia export terminals and major pipeline infrastructure are now routinely classified as critical infrastructure. For hydrogen projects planning ammonia export (most of them), this adds a national-security review layer to the FIRB economic test.\n\nIn practice, this means a foreign acquirer of a hydrogen-to-ammonia export project faces combined FIRB + SOCI review comparable to LNG or refining asset acquisitions. Timelines extend to 90-180 days for straightforward matters."},
    {"heading":"Electricity-supply dependencies","body":"Green hydrogen projects typically require dedicated renewable electricity supply — solar, wind, or hybrid with battery storage. Foreign acquisition of the electricity-generation assets separately triggers FIRB review because electricity generation is named sensitive sector.\n\nDeal structure matters. A foreign acquirer buying a hydrogen project AND the associated renewable generation faces two parallel FIRB tests. Acquiring just the hydrogen project while the renewable generation is Australian-owned simplifies the review."},
    {"heading":"Water and land","body":"Hydrogen projects consume water at scale — typically 9-15 litres per kg hydrogen produced. Large-scale projects require water licences or desalination capacity. Agricultural-land acquisition for renewable generation triggers FIRB agricultural-land rules with a $15M threshold.\n\nForeign-investor structures need to consider the full project footprint, not just the headline hydrogen plant. Pre-lodgement engagement with Treasury and CISC is increasingly the norm for projects above A$500M total investment."},
    {"heading":"Allied-nation fast track","body":"US, Japan, Korea, EU and UK investors benefit from streamlined FIRB review under bilateral frameworks. For hydrogen specifically, Japanese and Korean investors are the dominant foreign participants — aligned with the off-take market — and have clean FIRB precedent.\n\nChinese and Russian investors face materially more complex review. Chinese hydrogen investment in Australia has been rare; Russian investment effectively non-existent."},
    {"heading":"Practical advice","body":"For non-Australian investors considering hydrogen exposure: start with portfolio holdings in ASX-listed pure-plays below 10% of any individual company — these remain exempt from FIRB notification under the standard portfolio rules. Direct project equity above A$50M, or shareholdings above 10% in any hydrogen company, warrant pre-lodgement engagement with a foreign-investment lawyer.\n\nBudget 90-180 days for direct project FIRB + SOCI approvals. Legal fees for sensitive-sector-equivalent hydrogen applications typically run A$120K-$250K. Allied-nation investors have the cleanest path; foreign-government investors should plan 6-12 month timelines."}
  ]$json$::jsonb,
  $json$["FIRB","hydrogen","SOCI","foreign investment","critical infrastructure","Australia"]$json$::jsonb,
  6, true, NOW(),
  ARRAY['hydrogen','oil-gas'], ARRAY['foreign_investment_lawyer']::text[],
  'published','Market Research Team','Invest.com.au'
),

(
  'SMSF Hydrogen Investment: Sizing and Concentration Rules',
  'smsf-hydrogen-investment-sizing',
  'Pure-play hydrogen names are small-cap and volatile. Here''s how to size them inside an SMSF without breaking trustee rules.',
  'hydrogen', 'guide',
  $json$[
    {"heading":"What works inside an SMSF","body":"ASX-listed hydrogen stocks (FMG, ORG, HZR, PRL, FHE, PH2, SPN, RNE) and the Global X Hydrogen ETF (HGEN) are conventional listed investments. SMSFs can hold them subject to the normal investment-strategy and sole-purpose test requirements — no special approvals needed.\n\nFor most SMSF trustees seeking hydrogen exposure, ASX-listed instruments are sufficient. Wholesale unlisted hydrogen funds are thin on the ground in Australia; direct project equity is typically wholesale-only and above most SMSF scale."},
    {"heading":"The concentration problem","body":"ASX hydrogen pure-plays have market caps under A$200M in most cases. Liquidity is thin. Pre-FID stocks move on single news items — off-take announcements, policy awards, drilling results — by 20-50% moves in a session.\n\nThis creates a concentration risk inside SMSFs. A $100K position in a $150M market cap stock equals 0.07% of the company — fine in isolation — but a 30% one-day drawdown is a plausible scenario for small-cap pre-FID developers. Sizing needs to reflect that volatility."},
    {"heading":"Suggested sizing framework","body":"For SMSFs seeking hydrogen exposure: (1) total hydrogen allocation no more than 3-5% of portfolio equity; (2) within that, HGEN ETF as 50-70% of the allocation for diversification; (3) individual pure-play positions capped at 0.5-1% of portfolio, no more than three individual names.\n\nThis framework ships reasonable sector exposure while limiting single-name blowup risk to manageable levels."},
    {"heading":"The in-house assets trap","body":"As with any small-cap sector, SMSF trustees who work at an ASX hydrogen company face the 5% in-house assets rule. Employer-share-scheme issuance into the SMSF can breach the 5% limit quickly if not monitored.\n\nA routine annual review by your SMSF accountant should catch this. Breaches trigger corrective action and potentially deemed income at the highest marginal rate."},
    {"heading":"Volatility and rebalancing","body":"Because hydrogen pure-plays move in large percentages, rebalancing discipline matters more than in diversified equity allocations. A stock that 3x''s off a single FID announcement can push an SMSF allocation well outside its target range in days.\n\nA simple rebalancing rule: review allocation quarterly; trim positions back to target if they move >50% above target weight, add to positions that fall >50% below target (assuming the investment thesis remains intact). This disciplined approach captures upside volatility while managing downside risk."},
    {"heading":"Tax and franking","body":"Hydrogen pure-plays typically pay no dividend — they''re reinvestment-phase companies. Fortescue (the main exception) pays franked dividends.\n\nFor SMSF pension-phase holdings, the franking treatment of FMG''s iron-ore-derived dividends is significant — 0% effective tax on grossed-up dividends with full franking refund. Hydrogen pure-plays don''t contribute to this structural advantage; they''re held for capital-return potential rather than franked income."}
  ]$json$::jsonb,
  $json$["SMSF","hydrogen","concentration","sizing","small-cap","franking"]$json$::jsonb,
  6, true, NOW(),
  ARRAY['hydrogen'], ARRAY['smsf_accountant','energy_financial_planner']::text[],
  'published','Market Research Team','Invest.com.au'
),

(
  'Hydrogen Storage and Transport Economics: Where Value Actually Sits',
  'hydrogen-storage-transport-economics',
  'Production is only part of the cost stack. Storage and transport can double delivered-cost. Here''s the unglamorous part of the value chain.',
  'hydrogen', 'analysis',
  $json$[
    {"heading":"The cost-stack problem","body":"Much ASX hydrogen investment conversation focuses on production cost — LCOH at the electrolyser gate. That number is important but incomplete. Delivered hydrogen cost at an end-user includes production + compression/liquefaction + storage + transport + regasification or conversion at destination.\n\nFor long-distance export (Australia to Japan/Korea), the post-production cost stack frequently equals or exceeds the production cost itself. Projects that look economic at the production gate can be uneconomic at delivered-to-customer pricing."},
    {"heading":"Compression and liquefaction","body":"Pipeline-scale hydrogen transport requires compression to 100-350 bar. Cost: US$0.10-0.30/kg hydrogen depending on scale and distance. Shipping-scale requires either liquefaction (-253°C, consumes 30%+ of energy content), compression to 700+ bar, or chemical conversion to an energy carrier.\n\nEach pathway has distinct cost structures. Liquid hydrogen shipping at scale is not commercially proven. Compressed gas shipping is impractical for export volumes. Chemical conversion (ammonia is dominant) trades compression/liquefaction cost for conversion cost."},
    {"heading":"Ammonia as de-facto hydrogen carrier","body":"Haber-Bosch synthesis converts hydrogen to ammonia at a round-trip energy efficiency of roughly 80% — meaning 20% of the hydrogen''s energy content is lost in conversion. Capex for ammonia synthesis is material — US$1-2B for commercial-scale facilities.\n\nAt destination, ammonia can be: (1) burned directly in modified gas or coal plants (Japan/Korea coal co-firing), (2) used as feedstock for fertiliser manufacture, or (3) cracked back to hydrogen for further use. Cracking costs another 15-25% of energy content.\n\nThe net round-trip efficiency for ''green hydrogen production → ammonia → shipping → cracking back to hydrogen at destination'' is roughly 50-60%. This is the structural economic limit."},
    {"heading":"Transport","body":"Ammonia shipping from Australia to Japan/Korea costs roughly US$0.50-1.50/kg hydrogen-equivalent depending on vessel scale, port handling, and utilisation. Infrastructure exists — existing ammonia carrier fleet plus dedicated vessels being built for the new trade.\n\nLiquid hydrogen shipping is pilot-scale (Kawasaki Heavy Industries Suiso Frontier). Commercial-scale liquid H2 shipping remains expensive and logistically complex; ammonia is expected to dominate trade through the 2030s at minimum."},
    {"heading":"Storage","body":"Hydrogen storage at scale uses salt-cavern facilities (cheapest, but geographically limited), depleted gas fields (limited permeability constraints), or above-ground spheres (highest cost). Australia has salt caverns under study in the Pilbara and SA but commercial-scale operations don''t exist yet.\n\nStorage cost is geographic and scale-dependent. A project without credible storage capacity has higher effective cost because of matching-production-to-shipment windows. This is a real engineering cost most prospectuses under-emphasise."},
    {"heading":"Where the investable value sits","body":"Project economics favour integrated producer-exporters — developers who control production, conversion to ammonia, and port terminal access. Pure electrolyser-stage developers must partner with midstream operators; margin sharing reduces returns.\n\nFor ASX investors, this is why indirect majors (Woodside, Origin, Fortescue) have some structural advantages — they have port-and-pipeline logistics expertise and balance sheets to build integrated facilities. Pure-play pre-FID developers are more economically risky unless they''ve secured integrated off-take arrangements."}
  ]$json$::jsonb,
  $json$["hydrogen","ammonia","storage","transport","LCOH","export"]$json$::jsonb,
  7, true, NOW(),
  ARRAY['hydrogen'], ARRAY['resources_fund_manager','energy_financial_planner']::text[],
  'published','Market Research Team','Invest.com.au'
),

(
  'The Australian National Hydrogen Strategy 2024: What Actually Changed',
  'australian-national-hydrogen-strategy-2024',
  'The strategy update moved Australia from ambition to commitment. Here''s what matters for ASX investors.',
  'hydrogen', 'analysis',
  $json$[
    {"heading":"The original 2019 strategy","body":"Australia''s original National Hydrogen Strategy (2019) targeted being a ''major global supplier'' of hydrogen by 2030. The strategy was ambitious but light on binding mechanisms — mostly aspirational targets and state-coordination frameworks.\n\nIn 2019-2021 this drove announcements across the sector but did not substantially move the cost curve or create firm off-take commitments."},
    {"heading":"What changed in 2024","body":"The 2024 National Hydrogen Strategy update made four material shifts. First, it introduced the $2B Hydrogen Headstart Production Credit — the first federal instrument providing dollar-per-kg support tied to actual production. Second, it formalised state-commonwealth coordination on project approvals. Third, it set specific export-volume targets aligned with Japan and Korea demand projections. Fourth, it clarified the taxonomy and minimum standards for ''green'' certification.\n\nThe combination moves the policy from ambition to commitment. Production credits survive most government changes once committed — unlike grant programs that can be redirected easily."},
    {"heading":"The production-credit mechanism","body":"Hydrogen Headstart allocates production credits over 10 years of operation for successful projects. This matters because it aligns government support with actual delivery, not announcements. A project that receives Hydrogen Headstart must deliver hydrogen production at scale to receive the credit stream.\n\nThe mechanism indirectly de-risks off-take for first-mover customers — the credit tops up off-take pricing to an economic return for the producer, effectively creating a government-backed floor on delivered-hydrogen pricing."},
    {"heading":"State alignment","body":"WA, Queensland, SA and Tasmania have each established state hydrogen programs that complement Hydrogen Headstart with site allocation, tax concessions, and grid-connection support. The 2024 strategy formalised information-sharing and approval-coordination arrangements between Commonwealth and state levels.\n\nFor ASX investors, this means project approval timelines are faster and less subject to inter-governmental conflict than in the 2019-2022 period."},
    {"heading":"Certification and market integrity","body":"The strategy update introduced a Guarantee of Origin (GO) scheme for hydrogen and renewable-equivalent products. GO certificates are essential for premium pricing in EU markets (which require verifiable green origin) and increasingly in Japan and Korea.\n\nFor ASX developers, GO certification becomes a requirement for off-take contracts rather than a nice-to-have. Projects without clear GO pathways face pricing and market access constraints."},
    {"heading":"Investor implications","body":"The 2024 strategy is a structural positive for ASX hydrogen exposure. It doesn''t change unit economics — projects still need to produce at competitive cost — but it materially de-risks three of the four main risk categories: policy, off-take, and approvals. The remaining risk category is project execution and cost.\n\nPure-plays aligned with Hydrogen Headstart awards and GO-certified are materially advantaged. HGEN ETF holdings are indirectly positively affected through their Australian component. A specialist energy financial planner can help identify which ASX names benefit most directly."}
  ]$json$::jsonb,
  $json$["National Hydrogen Strategy","policy","Australia","Hydrogen Headstart","GO certification"]$json$::jsonb,
  7, true, NOW(),
  ARRAY['hydrogen'], ARRAY['energy_financial_planner','resources_fund_manager']::text[],
  'published','Market Research Team','Invest.com.au'
),

(
  'Pure Hydrogen (PH2) vs Hazer (HZR): Comparing Turquoise Developers',
  'pure-hydrogen-ph2-vs-hazer-hzr',
  'Two ASX companies pursuing methane-pyrolysis hydrogen with different technology routes and geographic focuses.',
  'hydrogen', 'comparison',
  $json$[
    {"heading":"Same category, different bets","body":"Pure Hydrogen (ASX: PH2) and Hazer Group (ASX: HZR) both produce hydrogen from natural gas via methane pyrolysis-adjacent pathways. Neither uses water electrolysis. Both generate solid carbon by-product. Both are small-cap ASX pure-plays at pre-commercial scale.\n\nFrom there the similarities diverge significantly."},
    {"heading":"Technology differences","body":"Hazer uses a proprietary iron-catalyst methane-pyrolysis process producing hydrogen and high-value graphitic carbon. The carbon by-product can be targeted toward battery anode materials — a high-margin end-market.\n\nPure Hydrogen has a diversified technology portfolio: steam methane reforming with carbon capture (blue hydrogen), methane pyrolysis, and some hydrogen distribution infrastructure. Not a single proprietary technology — more of an opportunistic multi-pathway approach."},
    {"heading":"Geographic and project differences","body":"Hazer is focused on Australian commercialisation — the Kwinana Commercial Demonstration Plant is the reference asset. Scale-up plans are mostly WA-centred with some US licensing arrangements.\n\nPure Hydrogen has more geographic diversification — Australia and US projects, multiple smaller developments rather than one flagship. This reduces single-project risk but also dilutes focus."},
    {"heading":"Scale and maturity","body":"Hazer''s Kwinana CDP is the larger operating facility of the two. Pure Hydrogen''s projects are mostly earlier-stage. For investors, Hazer is closer to commercial demonstration; Pure Hydrogen is more project-pipeline and less current demonstration.\n\nMarket caps reflect this: Hazer at ~A$150M vs Pure Hydrogen at ~A$50M. Hazer has more current value priced in; Pure Hydrogen more upside potential for pipeline conversion."},
    {"heading":"By-product economics","body":"Hazer''s graphitic carbon output is the specific commercial differentiator. If the carbon meets battery-anode grade specifications and achieves pricing comparable to synthetic graphite, the by-product revenue subsidises hydrogen production materially. This is Hazer''s bull case.\n\nPure Hydrogen''s carbon-capture-and-SMR route produces CO2 for sequestration, not high-value by-product. Economics depend on traditional SMR cost minus CCS cost plus hydrogen off-take — a simpler but less differentiated pathway."},
    {"heading":"Investor fit","body":"Both are speculative-end allocations within hydrogen portfolios. Hazer suits investors with a specific view on methane pyrolysis at commercial scale and on graphitic carbon market development. Pure Hydrogen suits investors preferring diversified multi-project exposure to blue-plus-turquoise-hydrogen pathways.\n\nPair-holding is reasonable given different technology bets. Combined position sizing should remain modest — 0.5-1.5% of portfolio across both — given small-cap volatility and binary project-stage outcomes."}
  ]$json$::jsonb,
  $json$["Pure Hydrogen","PH2","Hazer","HZR","methane pyrolysis","turquoise hydrogen","ASX"]$json$::jsonb,
  6, true, NOW(),
  ARRAY['hydrogen'], ARRAY['resources_fund_manager']::text[],
  'published','Market Research Team','Invest.com.au'
)

ON CONFLICT (slug) DO NOTHING;
