-- Migration: respondent_scorecards — the Decision Kit's post-call scorecards.
--
-- Once bids/responses arrive on a consumer's quote auction (or an accepted
-- brief), the Decision Kit helps them choose between the SPECIFIC respondents:
-- a factual comparison matrix, per-service intro-call scripts, and — gated
-- behind the `decision_kit` feature flag — these post-call scorecards. After
-- an intro call the consumer rates each respondent against a small fixed set
-- of criteria (clarity, fee transparency, relevance, rapport, confidence) and
-- the client-side summary combines the scores ("your scores suggest you lean
-- toward…" — never an auto-recommendation).
--
-- OWNER KEY — `owner_key` = the consumer's contact email (lower-cased).
--   This matches the *real* surfaces this feature attaches to: BOTH the brief
--   tracker (app/briefs/[slug], gated by `?email=` === advisor_auctions.
--   contact_email) and the quote page (app/quotes/[slug], the consumer
--   verifies with the email they posted with) authorise the consumer by
--   contact_email — there is no auth user id on these anonymous email-link
--   surfaces. So scorecards are keyed by that same email, exactly like
--   brief_outcomes.consumer_email and engagement_registry.consumer_email.
--
-- brief_id  — the advisor_auctions.id the scorecard belongs to (a "brief" is
--   an advisor_auctions row with flow_type='accept'; a quote auction is the
--   same table with source='public_job'). Always set.
-- auction_id — kept nullable for symmetry/forward-compat; today brief_id is
--   the single advisor_auctions.id either surface uses, so callers set
--   brief_id and leave auction_id null. (Documented here so a future reader
--   doesn't think one is the quote-id and the other the brief-id — they are
--   the same advisor_auctions.id; auction_id is reserved, not yet populated.)
-- professional_id — professionals.id of the respondent being scored.
--
-- RLS — service-role-only, copying engagement_registry / brief_outcomes /
--   prospects. RATIONALE: the consumer identity factor on these surfaces is
--   an email match (or a signed token), NOT a Supabase JWT, so there is no
--   auth.uid() to scope owner policies against. All reads/writes go through
--   the service-role admin client from a server route that re-verifies the
--   owner email against advisor_auctions.contact_email before touching this
--   table — identical to how brief_outcomes is written from
--   /api/outcomes/submit. An owner RLS policy here would be security theatre
--   (no JWT to bind to); the email re-check at the route is the real gate.
--
-- Rollback:
--   DROP TABLE IF EXISTS public.respondent_scorecards;

BEGIN;

CREATE TABLE IF NOT EXISTS public.respondent_scorecards (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brief_id integer NOT NULL,
  auction_id integer,
  professional_id integer NOT NULL,
  -- Consumer identity = lower-cased contact email (the owner key on both the
  -- brief tracker and the quote surface). NOT an auth user id by design.
  owner_key text NOT NULL,
  -- Per-criterion 1-5 ratings, e.g. { "clarity": 4, "fee_transparency": 5, ... }.
  -- Stored as jsonb so the fixed criteria set can evolve without a migration;
  -- the API validates keys/range with Zod before writing.
  criteria jsonb NOT NULL DEFAULT '{}'::jsonb,
  notes text CHECK (notes IS NULL OR char_length(notes) <= 2000),
  overall smallint CHECK (overall IS NULL OR (overall >= 1 AND overall <= 5)),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  -- One scorecard per (consumer, brief/auction, respondent); upsert on re-save.
  UNIQUE (owner_key, brief_id, professional_id)
);

CREATE INDEX IF NOT EXISTS idx_respondent_scorecards_owner_brief
  ON public.respondent_scorecards (owner_key, brief_id);
CREATE INDEX IF NOT EXISTS idx_respondent_scorecards_professional
  ON public.respondent_scorecards (professional_id);

ALTER TABLE public.respondent_scorecards ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Service role manages respondent_scorecards" ON public.respondent_scorecards;
CREATE POLICY "Service role manages respondent_scorecards"
  ON public.respondent_scorecards FOR ALL TO service_role USING (true) WITH CHECK (true);

COMMIT;
